### ISSUE TITLE
EOFException after subscription

### ISSUE THREAD

**Issue by schoeda** [apollographql/apollo-kotlin#3665]
**Summary**
EOFException after some minutes of subscription.

**Version**
v3.0.0-rc01

**Description**
If we do a subscription on the Apollo client like this:

```
try {
    apolloSyncClient?.subscription(ChangedFacilityPickJobsSubscription())?.toFlow()?.collect {
        // Do some stuff.
    }
} catch (e: Exception) {
    // EOFException is thrown here!
}
```

we get after some minutes this exception:

```
com.apollographql.apollo3.exception.ApolloNetworkException: Network error while executing ChangedFacilityPickJobs!
    com.apollographql.apollo3.exception.ApolloNetworkException: Network error while executing ChangedFacilityPickJobs
        at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$$inlined$map$1$2.emit(Collect.kt:144)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:77)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:59)
        at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$3.invokeSuspend(WebSocketNetworkTransport.kt:212)
        at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$3.invoke(Unknown Source:13)
        at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$3.invoke(Unknown Source:6)
        at com.apollographql.apollo3.internal.FlowsKt$transformWhile$1$invokeSuspend$$inlined$collectWhile$1.emit(flows.kt:53)
        at com.apollographql.apollo3.internal.FlowsKt$transformWhile$1$invokeSuspend$$inlined$collectWhile$2.emit(Collect.kt:135)
        at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$$inlined$filter$1$2.emit(Collect.kt:137)
        at kotlinx.coroutines.flow.SubscribedFlowCollector.emit(Unknown Source:2)
        at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt:351)
        at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: java.io.EOFException
        at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
        at okio.RealBufferedSource.readByte(RealBufferedSource.kt:209)
        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```

This problem is reproducible and happen every time if we subscribe. Before the exception is thrown, everything works fine and we get the updates from GraphQL.

Our Apollo client looks like this:

```
val httpServerUrl = "..."

ApolloClient
                    .Builder()
                    .httpServerUrl(httpServerUrl = httpServerUrl)
                    .httpEngine(DefaultHttpEngine())
                    .subscriptionNetworkTransport(WebSocketNetworkTransport
                                                          .Builder()
                                                          .serverUrl(httpServerUrl)
                                                          .protocol(AuthenticationProtocol.create())
                                                          .webSocketEngine(DefaultWebSocketEngine())
                                                          .build())
                    .build()
```

Maybe someone of you have an idea what the problem is.

Thank you,
Daniel

**Comment by martinbonnin** [comment]
Hi 👋 Thanks for reaching out!

Looks like the server closed the connection? Maybe you need to setup some kind of keepalive or something else? Do you know what server is used on your backend?

**Comment by schoeda** [comment]
Hey Martin!

Thanks for the hint, we will check that with the server side closed connection. We use the Apollo Server 2. I saw that there is an [reconnect-flag](https://www.apollographql.com/docs/react/data/subscriptions/) in the React-Client, do you know if it also available for the Android client?

**Comment by martinbonnin** [comment]
> We use the Apollo Server 2

👍  I'll dig into the keep alive options for AS2. I know that [some cloud providers will close the WebSocket after some inactivity time](https://github.com/apollographql/fullstack-tutorial/issues/240) so maybe this is what's happening at the moment.

> I saw that there is an reconnect-flag in the React-Client, do you know if it also available for the Android client?

We don't have such a thing at the moment. This feels like something that would need to be customizable. Like reconnect on some errors but still fail the stream on some others?

**Comment by schoeda** [comment]
We updated our Server to AS3 and test it now, maybe that helps. Until now we don't have other errors than the one with EOFException.

Thanks for the hint with the [inactive WebSockets](https://github.com/apollographql/fullstack-tutorial/issues/240), we check that too.

**Comment by martinbonnin** [comment]
Hi 👋  `3.0.0-rc03` has a `reconnectWhen {}` option so that you can automatically reconnect your websocket under the hood. Another option would be to call `Flow.retry {}` only on the Flows that you want to retry (or all of them!)

This won't fix the root issue of whether there is some keep alive required somewhere but at least this should make it transparent to your application?

**Comment by schoeda** [comment]
Hey Martin!

Yes that helps us, so we can keep alive the connection. Thank you very much!

Maybe it is also possible to add a flag `isWebSocketConnected` in the `ApolloClient`. So we can check the connection for example if the user reenters the application? So one would have several options for the connection handling.

**Comment by martinbonnin** [comment]
> Maybe it is also possible to add a flag isWebSocketConnected in the ApolloClient. 

I'm not too fond of that because that would open the door to multiple race conditions. What if the websocket is currently connecting or is connected between the check and whatever action you're going to do next.

> So we can check the connection for example if the user reenters the application? So one would have several options for the connection handling.

Ideally, an application should start subscriptions in a scope that's bound to the lifecyle so that they are started in `onStart` (or `onResume`) and cancelled in `onStop` (or `onPause`). 

I can see reasons to force close a connection (see [this issue](https://github.com/apollographql/apollo-android/issues/3666#issuecomment-993000163)) but not really for creating them as that would conflict with what `WebSocketNetworkTransport`. 

Can you share more about your use case?

**Comment by schoeda** [comment]
In our case we have a CoroutineScope that is bound to the application. Why we do that? We want a data sync independent from the view. But maybe this is not the best idea and we have to refactor this. I have to do some checks and maybe we can build it like you say.

My biggest question in this case is, do i get changes that happen between `onPause` and `onStart` with a new subscription by `onStart`?

**Comment by martinbonnin** [comment]
> In our case we have a CoroutineScope that is bound to the application.

I guess that's ok too. As long as there is a well identified scope, the subscription will be restarted when the application is restarted and closed when the application is closed so that's fine and you don't need to check `isWebSocketConnected`?

> My biggest question in this case is, do i get changes that happen between onPause and onStart with a new subscription by onStart?

Nope, if you start the Flow in `onStart` and cancel it in `onStop` , no value will be collected after `onStop` so you won't get background update.

If you want background updates then an application scope sounds reasonable but I don't see why you'd need `isWebSocketConnected` in that case?

**Comment by schoeda** [comment]
If the reconnect works fine, we need no `isWebSocketConnected`. It was only an idea to do a check that everything works good. For us it is very important that we show always the right data and that we notice if something is wrong. But with the exception handler we can implement a `isWebSocketConnected` by ourselves.

So, you can forget the `isWebSocketConnected` idea.

**Comment by martinbonnin** [comment]
Gotcha 👍 . Yep, we'll make sure the reconnect work before adding new potentially footgunesque APIs 🦶 🔫 .

I'm closing this issue because it seems the underlying cause of why the server closes the connection is outside of Apollo Kotlin control and there is an acceptable workaround using `reconnectWhen {}`. 

Feel free to leave a message if you have more details about why the server is closing the connection and you want us to investigate ping/pong messages or another way to keep the connection open.

**Comment by schoeda** [comment]
Thanks for your support @martinbonnin !
