### ISSUE TITLE
NullPointerException when LruCache is trimmed

### ISSUE THREAD

**Issue by RicoYao** [apollographql/apollo-kotlin#3818]
**Summary**
When the LruCache is being trimmed, a NullPointerException is thrown

**Version**
3.0.0

**Description**
* Set a low maxSizeBytes value when configuring the memory cache. e.g. `MemoryCacheFactory(maxSizeBytes = 20000)`
* Execute queries to populate the cache. Eventually an exception is observed as records are attempted to be merged:
```
java.lang.NullPointerException
        at com.apollographql.apollo3.cache.normalized.api.internal.LruCache.unlinkNode(LruCache.kt:141)
        at com.apollographql.apollo3.cache.normalized.api.internal.LruCache.trim(LruCache.kt:87)
        at com.apollographql.apollo3.cache.normalized.api.internal.LruCache.set(LruCache.kt:43)
        at com.apollographql.apollo3.cache.normalized.api.MemoryCache.merge(MemoryCache.kt:88)
        at com.apollographql.apollo3.cache.normalized.api.MemoryCache.merge(MemoryCache.kt:109)
        at com.apollographql.apollo3.cache.normalized.api.internal.OptimisticCache.merge(OptimisticCache.kt:38)
        at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore$writeOperationWithRecords$2.invoke(DefaultApolloStore.kt:205)
        at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore$writeOperationWithRecords$2.invoke(DefaultApolloStore.kt:198)
        at com.apollographql.apollo3.cache.normalized.internal.Guard.writeAccess(Guard.kt:19)
        at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore.writeOperationWithRecords(DefaultApolloStore.kt:198)
        at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore.writeOperation(DefaultApolloStore.kt:149)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$maybeWriteToCache$2.invokeSuspend(ApolloCacheInterceptor.kt:74)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$maybeWriteToCache$2.invoke(Unknown Source:8)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$maybeWriteToCache$2.invoke(Unknown Source:2)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor.maybeAsync(ApolloCacheInterceptor.kt:52)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor.maybeWriteToCache(ApolloCacheInterceptor.kt:72)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor.maybeWriteToCache$default(ApolloCacheInterceptor.kt:59)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$readFromNetwork$1.invokeSuspend(ApolloCacheInterceptor.kt:328)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$readFromNetwork$1.invoke(Unknown Source:8)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$readFromNetwork$1.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Collect.kt:136)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:77)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:59)
        at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invokeSuspend(HttpNetworkTransport.kt:83)
        at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invoke(Unknown Source:8)
        at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:212)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:195)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collect$suspendImpl(ChannelFlow.kt:167)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collect(Unknown Source:0)
        at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1.collect(SafeCollector.common.kt:114)
        at kotlinx.coroutines.flow.FlowKt__ReduceKt.single(Reduce.kt:179)
        at kotlinx.coroutines.flow.FlowKt.single(Unknown Source:1)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor.readOneFromNetwork(ApolloCacheInterceptor.kt:336)
```

**Comment by BoD** [comment]
Hi! Thanks for reporting this.

So far I haven't managed to reproduce the crash, would it be possible for you to share some code? Thanks!
