### ISSUE TITLE
Certain queries always cause java.lang.IllegalStateException: BufferedSourceJsonReader cannot rewind.

### ISSUE THREAD

**Issue by tomoya0x00** [apollographql/apollo-kotlin#3914]
**Summary**
If a query contains a fragment of query, parsing an HTTP response is always failed.

```
 Caused by: java.lang.IllegalStateException: BufferedSourceJsonReader cannot rewind.
     at com.apollographql.apollo3.api.json.BufferedSourceJsonReader.rewind(BufferedSourceJsonReader.kt:938)
     ...
     at com.apollographql.apollo3.api.ObjectAdapter.fromJson(Adapters.kt:230)
     at com.apollographql.apollo3.api.NullableAdapter.fromJson(Adapters.kt:58)
     at com.apollographql.apollo3.api.internal.ResponseParser.parse(ResponseParser.kt:35)
     at com.apollographql.apollo3.api.Operations.parseJsonResponse(Operations.kt:59)
     at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1$response$1.invoke(HttpNetworkTransport.kt:74)
 	... 77 more
```

**Version**
3.1.0

**Description**

```
query SearchSomething {
  ...Something
}

fragment Something on Query {
  searchSomething {
    name
  }
}
```

If we write the above query,  we can get generated ResponseAdapter like this:

```
public object SearchSomethingQuery_ResponseAdapter {
  public object Data : Adapter<SearchSomethingQuery.Data> {
    public val RESPONSE_NAMES: List<String> = listOf("__typename")

    public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
        SearchSomethingQuery.Data {
      var __typename: String? = null

      while(true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> __typename = StringAdapter.fromJson(reader, customScalarAdapters)
          else -> break
        }
      }

      check(__typename != null) {
        "__typename was not found"
      }

      reader.rewind()
      val fragments = com.example.SearchSomething_ResponseAdapter.Data.Fragments.fromJson(reader,
          customScalarAdapters)

      return SearchSomething.Data(
        __typename = __typename,
        fragments = fragments
      )
  ...
}
```

The above code contains `reader.rewind()`. But BufferedSourceJsonReader doesn't support `rewind` .

https://github.com/apollographql/apollo-kotlin/blob/main/apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/json/BufferedSourceJsonReader.kt#L938

So parsing JSON is always failed, if we get it from the network.

`reader.rewind()`  is added by the below code.

https://github.com/apollographql/apollo-kotlin/blob/main/apollo-compiler/src/main/kotlin/com/apollographql/apollo3/compiler/codegen/kotlin/adapter/AdapterCommon.kt#L102

**Comment by martinbonnin** [comment]
Good catch 👍 . This is happening with fragments on the `Query` type because we never buffer them :( (see adapter code [there](https://github.com/apollographql/apollo-kotlin/blob/0979dbf4d1d5d3eba6fb7a413e16c6a25e02debb/apollo-compiler/src/main/kotlin/com/apollographql/apollo3/compiler/codegen/kotlin/file/ExecutableCommon.kt#L53)). 

This is most likely going to be fixed with https://github.com/apollographql/apollo-kotlin/issues/3774 that I've had on my plate for some time now (because the `Query` type is always monomorphic and never requires buffering). In the meantime, you can try avoiding fragments on the root `Query` type.

**Comment by tomoya0x00** [comment]
Thanks for your quick reply and for providing the current status of it!

> In the meantime, you can try avoiding fragments on the root Query type.

Yeah, I've already tried it and it works fine. Thank you for kindly advice 😉

**Comment by martinbonnin** [comment]
Turns out I was wrong, even monomorphic fields might require buffering if fragments read merged fields.

See https://github.com/apollographql/apollo-kotlin/pull/3973 for a fix.
