### ISSUE TITLE
❄️  Flaky test: Timed out waiting for 500 ms

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#3920]
FWIW, looks like we have a flaky test. Usually re-running the CI is enough. I'm logging the error in this issue so that we can take action if this becomes too much of an issue.

```
test.WatcherTest[javaCodegen] > cacheOnlyFetchPolicy[javaCodegen] FAILED
    kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 500 ms
        at (Coroutine boundary.()
        at com.apollographql.apollo3.testing.ChannelsKt$receiveOrTimeout$2.invokeSuspend(channels.kt:9)
        at test.WatcherTest$cacheOnlyFetchPolicy$2.invokeSuspend(WatcherTest.kt:313)
        at com.apollographql.apollo3.testing.RunWithMainLoopJvmKt$runTest$3.invokeSuspend(runWithMainLoopJvm.kt:15)

        Caused by:
        kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 500 ms
            at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:186)
            at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
            at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)
            at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
            at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:69)
            at java.lang.Thread.run(Thread.java:750)
```

**Comment by martinbonnin** [comment]
```
test.WatcherTest[javaCodegen] > cacheOnlyFetchPolicy[javaCodegen] FAILED
    kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 500 ms
        at (Coroutine boundary.()
        at com.apollographql.apollo3.testing.ChannelsKt$receiveOrTimeout$2.invokeSuspend(channels.kt:9)
        at test.WatcherTest$cacheOnlyFetchPolicy$2.invokeSuspend(WatcherTest.kt:313)
        at com.apollographql.apollo3.testing.RunWithMainLoopJvmKt$runTest$3.invokeSuspend(runWithMainLoopJvm.kt:15)

        Caused by:
        kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 500 ms
            at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:186)
            at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
            at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)
            at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
            at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:69)
            at java.lang.Thread.run(Thread.java:750)
```

**Comment by martinbonnin** [comment]
com.apollographql.apollo3.cache.http.internal.DiskLruCacheTest > rebuildJournalFailureAllowsEvictAll FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 60 seconds
        at java.io.FileOutputStream.close0(Native Method)
        at java.io.FileOutputStream.access$000(FileOutputStream.java:53)
        at java.io.FileOutputStream$1.close(FileOutputStream.java:356)
        at java.io.FileDescriptor.closeAll(FileDescriptor.java:212)
        at java.io.FileOutputStream.close(FileOutputStream.java:354)
        at okio.OutputStreamSink.close(JvmOkio.kt:72)
        at okio.ForwardingSink.close(ForwardingSink.kt:37)
        at okio.ForwardingSink.close(ForwardingSink.kt:37)
        at com.apollographql.apollo3.cache.http.internal.FaultHidingSink.close(FaultHidingSink.kt:55)
        at okio.RealBufferedSink.close(RealBufferedSink.kt:286)
        at com.apollographql.apollo3.cache.http.internal.DiskLruCacheTest$Companion.setString(DiskLruCacheTest.kt:1991)
        at com.apollographql.apollo3.cache.http.internal.DiskLruCacheTest$Companion.access$setString(DiskLruCacheTest.kt:1957)
        at com.apollographql.apollo3.cache.http.internal.DiskLruCacheTest.set(DiskLruCacheTest.kt:1903)
        at com.apollographql.apollo3.cache.http.internal.DiskLruCacheTest.rebuildJournalFailureAllowsEvictAll(DiskLruCacheTest.kt:967)

**Comment by martinbonnin** [comment]
```
RxJavaTest > errorsAreReceived FAILED
    java.lang.AssertionError: No errors (latch = 1, values = 0, errors = 0, completions = 0, timeout!, disposed!)
        at io.reactivex.observers.BaseTestConsumer.fail(BaseTestConsumer.java:189)
        at io.reactivex.observers.BaseTestConsumer.assertError(BaseTestConsumer.java:318)
        at RxJavaTest.errorsAreReceived(RxJavaTest.kt:56)
```

**Comment by martinbonnin** [comment]
```
test.WatcherTest[javaCodegen] > cacheOnlyFetchPolicy[javaCodegen] FAILED
    kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 500 ms
        at (Coroutine boundary.()
        at com.apollographql.apollo3.testing.ChannelsKt$receiveOrTimeout$2.invokeSuspend(channels.kt:9)
        at test.WatcherTest$cacheOnlyFetchPolicy$2.invokeSuspend(WatcherTest.kt:313)
        at com.apollographql.apollo3.testing.RunWithMainLoopJvmKt$runTest$3.invokeSuspend(runWithMainLoopJvm.kt:15)

        Caused by:
        kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 500 ms
            at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:186)
            at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
            at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)
            at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
            at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:69)
            at java.lang.Thread.run(Thread.java:750)
```

**Comment by martinbonnin** [comment]
```
com.apollographql.apollo3.cache.http.internal.DiskLruCacheTest > rebuildJournalFailureAllowsRemovals FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 60 seconds
        at sun.nio.fs.UnixNativeDispatcher.rename0(Native Method)
        at sun.nio.fs.UnixNativeDispatcher.rename(UnixNativeDispatcher.java:188)
        at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:388)
        at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
        at java.nio.file.Files.move(Files.java:1395)
        at okio.NioSystemFileSystem.atomicMove(NioSystemFileSystem.kt:78)
        at okio.ForwardingFileSystem.atomicMove(ForwardingFileSystem.kt:225)
        at com.apollographql.apollo3.cache.http.internal.FaultyFileSystem.atomicMove(FaultyFileSystem.kt:62)
        at com.apollographql.apollo3.cache.http.internal.DiskLruCacheKt.rename(DiskLruCache.kt:1020)
        at com.apollographql.apollo3.cache.http.internal.DiskLruCacheKt.access$rename(DiskLruCache.kt:1)
        at com.apollographql.apollo3.cache.http.internal.DiskLruCache.completeEdit(DiskLruCache.kt:493)
        at com.apollographql.apollo3.cache.http.internal.DiskLruCache$Editor.commit(DiskLruCache.kt:834)
        at com.apollographql.apollo3.cache.http.internal.DiskLruCacheTest.set(DiskLruCacheTest.kt:1904)
        at com.apollographql.apollo3.cache.http.internal.DiskLruCacheTest.rebuildJournalFailureAllowsRemovals(DiskLruCacheTest.kt:924)
```
