### ISSUE TITLE
[3.x] graphql-ws protocol issue

### ISSUE THREAD

**Issue by Krillsson** [apollographql/apollo-kotlin#3990]
**Summary**
After upgrading to Apollo 3, `graphql-ws` subscription protocol does not work out of the box with `com.graphql-java-kickstart.graphql-java-servlet`

**Version**
3.2.0

**Description**
Much like #3205. I had issue opening a connection with our BE server since the implementation in `SubscriptionWsProtocol` now appear to be sending messages in binary format compared to 2.x that sent text. The BE is running [com.graphql-java-kickstart.graphql-java-servlet](https://github.com/graphql-java-kickstart/graphql-java-servlet), and the implementation of `graphql-ws` is in the apollo package.

I got it to work again by providing a copy of `SubscriptionWsProtocol`, but with the `sendMessageMapBinary(message)` methods swapped out with `sendMessageMap(message, WsFrameType.Text)`.

Would it be possible to add support for selecting `WsFrameType` during creation like with `GraphQLWsProtocol`?

If so, that should be something I could easily contribute with a PR.

**Comment by BoD** [comment]
Hi! 👋  Thanks for reporting this!

Just to clarify on the terminology:
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md) is a legacy (no longer maintained) protocol. But it is currently still the default used protocol in Apollo Kotlin for backwards compatibility. It is implemented in `SubscriptionWsProtocol` 
- [graphql-ws](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md) is a more recent and recommended protocol, implemented in `GraphQLWsProtocol`

I am not familiar with graphql-java-servlet, but from what I understand the protocol implemented in the apollo package is `subscriptions-transport-ws`? 

With that out of the way, yes it would make sense to allow passing the frame type, like with `GraphQLWsProtocol`, and you're welcome to contribute a PR! 🙏

**Comment by BoD** [comment]
> Although SubscriptionWsProtocol.kt#L83 says "graphql-ws". Am I missing something? 🤔

No, this is confusing, but the header value for `subscriptions-transport-ws` is  `graphql-ws`, whereas the value for `graphql-ws` is `graphql-transport-ws` - I guess this is "for historic reasons" 😅

**Comment by BoD** [comment]
Hi @Krillsson! Since we're about to make a new release, and we just had another user impacted by this, I'm going to make the change now - apologies if you already started working on it! Thanks a lot for the report and willingness to provide a fix!

**Comment by Krillsson** [comment]
I already made the change but found out I have to fork it to submit a PR. Got a 403 when trying to push my branch.

No worries :+1:

**Comment by Krillsson** [comment]
a stacktrace for future reference

```kotlin
com.apollographql.apollo3.exception.ApolloNetworkException: Network error while executing <a subscription name>
        at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$$inlined$map$1$2.emit(Collect.kt:144)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:77)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:59)
        at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$3.invokeSuspend(WebSocketNetworkTransport.kt:249)
        at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$3.invoke(Unknown Source:13)
        at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$3.invoke(Unknown Source:6)
        at com.apollographql.apollo3.internal.FlowsKt$transformWhile$1$invokeSuspend$$inlined$collectWhile$1.emit(flows.kt:53)
        at com.apollographql.apollo3.internal.FlowsKt$transformWhile$1$invokeSuspend$$inlined$collectWhile$2.emit(Collect.kt:135)
        at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$$inlined$filter$1$2.emit(Collect.kt:137)
        at kotlinx.coroutines.flow.SubscribedFlowCollector.emit(Unknown Source:2)
        at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt:351)
        at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 10000 ms
        at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:186)
        at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
        at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:69)
        at java.lang.Thread.run(Thread.java:920)
```

**Comment by BoD** [comment]
[v3.2.1](https://github.com/apollographql/apollo-kotlin/releases/tag/v3.2.1) is now available, with the new parameter. Thanks again!
