### ISSUE TITLE
java.lang.NoSuchMethodError on ApolloClient.Builder()...build()

### ISSUE THREAD

**Issue by adsiddiqui-equinix** [apollographql/apollo-kotlin#4048]
**Question.**
I get this error when building the client (i am using Java):
```
java.lang.NoSuchMethodError: 'kotlinx.coroutines.channels.Channel kotlinx.coroutines.channels.ChannelKt.Channel$default(int, kotlinx.coroutines.channels.BufferOverflow, kotlin.jvm.functions.Function1, int, java.lang.Object)'
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:279)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at org.springframework.cloud.sleuth.instrument.async.TraceRunnable.run(TraceRunnable.java:68)
	at com.equinix.crh.asset.common.config.ThreadConfig$ContextDecorator.lambda$decorate$0(ThreadConfig.java:84)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoSuchMethodError: 'kotlinx.coroutines.channels.Channel kotlinx.coroutines.channels.ChannelKt.Channel$default(int, kotlinx.coroutines.channels.BufferOverflow, kotlin.jvm.functions.Function1, int, java.lang.Object)'
	at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport.<init>(WebSocketNetworkTransport.kt:65)
	at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport.<init>(WebSocketNetworkTransport.kt)
	at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$Builder.build(WebSocketNetworkTransport.kt:335)
	at com.apollographql.apollo3.ApolloClient$Builder.build(ApolloClient.kt:537)
	at com.equinix.crh.common.graphql.service.GraphQlHelperService.testApolloGraphQL(GraphQlHelperService.java:195)
	at com.equinix.crh.asset.service.AssetServiceImpl.getResourcesByProjectIdAndResourceType(AssetServiceImpl.java:2660)
	at com.equinix.crh.asset.service.AssetServiceImpl$$FastClassBySpringCGLIB$$6ba897cf.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.equinix.crh.asset.service.AssetServiceImpl$$EnhancerBySpringCGLIB$$1fceb613.getResourcesByProjectIdAndResourceType(<generated>)
	at com.equinix.crh.asset.service.AssetServiceImpl.getResourcesByProjectIdAndResourceTypeAsync(AssetServiceImpl.java:2626)
	at com.equinix.crh.asset.service.AssetServiceImpl$$FastClassBySpringCGLIB$$6ba897cf.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at org.springframework.cloud.sleuth.instrument.async.TraceAsyncAspect.traceBackgroundThread(TraceAsyncAspect.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:276)
	... 6 common frames omitted
```

I added the following to my build.gradle file:
```
plugins {
  id 'com.apollographql.apollo3' version '3.2.0'
}

dependencies {
  implementation "com.apollographql.apollo3:apollo-runtime:3.2.0"
  implementation "com.apollographql.apollo3:apollo-rx2-support:3.2.0"
}

apollo {
    packageName.set("com.equinix.crh")
    generateKotlinModels.set(false)
}
```

The models are generated successfully when i build the project, but when i do this:
```
ApolloClient apolloClient = new ApolloClient.Builder().serverUrl("https://apollo-fullstack-tutorial.herokuapp.com/graphql").build();
```
i get the `java.lang.NoSuchMethodError`

Any idea what is wrong here?

**Comment by adsiddiqui-equinix** [comment]
Thank you @BoD for the quick reply.
You are right, i am using Spring 2.3.0 RC, which has a dependency on `org.jetbrains.kotlinx:kotlinx-coroutines-*:1.3.6`
![image](https://user-images.githubusercontent.com/82800204/164226573-48925275-aab7-46fe-b2ee-7de9da6769b5.png)
![image](https://user-images.githubusercontent.com/82800204/164226652-40ddae74-68f8-419f-b180-10a7aa261167.png)

The apollo-kotlin dependencies on `org.jetbrains.kotlinx:kotlinx-coroutines-*:1.5.2`  are downgraded to 1.3.6
![image](https://user-images.githubusercontent.com/82800204/164226745-8434b7d6-37a0-4b0b-92d6-31986d50b505.png)
![image](https://user-images.githubusercontent.com/82800204/164226805-29467c0d-a2da-482f-b753-c5173b038c44.png)


Is there a way i can fix this?

**Comment by BoD** [comment]
I'm not 100% sure why 1.3.6 is selected, as usually Gradle selects the highest version when there's a conflict - but I think the `(c)` means "constraint" as if the version is explicitly requested by Spring.

You could try to force the version of the dependency to 1.5.2 by declaring it like this:

```kotlin
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core") {
        version {
            strictly("1.5.2")
        }
    }
```

but I'm not sure of the consequences for Spring and this is probably unsafe.

Would it be possible for you to use a more recent version of Spring? I can see [here](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.6.6/spring-boot-dependencies-2.6.6.pom) that the latest v2.6.6 depends on the same version of coroutines as Apollo Kotlin.

**Comment by adsiddiqui-equinix** [comment]
Hey @BoD, thanks for the reply. I will probably upgrade Spring.

**Comment by martinbonnin** [comment]
Closing this one as it seems updating Spring Boot made the trick. Let's follow up in https://github.com/apollographql/apollo-kotlin/issues/4064
