### ISSUE TITLE
java.lang.NoSuchFieldError: Companion on DefaultHttpEngine$execute$2$httpRequest$2$2

### ISSUE THREAD

**Issue by adsiddiqui-equinix** [apollographql/apollo-kotlin#4064]
**Question.**
This is related to #4048 .
I managed to fix that error by upgrading Spring Boot to 2.6.6. Now i have a different error on the HTTP request.
```
java.util.concurrent.CompletionException: java.lang.NoSuchFieldError: Companion
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:281)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at org.springframework.cloud.sleuth.instrument.async.TraceRunnable.run(TraceRunnable.java:64)
	at com.equinix.crh.asset.common.config.ThreadConfig$ContextDecorator.lambda$decorate$0(ThreadConfig.java:84)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoSuchFieldError: Companion
	at com.apollographql.apollo3.network.http.DefaultHttpEngine$execute$2$httpRequest$2$2.contentType(OkHttpEngine.kt:56)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:53)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at com.apollographql.apollo3.network.http.DefaultHttpEngine.execute(OkHttpEngine.kt:75)
Caused by: java.lang.NoSuchFieldError: Companion
```

This looked like an error with the `okhttp` library that is being used. I generated the gradle dependencies for my app and noticed that the version being served is old:

![image](https://user-images.githubusercontent.com/82800204/165464971-526fdde2-b5bf-479f-b7e4-13037079c409.png)

I don't know why the version is being changed from 4.9.3 to 3.14.9, especially when apollographql is the first package to import this dependency. I managed to fix it and get things running by adding this to my `build.gradle`:
```
implementation("com.squareup.okhttp3:okhttp") {
        version {
            strictly("4.9.3")
        }
    }
```

![image](https://user-images.githubusercontent.com/82800204/165466205-62424a00-f55e-4a82-babb-d8af3de7bcca.png)

Is there a different way to solve this issue?

**Comment by martinbonnin** [comment]
Hi 👋 

> I don't know why the version is being changed from 4.9.3 to 3.14.9, especially when apollographql is the first package to import this dependency.

For what it worth, the order of the dependencies declaration shouldn't matter

> Is there a different way to solve this issue?

Hard to tell from the screenshots. Looks like a plugin or another dependency forces `3.14.9`. Can you share the complete `:app:dependencies` output?

**Comment by martinbonnin** [comment]
Hi @adsiddiqui-equinix anything else we can help with here?

**Comment by martinbonnin** [comment]
@adsiddiqui-equinix I'm going to go ahead and assume you found a solution. I'm closing this issue for now. Feel free to reply to this thread and we can keep investigating.
