### ISSUE TITLE
Unable to merge records from the database on queries exceeding SQL variables limit

### ISSUE THREAD

**Issue by alvr** [apollographql/apollo-kotlin#4255]
### Summary
Long queries that are saved into the database are not possible because it exceeds the SQL variables limit.

### Version
Happening from v3.3.1. Tested in v3.3.0 and v3.2.2 and the same query works fine.

### Logs
```
I/System.out: Apollo: unhandled exception
W/System.err: java.lang.Exception: Unable to merge records from the database
W/System.err:     at com.apollographql.apollo3.cache.normalized.sql.SqlNormalizedCache.merge(SqlNormalizedCache.kt:83)
W/System.err:     at com.apollographql.apollo3.cache.normalized.api.internal.OptimisticCache.merge(OptimisticCache.kt:38)
W/System.err:     at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore$writeOperationWithRecords$2.invoke(DefaultApolloStore.kt:204)
W/System.err:     at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore$writeOperationWithRecords$2.invoke(DefaultApolloStore.kt:197)
W/System.err:     at com.apollographql.apollo3.cache.normalized.internal.Guard.writeAccess(Guard.kt:19)
W/System.err:     at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore.writeOperationWithRecords(DefaultApolloStore.kt:197)
W/System.err:     at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore.writeOperation(DefaultApolloStore.kt:148)
W/System.err:     at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$maybeWriteToCache$2.invokeSuspend(ApolloCacheInterceptor.kt:85)
W/System.err:     at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$maybeWriteToCache$2.invoke(Unknown Source:12)
W/System.err:     at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$maybeWriteToCache$2.invoke(Unknown Source:7)
W/System.err:     at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$maybeAsync$2.invokeSuspend(ApolloCacheInterceptor.kt:53)
W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
W/System.err:     at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
W/System.err:     at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
W/System.err: Caused by: android.database.sqlite.SQLiteException: too many SQL variables (code 1 SQLITE_ERROR): , while compiling: SELECT key, record FROM records WHERE key IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
W/System.err:     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
W/System.err:     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1045)
W/System.err:     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:652)
W/System.err:     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
W/System.err:     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
W/System.err:     at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
W/System.err:     at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
W/System.err:     at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1545)
W/System.err:     at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1520)
W/System.err:     at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.query(FrameworkSQLiteDatabase.java:161)
W/System.err:     at com.squareup.sqldelight.android.AndroidQuery.executeQuery(AndroidSqliteDriver.kt:253)
W/System.err:     at com.squareup.sqldelight.android.AndroidQuery.executeQuery(AndroidSqliteDriver.kt:228)
W/System.err:     at com.squareup.sqldelight.android.AndroidSqliteDriver$executeQuery$2.invoke(AndroidSqliteDriver.kt:149)
W/System.err:     at com.squareup.sqldelight.android.AndroidSqliteDriver$executeQuery$2.invoke(AndroidSqliteDriver.kt:149)
W/System.err:     at com.squareup.sqldelight.android.AndroidSqliteDriver.execute(AndroidSqliteDriver.kt:127)
W/System.err:     at com.squareup.sqldelight.android.AndroidSqliteDriver.executeQuery(AndroidSqliteDriver.kt:149)
W/System.err:     at com.apollographql.apollo3.cache.internal.json.apollonormalizedcachesqlite.JsonQueriesImpl$RecordsForKeysQuery.execute(JsonDatabaseImpl.kt:197)
W/System.err:     at com.squareup.sqldelight.Query.executeAsList(Query.kt:134)
W/System.err:     at com.apollographql.apollo3.cache.normalized.sql.internal.JsonRecordDatabase.select(JsonRecordDatabase.kt:18)
W/System.err:     at com.apollographql.apollo3.cache.normalized.sql.SqlNormalizedCache$internalUpdateRecords$1.invoke(SqlNormalizedCache.kt:139)
W/System.err:     at com.apollographql.apollo3.cache.normalized.sql.SqlNormalizedCache$internalUpdateRecords$1.invoke(SqlNormalizedCache.kt:138)
W/System.err:     at com.apollographql.apollo3.cache.normalized.sql.internal.JsonRecordDatabase$transaction$1.invoke(JsonRecordDatabase.kt:26)
W/System.err:     at com.apollographql.apollo3.cache.normalized.sql.internal.JsonRecordDatabase$transaction$1.invoke(JsonRecordDatabase.kt:25)
W/System.err:     at com.squareup.sqldelight.TransacterImpl.transactionWithWrapper(Transacter.kt:235)
W/System.err:     at com.squareup.sqldelight.TransacterImpl.transactionWithResult(Transacter.kt:221)
W/System.err:     at com.squareup.sqldelight.Transacter$DefaultImpls.transactionWithResult$default(Transacter.kt:61)
W/System.err:     at com.apollographql.apollo3.cache.normalized.sql.internal.JsonRecordDatabase.transaction(JsonRecordDatabase.kt:25)
W/System.err:     at com.apollographql.apollo3.cache.normalized.sql.internal.RecordDatabase$DefaultImpls.transaction$default(RecordDatabase.kt:32)
W/System.err:     at com.apollographql.apollo3.cache.normalized.sql.SqlNormalizedCache.internalUpdateRecords(SqlNormalizedCache.kt:138)
W/System.err:     at com.apollographql.apollo3.cache.normalized.sql.SqlNormalizedCache.merge(SqlNormalizedCache.kt:80)
W/System.err: 	... 18 more
```

### Steps to reproduce the behavior
- [Here](https://github.com/alvr/katana/blob/develop/data/remote/base/src/main/kotlin/dev/alvr/katana/data/remote/base/di/ApolloModule.kt) is my Apollo client builder.
- [Here](https://github.com/alvr/katana/tree/develop/data/remote/lists/src/main/graphql) the query I'm executing.

Because an account is needed, here is the response is quite long, [here](https://gist.github.com/alvr/7d5176a6ef954ca460ce28740289e7a3#file-anime_res-json) is a gist with it.

This only happens with long responses. [This one](https://gist.github.com/alvr/7d5176a6ef954ca460ce28740289e7a3#file-manga_res-json) is being saved correctly.

**Comment by martinbonnin** [comment]
Thanks a lot for catching this. This is a regression from https://github.com/apollographql/apollo-kotlin/pull/4104 that lost the chunking of the parameters. We'll do a new version early next week with a fix

**Comment by alvr** [comment]
That's great! Thank you very much.
