### ISSUE TITLE
HTTP headers are not transmitted in GraphQL subscription connection

### ISSUE THREAD

**Issue by andrey-nakin** [apollographql/apollo-kotlin#4266]
Hello!

I'm attempting to create a GraphQL subscription. My backend requires `Authorization` header to be passed within the request. Here's my code:

```java
final var apolloClient = new ApolloClient.Builder()
        .serverUrl("http://mydomain/graphql")
        .webSocketServerUrl("ws://mydomain/subscriptions")
        .wsProtocol(new GraphQLWsProtocol.Factory())
        .addHttpHeader("Authorization", "Bearer a-very-secret-token")
        .build();

final var call = apolloClient.subscription(new MySubscription());
final var flowable = (Flowable<ApolloResponse<MySubscription.Data>>) Rx3Apollo.flowable(call);
flowable.subscribe(response -> {
   // handle data
}, throwable -> {
  // handle error
});
```

Unfortunately I don't see `Authorization` header in the request. Moreover, if I add any other custom HTTP header, it is not passed to the subscription connection.

How can I fix this?

**Comment by BoD** [comment]
Hi!

The headers added with `ApolloClient.Builder.addHttpHeader` are only used with queries and mutations. To set specific headers for the WebSocket used with subscriptions, you can set a `subscriptionNetworkTransport` and pass it the headers, like so:

```java

        final var apolloClient = new ApolloClient.Builder()
                .serverUrl("http://mydomain/graphql")
                .subscriptionNetworkTransport(new  WebSocketNetworkTransport.Builder()
                        .protocol(new GraphQLWsProtocol.Factory())
                        .serverUrl("ws://mydomain/subscriptions")
                        .addHeader("Authorization", "Bearer a-very-secret-token")
                        .build())
                .build();

```

Please let us know if that works for you!

**Comment by andrey-nakin** [comment]
Hi @BoD!

Thank you for the quick response. The `subscriptionNetworkTransport` helps and the authorization header is now sent to the server.

But there's another problem, when I run a subscription request, the following error appears:

```
com.apollographql.apollo3.exception.ApolloNetworkException: Network error while executing FlightSubscription
	at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$$inlined$map$1$2.emit(Emitters.kt:245) ~[apollo-runtime-jvm-3.3.2.jar!/:3.3.2]
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15) ~[kotlinx-coroutines-core-jvm-1.6.3.jar!/:na]
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15) ~[kotlinx-coroutines-core-jvm-1.6.3.jar!/:na]
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:87) ~[kotlinx-coroutines-core-jvm-1.6.3.jar!/:na]
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:66) ~[kotlinx-coroutines-core-jvm-1.6.3.jar!/:na]
	at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$3.invokeSuspend(WebSocketNetworkTransport.kt:268) ~[apollo-runtime-jvm-3.3.2.jar!/:3.3.2]
	at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$3.invoke(WebSocketNetworkTransport.kt) ~[apollo-runtime-jvm-3.3.2.jar!/:3.3.2]
	at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$3.invoke(WebSocketNetworkTransport.kt) ~[apollo-runtime-jvm-3.3.2.jar!/:3.3.2]
	at com.apollographql.apollo3.internal.FlowsKt$transformWhile$1$invokeSuspend$$inlined$collectWhile$1.emit(flows.kt:53) ~[apollo-runtime-jvm-3.3.2.jar!/:3.3.2]
	at com.apollographql.apollo3.internal.FlowsKt$transformWhile$1$invokeSuspend$$inlined$collectWhile$2.emit(flows.kt:38) ~[apollo-runtime-jvm-3.3.2.jar!/:3.3.2]
	at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$$inlined$filter$1$2.emit(Emitters.kt:224) ~[apollo-runtime-jvm-3.3.2.jar!/:3.3.2]
	at kotlinx.coroutines.flow.SubscribedFlowCollector.emit(Share.kt) ~[kotlinx-coroutines-core-jvm-1.6.3.jar!/:na]
	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:383) ~[kotlinx-coroutines-core-jvm-1.6.3.jar!/:na]
	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(SharedFlow.kt) ~[kotlinx-coroutines-core-jvm-1.6.3.jar!/:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.6.21.jar!/:1.6.21-release-334(1.6.21)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.6.3.jar!/:na]
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) ~[kotlinx-coroutines-core-jvm-1.6.3.jar!/:na]
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) ~[kotlinx-coroutines-core-jvm-1.6.3.jar!/:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[kotlinx-coroutines-core-jvm-1.6.3.jar!/:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749) ~[kotlinx-coroutines-core-jvm-1.6.3.jar!/:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[kotlinx-coroutines-core-jvm-1.6.3.jar!/:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[kotlinx-coroutines-core-jvm-1.6.3.jar!/:na]
Caused by: com.apollographql.apollo3.exception.ApolloWebSocketClosedException: WebSocket Closed code='1011' reason='Internal Server Error'
	at com.apollographql.apollo3.network.ws.DefaultWebSocketEngine$open$webSocket$1.onClosing(OkHttpWebSocketEngine.kt:64) ~[apollo-runtime-jvm-3.3.2.jar!/:3.3.2]
	at okhttp3.internal.ws.RealWebSocket.onReadClose(RealWebSocket.kt:378) ~[okhttp-4.9.3.jar!/:na]
	at okhttp3.internal.ws.WebSocketReader.readControlFrame(WebSocketReader.kt:220) ~[okhttp-4.9.3.jar!/:na]
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:104) ~[okhttp-4.9.3.jar!/:na]
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293) ~[okhttp-4.9.3.jar!/:na]
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195) ~[okhttp-4.9.3.jar!/:na]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) ~[okhttp-4.9.3.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

I found a simple workaround: not to use `GraphQLWsProtocol.Factory`. So my final code looks like this:

```java
var apolloClient = new ApolloClient.Builder().serverUrl("http://mydomain/graphql")
        .addHttpHeader("Authorization", "Bearer a-very-secret-token")
        .subscriptionNetworkTransport(new WebSocketNetworkTransport.Builder()
                .serverUrl("ws://mydomain/subscriptions")
                .addHeader("Authorization", "Bearer a-very-secret-token")
                .build())
        .build();

var call = apolloClient.subscription(new MySubscription());
var flowable = (Flowable<ApolloResponse<MySubscription.Data>>) Rx3Apollo.flowable(call);
flowable.subscribe(response -> {
    // handle data
}, throwable -> {
    // handle error
});
```

**Comment by BoD** [comment]
Oh your backend must be using the [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md) protocol, which is the default for Apollo-Kotlin when not specifying one.

Glad it now works! 😊
