### ISSUE TITLE
ApolloNetworkException - Channel was closed - with Kotlin Multiplatform JS

### ISSUE THREAD

**Issue by schoeda** [apollographql/apollo-kotlin#4339]
### Summary
I use KMP and compile a web client. Every query between our backend runs fine. Only the subscription get an error and it is not possible to create a connection to our backend. Every time i try i get directly a ApolloNetworkException in my console logs in Google Chrome. In another web client we use the JS library (https://apollo-angular.com/) and everything runs fine. The difference that i see is, the request header "Sec-WebSocket-Protocol: graphql-transport-ws" is set with the js library. That header is missing in the KMP requests. 

### Version
"com.apollographql.apollo3:apollo-runtime:3.5.0"

### Logs
ApolloNetworkException {message: 'Network error while executing ChangedFacilityPickJobs', cause: ClosedReceiveChannelException, name: 'ApolloNetworkException', platformCause_1: ClosedReceiveChannelException, stack: 'ApolloNetworkException: Network error while execut…in/apollo-kotlin-apollo-runtime-js-ir.js:2600:16)'}cause: ClosedReceiveChannelException {message: 'Channel was closed', cause: undefined, name: 'ClosedReceiveChannelException', stack: 'ClosedReceiveChannelException: Channel was closed\n…in/apollo-kotlin-apollo-runtime-js-ir.js:7005:30)'}message: "Network error while executing ChangedFacilityPickJobs"name: "ApolloNetworkException"platformCause_1: ClosedReceiveChannelExceptioncause: undefinedmessage: "Channel was closed"name: "ClosedReceiveChannelException"stack: "ClosedReceiveChannelException: Channel was closed\n    at Closed.get_receiveException_nqbiq3_k$ (webpack-internal:///./kotlin/kotlinx.coroutines-kotlinx-coroutines-core-js-ir.js:6894:37)\n    at ReceiveElement.resumeReceiveClosed_ep2qlw_k$ (webpack-internal:///./kotlin/kotlinx.coroutines-kotlinx-coroutines-core-js-ir.js:5613:47)\n    at helpClose (webpack-internal:///./kotlin/kotlinx.coroutines-kotlinx-coroutines-core-js-ir.js:6243:35)\n    at AbstractSendChannel.close_9zy44b_k$ (webpack-internal:///./kotlin/kotlinx.coroutines-kotlinx-coroutines-core-js-ir.js:6799:5)\n    at ChannelWrapper.close_9zy44b_k$ (webpack-internal:///./kotlin/apollo-kotlin-apollo-runtime-js-ir.js:2041:37)\n    at ChannelWrapper.close$default [as close$default_jao18g_k$] (webpack-internal:///./kotlin/kotlinx.coroutines-kotlinx-coroutines-core-js-ir.js:293:36)\n    at WebSocket.eval (webpack-internal:///./kotlin/apollo-kotlin-apollo-runtime-js-ir.js:7005:30)"[[Prototype]]: NoSuchElementExceptionconstructor: ƒ ClosedReceiveChannelException(message)[[Prototype]]: RuntimeExceptionstack: "ApolloNetworkException: Network error while executing ChangedFacilityPickJobs\n    at WebSocketNetworkTransport$execute$o$collect$slambda_1.doResume_5yljmg_k$ (webpack-internal:///./kotlin/apollo-kotlin-apollo-runtime-js-ir.js:5077:25)\n    at WebSocketNetworkTransport$execute$o$collect$slambda_1.invoke_kvy33q_k$ (webpack-internal:///./kotlin/apollo-kotlin-apollo-runtime-js-ir.js:5039:16)\n    at sam$kotlinx_coroutines_flow_FlowCollector$0_3.l [as function_1] (webpack-internal:///./kotlin/apollo-kotlin-apollo-runtime-js-ir.js:5128:16)\n    at sam$kotlinx_coroutines_flow_FlowCollector$0_3.emit_1fbrsb_k$ (webpack-internal:///./kotlin/apollo-kotlin-apollo-runtime-js-ir.js:5402:17)\n    at SafeCollector.emit_1fbrsb_k$ (webpack-internal:///./kotlin/kotlinx.coroutines-kotlinx-coroutines-core-js-ir.js:17567:29)\n    at WebSocketNetworkTransport$execute$slambda_1.doResume_5yljmg_k$ (webpack-internal:///./kotlin/apollo-kotlin-apollo-runtime-js-ir.js:5797:61)\n    at WebSocketNetworkTransport$execute$slambda_1.invoke_jwaue4_k$ (webpack-internal:///./kotlin/apollo-kotlin-apollo-runtime-js-ir.js:5772:16)\n    at _no_name_provided__qut3iv.l [as $transform_1] (webpack-internal:///./kotlin/apollo-kotlin-apollo-runtime-js-ir.js:5855:16)\n    at $emitCOROUTINE$1.doResume_5yljmg_k$ (webpack-internal:///./kotlin/apollo-kotlin-apollo-runtime-js-ir.js:2553:51)\n    at _no_name_provided__qut3iv.emit_1fbrsb_k$ (webpack-internal:///./kotlin/apollo-kotlin-apollo-runtime-js-ir.js:2600:16)"[[Prototype]]: ApolloExceptionconstructor: ƒ ApolloNetworkException(message, platformCause)$metadata$: {kind: 'class', simpleName: 'ApolloNetworkException', interfaceId: undefined, interfaces: Array(0), associatedObjectKey: undefined, …}length: 2name: "ApolloNetworkException"prototype: ApolloException {constructor: ƒ, get_platformCause_78v825_k$: ƒ}arguments: (...)caller: (...)[[FunctionLocation]]: apollo-kotlin-apollo-api-js-ir.js:8700[[Prototype]]: ƒ ()[[Scopes]]: Scopes[4]get_platformCause_78v825_k$: ƒ ()length: 0name: ""prototype: {constructor: ƒ}arguments: (...)caller: (...)[[FunctionLocation]]: apollo-kotlin-apollo-api-js-ir.js:8705[[Prototype]]: ƒ ()[[Scopes]]: Scopes[4][[Prototype]]: RuntimeException

### Steps to reproduce the behavior
Every subscription try with KMP.

**Comment by schoeda** [comment]
Hey @BoD!
Thanks for your answer! I think the problem ist my own mistake. I had a problem with the "x-apollo-operation-name" header and override the header because Access-Control-Allow-Headers don't liked it. Maybe that removes the "sec-websocket-protocol". Do you know if it is possible to remove only the "x-apollo-operation-name" header?

**Comment by schoeda** [comment]
I think this is my solution for the header handling: https://www.apollographql.com/docs/apollo-server/security/cors#preventing-cross-site-request-forgery-csrf

Sorry for the ticket. Have a great weekend! :)
