### ISSUE TITLE
Have a way to specify a global custom `FakeResolver` for data builders

### ISSUE THREAD

**Issue by eduardb** [apollographql/apollo-kotlin#4435]
### Use case
Using data builders when having custom scalars requires a custom `FakeResolver` that implements `resolveLeaf` for those custom scalars if you want those scalars to be generated instead of having to manually specify them for each operation. The problem is that you need to pass this **every single time** you want to use a data builder for an operation, which can become a bit tiresome, and error-prone (e.g. if you forget to actually pass it down, and your tests start failing 😄).

### Describe the solution you'd like
No strong opinions on how this should look like, I imagine that it could be a Gradle config like `customFakeResolver.set("fully.qualified.class.name")`, or some other API to specify a class that implements `FakeResolver` that would be used instead of `DefaultFakeResolver` by each generated data builder.

PS: I would keep the `DefaultFakeResolver` class though, as it's very useful to delegate to it for non-custom scalar leafs.

**Comment by adapap** [comment]
In my use case, even just being able to parse the custom scalars as specified in `customScalarsMapping` in `build.gradle` by default would be great!

**Comment by martinbonnin** [comment]
@adapap can you elaborate a bit more? This should work already:

```kotlin
// build.gradle.kts
apollo {
  service("service") {
    packageName.set("com.example")
    generateDataBuilders.set(true)
    mapScalar("Long", "com.example.MyLong")
  }
}
```

```kotlin
val data = GetCustomScalarQuery.Data {
  long = MyLong(42)
}
```

Or do you need something else?

**Comment by adapap** [comment]
@martinbonnin In my case, the default fake resolver does not seem to be respecting the scalars defined in `build.gradle`. For example, if I define my apollo config as such:
```
apollo {
  service("example") {
    packageName.set("com.example.app")
    generateDataBuilders.set(true)
    mapScalar("int64", "kotlin.Long")

    schemaFile.set(file("../schema-copied.json"))
    srcDir(file("src/main/graphql/"))
  }
}
```

When I try to use `DefaultFakeResolver` with a query that uses an `int64` type, I get the following error:
```
Don't know how to instantiate leaf int64
java.lang.IllegalStateException: Don't know how to instantiate leaf int64
	at com.apollographql.apollo3.api.DefaultFakeResolver.resolveLeaf(fakeResolver.kt:269)
	at com.apollographql.apollo3.api.FakeResolverKt.buildFieldOfNonNullType(fakeResolver.kt:212)
	at com.apollographql.apollo3.api.FakeResolverKt.buildFieldOfType(fakeResolver.kt:156)
	at com.apollographql.apollo3.api.FakeResolverKt.buildFieldOfNonNullType(fakeResolver.kt:209)
	at com.apollographql.apollo3.api.FakeResolverKt.buildFieldOfType(fakeResolver.kt:156)
	at com.apollographql.apollo3.api.FakeResolverKt.buildFieldOfType(fakeResolver.kt:151)
	at com.apollographql.apollo3.api.FakeResolverKt.buildFieldOfNonNullType(fakeResolver.kt:209)
	at com.apollographql.apollo3.api.FakeResolverKt.buildFieldOfType(fakeResolver.kt:156)
	at com.apollographql.apollo3.api.FakeResolverKt.buildFieldOfType(fakeResolver.kt:151)
	at com.apollographql.apollo3.api.FakeResolverKt.buildFieldOfNonNullType(fakeResolver.kt:197)
	at com.apollographql.apollo3.api.FakeResolverKt.buildFieldOfType(fakeResolver.kt:156)
	at com.apollographql.apollo3.api.FakeResolverKt.buildFakeObject(fakeResolver.kt:112)
	at com.apollographql.apollo3.api.FakeResolverKt.buildData(fakeResolver.kt:327)
```

**Comment by martinbonnin** [comment]
@adapap thanks for sending this! As a side note for next time, can you open different issues? It helps keeping the discussion focused. 
But now that you're here, let's dive in!

> When I try to use DefaultFakeResolver with a query that uses an int64 type, I get the following error

The `DefaultFakeResolver` doesn't know about the int64 custom scalar adapter as it's registered at runtime. 

You can register the int64 custom scalar adapter it at build time to have this working:

```
apollo {
  service("example") {
    // This will use the builtin LongAdapter (you can remove the call to `addCustomScalarAdapter()`)
    mapScalarToKotlinLong("int64")
    // ...
  }
}
```

> I also get an issue using data builders where there is a conflict trying to construct the data

That's unexpected. Can you share your schema ?

**Comment by adapap** [comment]
> You can register the int64 custom scalar adapter it at build time to have this working:
```
apollo {
  service("example") {
    // This will use the builtin LongAdapter (you can remove the call to `addCustomScalarAdapter()`)
    mapScalarToKotlinLong("int64")
    // ...
  }
}
```
@martinbonnin This solution did not solve the issue for me, and in v3.8.1 I am not able to use data builders for tests even with a custom resolver. Without passing in a custom resolver, I get the `Don't know how to instantiate leaf int64` error even if I manually specify all of the fields in the builder.

I also tried writing my own resolver as the original issue describes, and I run into an issue now where if I set a value to `null`, the fake resolver ignores that and uses a default value. My custom resolver is a replica of the default fake resolver that apollo provides, but handles the custom scalar types in the `resolveLeaf` method.

I understand that a schema is helpful, and although I can't provide the full schema as it's 500k+ lines of auto-generated JSON, I can try to provide a subset to give an idea of our schema's format that might help with the investigation:

```
{
  "__schema": {
    "mutationType": {
      "name": "Mutation"
    },
    "queryType": {
      "name": "Query"
    },
    "types": [
      {
        "description": "",
        "enumValues": [],
        "fields": [
          {
            "args": [],
            "deprecationReason": null,
            "description": "",
            "isDeprecated": false,
            "name": "admin",
            "type": {
              "kind": "OBJECT",
              "name": "User",
              "ofType": null
            }
          },
          {
            "args": [],
            "deprecationReason": null,
            "description": "",
            "isDeprecated": false,
            "name": "userEmail",
            "type": {
              "kind": "SCALAR",
              "name": "string",
              "ofType": null
            }
          },
          {
            "args": [],
            "deprecationReason": null,
            "description": "",
            "isDeprecated": false,
            "name": "userId",
            "type": {
              "kind": "NON_NULL",
              "name": null,
              "ofType": {
                "kind": "SCALAR",
                "name": "int64",
                "ofType": null
              }
            }
          },
          {
            "args": [],
            "deprecationReason": null,
            "description": "",
            "isDeprecated": false,
            "name": "deviceAppVersion",
            "type": {
              "kind": "SCALAR",
              "name": "string",
              "ofType": null
            }
          },
          {
            "args": [],
            "deprecationReason": null,
            "description": "",
            "isDeprecated": false,
            "name": "device",
            "type": {
              "kind": "OBJECT",
              "name": "Device",
              "ofType": null
            }
          }
        ]
      }
    ]
  }
}
```

**Comment by ar-g** [comment]
This is very much needed! cc @martinbonnin

**Comment by jamesonwilliams** [comment]
I'm encountering this one as well - 

In my schema module, I have:
```groovy
apollo {
  service("ServiceName") {
    ...
    mapScalarToKotlinLong("ScalarName")
  }
}
```

I experimented with adding 
```kotlin
ApolloClient.Builder()
  .addCustomScalarAdapter(ScalarName.type, LongAdapter)
```

But that seemed to make things worse.

I can get the tests to pass if provide this resolver to my data builder's constructor:
```kotlin
class Resolver : DefaultFakeResolver(__Schema.all) {
  override fun resolveLeaf(context: FakeResolverContext): Any {
    return when (context.mergedField.type.rawType().name) {
      "ScalarName" -> 100L
      else -> super.resolveLeaf(context)
    }
  }
}
```

But, it would be sweet if `mapScalarToKotlinLong` could do it alone!

For what it's worth, the generated `__Schema.all` list does _not_ include my `ScalarName.type`. (Not sure if it should!)

**Comment by martinbonnin** [comment]
@jamesonwilliams indeed scalars are a bit awkward because they are a runtime thing only. The codegen doesn't know how to instanciate a given custom scalar. For Long, `100L` is a valid initializer but for a date, maybe we want `Instant.now()` or `DateTime.parse(isoString)`, the sky is the limit in how complex that expression can be...
