### ISSUE TITLE
`SqlNormalizedCache.dump()` fails due to not implemented method

### ISSUE THREAD

**Issue by eduardb** [apollographql/apollo-kotlin#4436]
### Summary
`JsonRecordDatabase.selectAll()`, who `SqlNormalizedCache.dump()` relies on, is not implemented, not making possible dumping the contents of ApolloStore when using a SQLite cache. 

### Version
Tested on 3.6.0 and 3.6.1

<details>
  <summary>Gradle lockfile snippet (click to expand)</summary>
  
  ```
com.apollographql.apollo3:apollo-annotations-jvm:3.6.0=fakeDebugAndroidTestCompileClasspath,fakeDebugAndroidTestRuntimeClasspath,fakeDebugCompileClasspath,fakeDebugRuntimeClasspath,fakeDebugUnitTestCompileClasspath,fakeDebugUnitTestRuntimeClasspath,fakeReleaseCompileClasspath,fakeReleaseRuntimeClasspath,fakeReleaseUnitTestCompileClasspath,fakeReleaseUnitTestRuntimeClasspath,localDebugAndroidTestCompileClasspath,localDebugAndroidTestRuntimeClasspath,localDebugCompileClasspath,localDebugRuntimeClasspath,localDebugUnitTestCompileClasspath,localDebugUnitTestRuntimeClasspath,localReleaseCompileClasspath,localReleaseRuntimeClasspath,localReleaseUnitTestCompileClasspath,localReleaseUnitTestRuntimeClasspath,productionDebugAndroidTestCompileClasspath,productionDebugAndroidTestRuntimeClasspath,productionDebugCompileClasspath,productionDebugRuntimeClasspath,productionDebugUnitTestCompileClasspath,productionDebugUnitTestRuntimeClasspath,productionReleaseCompileClasspath,productionReleaseRuntimeClasspath,productionReleaseUnitTestCompileClasspath,productionReleaseUnitTestRuntimeClasspath
com.apollographql.apollo3:apollo-annotations:3.6.0=fakeDebugAndroidTestCompileClasspath,fakeDebugAndroidTestRuntimeClasspath,fakeDebugCompileClasspath,fakeDebugRuntimeClasspath,fakeDebugUnitTestCompileClasspath,fakeDebugUnitTestRuntimeClasspath,fakeReleaseCompileClasspath,fakeReleaseRuntimeClasspath,fakeReleaseUnitTestCompileClasspath,fakeReleaseUnitTestRuntimeClasspath,localDebugAndroidTestCompileClasspath,localDebugAndroidTestRuntimeClasspath,localDebugCompileClasspath,localDebugRuntimeClasspath,localDebugUnitTestCompileClasspath,localDebugUnitTestRuntimeClasspath,localReleaseCompileClasspath,localReleaseRuntimeClasspath,localReleaseUnitTestCompileClasspath,localReleaseUnitTestRuntimeClasspath,productionDebugAndroidTestCompileClasspath,productionDebugAndroidTestRuntimeClasspath,productionDebugCompileClasspath,productionDebugRuntimeClasspath,productionDebugUnitTestCompileClasspath,productionDebugUnitTestRuntimeClasspath,productionReleaseCompileClasspath,productionReleaseRuntimeClasspath,productionReleaseUnitTestCompileClasspath,productionReleaseUnitTestRuntimeClasspath
com.apollographql.apollo3:apollo-api-jvm:3.6.0=fakeDebugAndroidTestCompileClasspath,fakeDebugAndroidTestRuntimeClasspath,fakeDebugCompileClasspath,fakeDebugRuntimeClasspath,fakeDebugUnitTestCompileClasspath,fakeDebugUnitTestRuntimeClasspath,fakeReleaseCompileClasspath,fakeReleaseRuntimeClasspath,fakeReleaseUnitTestCompileClasspath,fakeReleaseUnitTestRuntimeClasspath,localDebugAndroidTestCompileClasspath,localDebugAndroidTestRuntimeClasspath,localDebugCompileClasspath,localDebugRuntimeClasspath,localDebugUnitTestCompileClasspath,localDebugUnitTestRuntimeClasspath,localReleaseCompileClasspath,localReleaseRuntimeClasspath,localReleaseUnitTestCompileClasspath,localReleaseUnitTestRuntimeClasspath,productionDebugAndroidTestCompileClasspath,productionDebugAndroidTestRuntimeClasspath,productionDebugCompileClasspath,productionDebugRuntimeClasspath,productionDebugUnitTestCompileClasspath,productionDebugUnitTestRuntimeClasspath,productionReleaseCompileClasspath,productionReleaseRuntimeClasspath,productionReleaseUnitTestCompileClasspath,productionReleaseUnitTestRuntimeClasspath
com.apollographql.apollo3:apollo-api:3.6.0=fakeDebugAndroidTestCompileClasspath,fakeDebugAndroidTestRuntimeClasspath,fakeDebugCompileClasspath,fakeDebugRuntimeClasspath,fakeDebugUnitTestCompileClasspath,fakeDebugUnitTestRuntimeClasspath,fakeReleaseCompileClasspath,fakeReleaseRuntimeClasspath,fakeReleaseUnitTestCompileClasspath,fakeReleaseUnitTestRuntimeClasspath,localDebugAndroidTestCompileClasspath,localDebugAndroidTestRuntimeClasspath,localDebugCompileClasspath,localDebugRuntimeClasspath,localDebugUnitTestCompileClasspath,localDebugUnitTestRuntimeClasspath,localReleaseCompileClasspath,localReleaseRuntimeClasspath,localReleaseUnitTestCompileClasspath,localReleaseUnitTestRuntimeClasspath,productionDebugAndroidTestCompileClasspath,productionDebugAndroidTestRuntimeClasspath,productionDebugCompileClasspath,productionDebugRuntimeClasspath,productionDebugUnitTestCompileClasspath,productionDebugUnitTestRuntimeClasspath,productionReleaseCompileClasspath,productionReleaseRuntimeClasspath,productionReleaseUnitTestCompileClasspath,productionReleaseUnitTestRuntimeClasspath
com.apollographql.apollo3:apollo-mpp-utils-jvm:3.6.0=fakeDebugAndroidTestCompileClasspath,fakeDebugAndroidTestRuntimeClasspath,fakeDebugCompileClasspath,fakeDebugRuntimeClasspath,fakeDebugUnitTestCompileClasspath,fakeDebugUnitTestRuntimeClasspath,fakeReleaseCompileClasspath,fakeReleaseRuntimeClasspath,fakeReleaseUnitTestCompileClasspath,fakeReleaseUnitTestRuntimeClasspath,localDebugAndroidTestCompileClasspath,localDebugAndroidTestRuntimeClasspath,localDebugCompileClasspath,localDebugRuntimeClasspath,localDebugUnitTestCompileClasspath,localDebugUnitTestRuntimeClasspath,localReleaseCompileClasspath,localReleaseRuntimeClasspath,localReleaseUnitTestCompileClasspath,localReleaseUnitTestRuntimeClasspath,productionDebugAndroidTestCompileClasspath,productionDebugAndroidTestRuntimeClasspath,productionDebugCompileClasspath,productionDebugRuntimeClasspath,productionDebugUnitTestCompileClasspath,productionDebugUnitTestRuntimeClasspath,productionReleaseCompileClasspath,productionReleaseRuntimeClasspath,productionReleaseUnitTestCompileClasspath,productionReleaseUnitTestRuntimeClasspath
com.apollographql.apollo3:apollo-mpp-utils:3.6.0=fakeDebugAndroidTestCompileClasspath,fakeDebugAndroidTestRuntimeClasspath,fakeDebugCompileClasspath,fakeDebugRuntimeClasspath,fakeDebugUnitTestCompileClasspath,fakeDebugUnitTestRuntimeClasspath,fakeReleaseCompileClasspath,fakeReleaseRuntimeClasspath,fakeReleaseUnitTestCompileClasspath,fakeReleaseUnitTestRuntimeClasspath,localDebugAndroidTestCompileClasspath,localDebugAndroidTestRuntimeClasspath,localDebugCompileClasspath,localDebugRuntimeClasspath,localDebugUnitTestCompileClasspath,localDebugUnitTestRuntimeClasspath,localReleaseCompileClasspath,localReleaseRuntimeClasspath,localReleaseUnitTestCompileClasspath,localReleaseUnitTestRuntimeClasspath,productionDebugAndroidTestCompileClasspath,productionDebugAndroidTestRuntimeClasspath,productionDebugCompileClasspath,productionDebugRuntimeClasspath,productionDebugUnitTestCompileClasspath,productionDebugUnitTestRuntimeClasspath,productionReleaseCompileClasspath,productionReleaseRuntimeClasspath,productionReleaseUnitTestCompileClasspath,productionReleaseUnitTestRuntimeClasspath
com.apollographql.apollo3:apollo-normalized-cache-api-jvm:3.6.0=fakeDebugAndroidTestCompileClasspath,fakeDebugAndroidTestRuntimeClasspath,fakeDebugCompileClasspath,fakeDebugRuntimeClasspath,fakeDebugUnitTestCompileClasspath,fakeDebugUnitTestRuntimeClasspath,fakeReleaseCompileClasspath,fakeReleaseRuntimeClasspath,fakeReleaseUnitTestCompileClasspath,fakeReleaseUnitTestRuntimeClasspath,localDebugAndroidTestCompileClasspath,localDebugAndroidTestRuntimeClasspath,localDebugCompileClasspath,localDebugRuntimeClasspath,localDebugUnitTestCompileClasspath,localDebugUnitTestRuntimeClasspath,localReleaseCompileClasspath,localReleaseRuntimeClasspath,localReleaseUnitTestCompileClasspath,localReleaseUnitTestRuntimeClasspath,productionDebugAndroidTestCompileClasspath,productionDebugAndroidTestRuntimeClasspath,productionDebugCompileClasspath,productionDebugRuntimeClasspath,productionDebugUnitTestCompileClasspath,productionDebugUnitTestRuntimeClasspath,productionReleaseCompileClasspath,productionReleaseRuntimeClasspath,productionReleaseUnitTestCompileClasspath,productionReleaseUnitTestRuntimeClasspath
com.apollographql.apollo3:apollo-normalized-cache-api:3.6.0=fakeDebugAndroidTestCompileClasspath,fakeDebugAndroidTestRuntimeClasspath,fakeDebugCompileClasspath,fakeDebugRuntimeClasspath,fakeDebugUnitTestCompileClasspath,fakeDebugUnitTestRuntimeClasspath,fakeReleaseCompileClasspath,fakeReleaseRuntimeClasspath,fakeReleaseUnitTestCompileClasspath,fakeReleaseUnitTestRuntimeClasspath,localDebugAndroidTestCompileClasspath,localDebugAndroidTestRuntimeClasspath,localDebugCompileClasspath,localDebugRuntimeClasspath,localDebugUnitTestCompileClasspath,localDebugUnitTestRuntimeClasspath,localReleaseCompileClasspath,localReleaseRuntimeClasspath,localReleaseUnitTestCompileClasspath,localReleaseUnitTestRuntimeClasspath,productionDebugAndroidTestCompileClasspath,productionDebugAndroidTestRuntimeClasspath,productionDebugCompileClasspath,productionDebugRuntimeClasspath,productionDebugUnitTestCompileClasspath,productionDebugUnitTestRuntimeClasspath,productionReleaseCompileClasspath,productionReleaseRuntimeClasspath,productionReleaseUnitTestCompileClasspath,productionReleaseUnitTestRuntimeClasspath
com.apollographql.apollo3:apollo-normalized-cache-jvm:3.6.0=fakeDebugAndroidTestCompileClasspath,fakeDebugAndroidTestRuntimeClasspath,fakeDebugCompileClasspath,fakeDebugRuntimeClasspath,fakeDebugUnitTestCompileClasspath,fakeDebugUnitTestRuntimeClasspath,fakeReleaseCompileClasspath,fakeReleaseRuntimeClasspath,fakeReleaseUnitTestCompileClasspath,fakeReleaseUnitTestRuntimeClasspath,localDebugAndroidTestCompileClasspath,localDebugAndroidTestRuntimeClasspath,localDebugCompileClasspath,localDebugRuntimeClasspath,localDebugUnitTestCompileClasspath,localDebugUnitTestRuntimeClasspath,localReleaseCompileClasspath,localReleaseRuntimeClasspath,localReleaseUnitTestCompileClasspath,localReleaseUnitTestRuntimeClasspath,productionDebugAndroidTestCompileClasspath,productionDebugAndroidTestRuntimeClasspath,productionDebugCompileClasspath,productionDebugRuntimeClasspath,productionDebugUnitTestCompileClasspath,productionDebugUnitTestRuntimeClasspath,productionReleaseCompileClasspath,productionReleaseRuntimeClasspath,productionReleaseUnitTestCompileClasspath,productionReleaseUnitTestRuntimeClasspath
com.apollographql.apollo3:apollo-normalized-cache-sqlite-android-debug:3.6.0=fakeDebugAndroidTestCompileClasspath,fakeDebugAndroidTestRuntimeClasspath,fakeDebugCompileClasspath,fakeDebugRuntimeClasspath,fakeDebugUnitTestCompileClasspath,fakeDebugUnitTestRuntimeClasspath,localDebugAndroidTestCompileClasspath,localDebugAndroidTestRuntimeClasspath,localDebugCompileClasspath,localDebugRuntimeClasspath,localDebugUnitTestCompileClasspath,localDebugUnitTestRuntimeClasspath,productionDebugAndroidTestCompileClasspath,productionDebugAndroidTestRuntimeClasspath,productionDebugCompileClasspath,productionDebugRuntimeClasspath,productionDebugUnitTestCompileClasspath,productionDebugUnitTestRuntimeClasspath
com.apollographql.apollo3:apollo-normalized-cache-sqlite-android:3.6.0=fakeReleaseCompileClasspath,fakeReleaseRuntimeClasspath,fakeReleaseUnitTestCompileClasspath,fakeReleaseUnitTestRuntimeClasspath,localReleaseCompileClasspath,localReleaseRuntimeClasspath,localReleaseUnitTestCompileClasspath,localReleaseUnitTestRuntimeClasspath,productionReleaseCompileClasspath,productionReleaseRuntimeClasspath,productionReleaseUnitTestCompileClasspath,productionReleaseUnitTestRuntimeClasspath
com.apollographql.apollo3:apollo-normalized-cache-sqlite:3.6.0=fakeDebugAndroidTestCompileClasspath,fakeDebugAndroidTestRuntimeClasspath,fakeDebugCompileClasspath,fakeDebugRuntimeClasspath,fakeDebugUnitTestCompileClasspath,fakeDebugUnitTestRuntimeClasspath,fakeReleaseCompileClasspath,fakeReleaseRuntimeClasspath,fakeReleaseUnitTestCompileClasspath,fakeReleaseUnitTestRuntimeClasspath,localDebugAndroidTestCompileClasspath,localDebugAndroidTestRuntimeClasspath,localDebugCompileClasspath,localDebugRuntimeClasspath,localDebugUnitTestCompileClasspath,localDebugUnitTestRuntimeClasspath,localReleaseCompileClasspath,localReleaseRuntimeClasspath,localReleaseUnitTestCompileClasspath,localReleaseUnitTestRuntimeClasspath,productionDebugAndroidTestCompileClasspath,productionDebugAndroidTestRuntimeClasspath,productionDebugCompileClasspath,productionDebugRuntimeClasspath,productionDebugUnitTestCompileClasspath,productionDebugUnitTestRuntimeClasspath,productionReleaseCompileClasspath,productionReleaseRuntimeClasspath,productionReleaseUnitTestCompileClasspath,productionReleaseUnitTestRuntimeClasspath
com.apollographql.apollo3:apollo-normalized-cache:3.6.0=fakeDebugAndroidTestCompileClasspath,fakeDebugAndroidTestRuntimeClasspath,fakeDebugCompileClasspath,fakeDebugRuntimeClasspath,fakeDebugUnitTestCompileClasspath,fakeDebugUnitTestRuntimeClasspath,fakeReleaseCompileClasspath,fakeReleaseRuntimeClasspath,fakeReleaseUnitTestCompileClasspath,fakeReleaseUnitTestRuntimeClasspath,localDebugAndroidTestCompileClasspath,localDebugAndroidTestRuntimeClasspath,localDebugCompileClasspath,localDebugRuntimeClasspath,localDebugUnitTestCompileClasspath,localDebugUnitTestRuntimeClasspath,localReleaseCompileClasspath,localReleaseRuntimeClasspath,localReleaseUnitTestCompileClasspath,localReleaseUnitTestRuntimeClasspath,productionDebugAndroidTestCompileClasspath,productionDebugAndroidTestRuntimeClasspath,productionDebugCompileClasspath,productionDebugRuntimeClasspath,productionDebugUnitTestCompileClasspath,productionDebugUnitTestRuntimeClasspath,productionReleaseCompileClasspath,productionReleaseRuntimeClasspath,productionReleaseUnitTestCompileClasspath,productionReleaseUnitTestRuntimeClasspath
com.apollographql.apollo3:apollo-runtime-jvm:3.6.0=fakeDebugAndroidTestCompileClasspath,fakeDebugAndroidTestRuntimeClasspath,fakeDebugCompileClasspath,fakeDebugRuntimeClasspath,fakeDebugUnitTestCompileClasspath,fakeDebugUnitTestRuntimeClasspath,fakeReleaseCompileClasspath,fakeReleaseRuntimeClasspath,fakeReleaseUnitTestCompileClasspath,fakeReleaseUnitTestRuntimeClasspath,localDebugAndroidTestCompileClasspath,localDebugAndroidTestRuntimeClasspath,localDebugCompileClasspath,localDebugRuntimeClasspath,localDebugUnitTestCompileClasspath,localDebugUnitTestRuntimeClasspath,localReleaseCompileClasspath,localReleaseRuntimeClasspath,localReleaseUnitTestCompileClasspath,localReleaseUnitTestRuntimeClasspath,productionDebugAndroidTestCompileClasspath,productionDebugAndroidTestRuntimeClasspath,productionDebugCompileClasspath,productionDebugRuntimeClasspath,productionDebugUnitTestCompileClasspath,productionDebugUnitTestRuntimeClasspath,productionReleaseCompileClasspath,productionReleaseRuntimeClasspath,productionReleaseUnitTestCompileClasspath,productionReleaseUnitTestRuntimeClasspath
com.apollographql.apollo3:apollo-runtime:3.6.0=fakeDebugAndroidTestCompileClasspath,fakeDebugAndroidTestRuntimeClasspath,fakeDebugCompileClasspath,fakeDebugRuntimeClasspath,fakeDebugUnitTestCompileClasspath,fakeDebugUnitTestRuntimeClasspath,fakeReleaseCompileClasspath,fakeReleaseRuntimeClasspath,fakeReleaseUnitTestCompileClasspath,fakeReleaseUnitTestRuntimeClasspath,localDebugAndroidTestCompileClasspath,localDebugAndroidTestRuntimeClasspath,localDebugCompileClasspath,localDebugRuntimeClasspath,localDebugUnitTestCompileClasspath,localDebugUnitTestRuntimeClasspath,localReleaseCompileClasspath,localReleaseRuntimeClasspath,localReleaseUnitTestCompileClasspath,localReleaseUnitTestRuntimeClasspath,productionDebugAndroidTestCompileClasspath,productionDebugAndroidTestRuntimeClasspath,productionDebugCompileClasspath,productionDebugRuntimeClasspath,productionDebugUnitTestCompileClasspath,productionDebugUnitTestRuntimeClasspath,productionReleaseCompileClasspath,productionReleaseRuntimeClasspath,productionReleaseUnitTestCompileClasspath,productionReleaseUnitTestRuntimeClasspath
  ```
  
</details>

### Logs

```
   kotlin.NotImplementedError: An operation is not implemented: Not yet implemented
   	at com.apollographql.apollo3.cache.normalized.sql.internal.JsonRecordDatabase.selectAll(JsonRecordDatabase.kt:55)
   	at com.apollographql.apollo3.cache.normalized.sql.SqlNormalizedCache.dump(SqlNormalizedCache.kt:107)
   	at com.wave.apollo.TransientNormalisedCache.dump(TransientNormalisedCache.kt:37)
   	at com.apollographql.apollo3.cache.normalized.api.MemoryCache.dump(MemoryCache.kt:126)
   	at com.apollographql.apollo3.cache.normalized.api.internal.OptimisticCache.dump(OptimisticCache.kt:113)
   	at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore$dump$2.invoke(DefaultApolloStore.kt:248)
   	at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore$dump$2.invoke(DefaultApolloStore.kt:247)
   	at com.apollographql.apollo3.cache.normalized.internal.Lock.read(Lock.kt:12)
   	at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore.dump(DefaultApolloStore.kt:247)
```

### Steps to reproduce the behavior
Have an `ApolloClient` instance with a `SqlNormalizedCacheFactory` in the `normalizedCacheFactory` chain, then call `apolloClient.apolloStore.dump()`.

**Comment by martinbonnin** [comment]
Thanks for noticing this 🙏 . It'll be in next SNAPSHOT. We might wait a bit before doing a patch release this time unless it's too blocking for you, let us know :)

**Comment by martinbonnin** [comment]
Turns out we needed a new version for Kotlin 1.7.20 compatibility anyway so there it is :) : https://github.com/apollographql/apollo-kotlin/releases/tag/v3.6.2
