### ISSUE TITLE
[Java] NoSuchElementException during exception handling

### ISSUE THREAD

**Issue by tobiasdiez** [apollographql/apollo-kotlin#4448]
### Summary
I'm playing around with the new java module (I know its pre-alpha) and encountered an error, well, while encountering an error. I think something throw an error during the http request, but instead of properly reporting it another error is thrown.
I think here
https://github.com/apollographql/apollo-kotlin/blob/39df250747de5e3028dc6c11076a2315984d05d5/tests/java-client/src/test/java/test/ClientTest.java#L79-L83
the emitter error method should be called instead of `onComplete`.

### Version
Snapshot

### Logs

```
java.util.NoSuchElementException
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtSingle$ElementAtSubscriber.onComplete(FlowableElementAtSingle.java:115)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableCreate$BaseEmitter.completeDownstream(FlowableCreate.java:266)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:541)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.onComplete(FlowableCreate.java:496)
        at com.apollographql.apollo3.rx3.java.Rx3Apollo$1.onFailure(Rx3Apollo.java:38)
        at com.apollographql.apollo3.runtime.java.ApolloClient$NetworkInterceptor.intercept(ApolloClient.java:149)
        at com.apollographql.apollo3.runtime.java.DefaultInterceptorChain.proceed(DefaultInterceptorChain.java:33)
        at com.apollographql.apollo3.runtime.java.ApolloClient.lambda$execute$0(ApolloClient.java:77)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:858)
```

### Steps to reproduce the behavior
Not sure yet, but produce an error during the graphql http request or a 'wrong' response?

**Comment by tobiasdiez** [comment]
@BoD I would like to test if your recent PR indeed fixed this. However, the CI pipeline failed and thus it is not available as a SNAPSHOT release. Could you maybe retrigger the release? Thanks!

**Comment by martinbonnin** [comment]
I've just restarted [the workflow](https://github.com/apollographql/apollo-kotlin/actions/runs/3225900042)

**Comment by tobiasdiez** [comment]
Thanks, but it sadly failed again.

**Comment by martinbonnin** [comment]
Yikes, sorry for this. I just relaunched it. For some faster feedback loop, you can clone the repo and run use [local maven](https://github.com/apollographql/apollo-kotlin/blob/main/CONTRIBUTING.md#using-a-local-version-of-apollo-kotlin)

**Comment by tobiasdiez** [comment]
Now it works, and I can confirm that the issue is indeed fixed. Thanks!

**Comment by martinbonnin** [comment]
Nice, thanks for the update 🙏
