### ISSUE TITLE
Android apollo v3 graphql Query and Mutation + Failed to execute GraphQL http network request

### ISSUE THREAD

**Issue by Base2526** [apollographql/apollo-kotlin#4459]
Hi, Guy have a question i call graphql and return error

Exception :com.apollographql.apollo3.exception.ApolloNetworkException: Failed to execute GraphQL http network request

  
```
private class AuthorizationInterceptor(val context: Context) : Interceptor {
    override fun intercept(chain: Interceptor.Chain): Response {
        val request = chain.request().newBuilder()
            .addHeader("Authorization", "xxx")
            .build()

        return chain.proceed(request)
    }
}
```

```
  val okHttpClient = OkHttpClient.Builder()
        .addInterceptor(AuthorizationInterceptor(context))
        .build()
```
```

  var  instance = ApolloClient.Builder()
        .serverUrl("https://banlist.info/graphql")
        .okHttpClient(okHttpClient)
        .build()
```

```
val response = try {
                    apolloClient(context).mutation(SearchMutation()).execute()
                } catch (e: Exception) {
                    println("Exception :$e")
                    null
                }
```

**Comment by BoD** [comment]
Hi!

The code looks correct to me. This exception could be due to a connectivity issue or something else. Could you catch the exception and `printStackTrace`, to see more details?

**Comment by Base2526** [comment]
@BoD 
2022-10-17 14:43:03.504 24133-24133/com.banlistinfo I/System.out: Exception caught: com.apollographql.apollo3.exception.ApolloNetworkException: Failed to execute GraphQL http network request
2022-10-17 14:43:03.505 24133-24133/com.banlistinfo I/System.out:     at com.apollographql.apollo3.network.http.DefaultHttpEngine.execute(OkHttpEngine.kt:82)
2022-10-17 14:43:03.505 24133-24133/com.banlistinfo I/System.out:     at com.apollographql.apollo3.network.http.HttpNetworkTransport$EngineInterceptor.intercept(HttpNetworkTransport.kt:147)
2022-10-17 14:43:03.506 24133-24133/com.banlistinfo I/System.out:     at com.apollographql.apollo3.network.http.DefaultHttpInterceptorChain.proceed(HttpInterceptor.kt:22)
2022-10-17 14:43:03.506 24133-24133/com.banlistinfo I/System.out:     at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invokeSuspend(HttpNetworkTransport.kt:57)
2022-10-17 14:43:03.507 24133-24133/com.banlistinfo I/System.out:     at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invoke(Unknown Source:8)
2022-10-17 14:43:03.507 24133-24133/com.banlistinfo I/System.out:     at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invoke(Unknown Source:4)
2022-10-17 14:43:03.507 24133-24133/com.banlistinfo I/System.out:     at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
2022-10-17 14:43:03.508 24133-24133/com.banlistinfo I/System.out:     at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
2022-10-17 14:43:03.508 24133-24133/com.banlistinfo I/System.out:     at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:195)
2022-10-17 14:43:03.509 24133-24133/com.banlistinfo I/System.out:     at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157)
2022-10-17 14:43:03.509 24133-24133/com.banlistinfo I/System.out:     at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(Unknown Source:0)
2022-10-17 14:43:03.509 24133-24133/com.banlistinfo I/System.out:     at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
2022-10-17 14:43:03.511 24133-24133/com.banlistinfo I/System.out:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-10-17 14:43:03.511 24133-24133/com.banlistinfo I/System.out:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-10-17 14:43:03.512 24133-24133/com.banlistinfo I/System.out:     at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
2022-10-17 14:43:03.512 24133-24133/com.banlistinfo I/System.out:     at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
2022-10-17 14:43:03.512 24133-24133/com.banlistinfo I/System.out:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2022-10-17 14:43:03.513 24133-24133/com.banlistinfo I/System.out:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2022-10-17 14:43:03.515 24133-24133/com.banlistinfo I/System.out:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2022-10-17 14:43:03.515 24133-24133/com.banlistinfo I/System.out:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2022-10-17 14:43:03.515 24133-24133/com.banlistinfo I/System.out: Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2022-10-17 14:43:03.515 24133-24133/com.banlistinfo I/System.out:     at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
2022-10-17 14:43:03.516 24133-24133/com.banlistinfo I/System.out:     at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
2022-10-17 14:43:03.516 24133-24133/com.banlistinfo I/System.out:     at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
2022-10-17 14:43:03.516 24133-24133/com.banlistinfo I/System.out:     at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
2022-10-17 14:43:03.516 24133-24133/com.banlistinfo I/System.out:     at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
2022-10-17 14:43:03.516 24133-24133/com.banlistinfo I/System.out:     at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
2022-10-17 14:43:03.516 24133-24133/com.banlistinfo I/System.out:     at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:849)
2022-10-17 14:43:03.516 24133-24133/com.banlistinfo I/System.out:     at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
2022-10-17 14:43:03.517 24133-24133/com.banlistinfo I/System.out:     at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
2022-10-17 14:43:03.517 24133-24133/com.banlistinfo I/System.out:     at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
2022-10-17 14:43:03.517 24133-24133/com.banlistinfo I/System.out:     at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
2022-10-17 14:43:03.517 24133-24133/com.banlistinfo I/System.out:     at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
2022-10-17 14:43:03.517 24133-24133/com.banlistinfo I/System.out:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
2022-10-17 14:43:03.517 24133-24133/com.banlistinfo I/System.out:     at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
2022-10-17 14:43:03.517 24133-24133/com.banlistinfo I/System.out:     at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
2022-10-17 14:43:03.517 24133-24133/com.banlistinfo I/System.out:     at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
2022-10-17 14:43:03.517 24133-24133/com.banlistinfo I/System.out:     at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
2022-10-17 14:43:03.518 24133-24133/com.banlistinfo I/System.out:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
2022-10-17 14:43:03.518 24133-24133/com.banlistinfo I/System.out:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-10-17 14:43:03.518 24133-24133/com.banlistinfo I/System.out:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
2022-10-17 14:43:03.518 24133-24133/com.banlistinfo I/System.out:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-10-17 14:43:03.519 24133-24133/com.banlistinfo I/System.out:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
2022-10-17 14:43:03.519 24133-24133/com.banlistinfo I/System.out:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-10-17 14:43:03.519 24133-24133/com.banlistinfo I/System.out:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
2022-10-17 14:43:03.519 24133-24133/com.banlistinfo I/System.out:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-10-17 14:43:03.519 24133-24133/com.banlistinfo I/System.out:     at com.banlistinfo.AuthorizationInterceptor.intercept(Apollo.kt:45)
2022-10-17 14:43:03.519 24133-24133/com.banlistinfo I/System.out:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-10-17 14:43:03.520 24133-24133/com.banlistinfo I/System.out:     at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
2022-10-17 14:43:03.520 24133-24133/com.banlistinfo I/System.out:     at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
2022-10-17 14:43:03.520 24133-24133/com.banlistinfo I/System.out:     at com.apollographql.apollo3.network.http.DefaultHttpEngine.execute(OkHttpEngine.kt:74)
2022-10-17 14:43:03.520 24133-24133/com.banlistinfo I/System.out: 	... 19 more
2022-10-17 14:43:03.520 24133-24133/com.banlistinfo I/System.out: 	Suppressed: java.net.SocketTimeoutException: failed to connect to banlist.info/2400:6180:0:d1::7ae:b001 (port 443) from /2001:2::450c:4f86:a79e:f745 (port 46534) after 10000ms
2022-10-17 14:43:03.520 24133-24133/com.banlistinfo I/System.out:     at libcore.io.IoBridge.connectErrno(IoBridge.java:190)
2022-10-17 14:43:03.520 24133-24133/com.banlistinfo I/System.out:     at libcore.io.IoBridge.connect(IoBridge.java:134)
2022-10-17 14:43:03.520 24133-24133/com.banlistinfo I/System.out:     at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
2022-10-17 14:43:03.521 24133-24133/com.banlistinfo I/System.out:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
2022-10-17 14:43:03.521 24133-24133/com.banlistinfo I/System.out:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
2022-10-17 14:43:03.521 24133-24133/com.banlistinfo I/System.out:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
2022-10-17 14:43:03.521 24133-24133/com.banlistinfo I/System.out:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
2022-10-17 14:43:03.521 24133-24133/com.banlistinfo I/System.out:     at java.net.Socket.connect(Socket.java:621)
2022-10-17 14:43:03.521 24133-24133/com.banlistinfo I/System.out:     at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
2022-10-17 14:43:03.521 24133-24133/com.banlistinfo I/System.out:     at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
2022-10-17 14:43:03.521 24133-24133/com.banlistinfo I/System.out:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
2022-10-17 14:43:03.522 24133-24133/com.banlistinfo I/System.out: 		... 36 more
2022-10-17 14:43:03.522 24133-24133/com.banlistinfo I/System.out: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2022-10-17 14:43:03.522 24133-24133/com.banlistinfo I/System.out:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:661)
2022-10-17 14:43:03.522 24133-24133/com.banlistinfo I/System.out:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:510)
2022-10-17 14:43:03.522 24133-24133/com.banlistinfo I/System.out:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:428)
2022-10-17 14:43:03.522 24133-24133/com.banlistinfo I/System.out:     at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:356)
2022-10-17 14:43:03.522 24133-24133/com.banlistinfo I/System.out:     at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
2022-10-17 14:43:03.523 24133-24133/com.banlistinfo I/System.out:     at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
2022-10-17 14:43:03.523 24133-24133/com.banlistinfo I/System.out:     at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:161)
2022-10-17 14:43:03.523 24133-24133/com.banlistinfo I/System.out:     at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:250)
2022-10-17 14:43:03.523 24133-24133/com.banlistinfo I/System.out:     at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1644)
2022-10-17 14:43:03.523 24133-24133/com.banlistinfo I/System.out:     at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
2022-10-17 14:43:03.524 24133-24133/com.banlistinfo I/System.out:     at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
2022-10-17 14:43:03.524 24133-24133/com.banlistinfo I/System.out:     at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
2022-10-17 14:43:03.524 24133-24133/com.banlistinfo I/System.out:     at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
2022-10-17 14:43:03.524 24133-24133/com.banlistinfo I/System.out: 	... 46 more
2022-10-17 14:43:03.524 24133-24133/com.banlistinfo I/System.out: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2022-10-17 14:43:03.524 24133-24133/com.banlistinfo I/System.out: 	... 59 more

**Comment by BoD** [comment]
This indeed looks like an SSL certificate issue. This may be due to how the server is configured (does it use a self-signed certificate?). Or maybe are you using something like Charles Proxy (if so, you'll need to follow the SSL setup to install the certificate on your device)?

You _could_ configure your OkHttp to trust all certificates (see for instance this [SO question](https://stackoverflow.com/questions/6825226/trust-anchor-not-found-for-android-ssl-connection)), but this is in general a very bad idea in terms of security.

**Comment by Base2526** [comment]
@BoD ApolloClient can trust all certificates ?

**Comment by BoD** [comment]
> ApolloClient can trust all certificates ?

There is no specific ApolloClient setting to do that, but you can do it on your OhHttpClient, which you pass to the ApolloClient. Although, it is not advised to do this in production, for security reasons.

**Comment by Elangovanpdl** [comment]
@Base2526  How did you resolved this issue ? I am facing same issue now

**Comment by Base2526** [comment]
@Elangovanpdl You can setup Server SSL certificate sir, then call normal OK.

**Comment by bybuss** [comment]
create xml file with this config: 
```<?xml version="1.0" encoding="utf-8"?>
<YOUR NAME CONFIG FILE>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">YOUR IP FROM API</domain>
    </domain-config>
</YOUR NAME CONFIG FILE>```

then in AndroidManifest.xml in application tag add this line:
```android:networkSecurityConfig="@xml/YOUR NAME CONFIG FILE"```

after this you can send requests on your http api

**Comment by bybuss** [comment]
create xml file with this config: 


```<?xml version="1.0" encoding="utf-8"?>
<YOUR NAME CONFIG FILE>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">YOUR IP FROM API</domain>
    </domain-config>
</YOUR NAME CONFIG FILE>```


then in AndroidManifest.xml in application tag add this line:


```android:networkSecurityConfig="@xml/YOUR NAME CONFIG FILE"```


after this you can send requests on your http api

**Comment by bybuss** [comment]
create xml file with this config: 
```xml
<?xml version="1.0" encoding="utf-8"?>
<YOUR NAME CONFIG FILE>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">YOUR IP FROM API</domain>
    </domain-config>
</YOUR NAME CONFIG FILE>
```

then in AndroidManifest.xml in application tag add this line:
```xml
android:networkSecurityConfig="@xml/YOUR NAME CONFIG FILE"
```

after this you can send requests on your http api
