### ISSUE TITLE
GraphQLWsProtocol incorrectly parses error messages

### ISSUE THREAD

**Issue by vincentjames501** [apollographql/apollo-kotlin#4538]
### Summary

I'm using Hasura and sending queries/mutations/subscriptions over the `WebSocketNetworkTransport` using the `GraphQLWsProtocol`. 

According to the spec, it appears that the [error](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#error) message's `payload` should be of `GraphQLError[];`.

It looks like the code in [here](https://github.com/apollographql/apollo-kotlin/blob/05f2a3295517fb7a64c2259c38b453a37f3c4d19/libraries/apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo3/network/ws/GraphQLWsProtocol.kt#L120)

```kotlin
      "error" -> listener.operationError(messageMap["id"] as String, messageMap["payload"] as Map<String, Any?>)
```

It trying to cast the payload to a map when it should be casting it to an array of maps.

Example error payload from Hasura:

```json
{"type":"error","id":"eb14b901-c6d2-4144-b14d-c8ef64855ea3","payload":[{"extensions":{"code":"validation-failed","path":"$.selectionSet.extensionEndpointMappingsBulkUpdate.args.extensionEndpointMappingsBulkUpdateInput"},"message":"variable 'input' is declared as 'ExtensionEndpointMappingsBulkUpdateInput', but used where 'ExtensionEndpointMappingsBulkUpdateInput!' is expected"}]}
```

### Version

Apollo Runtime: 3.7.1

### Logs

Error generated from Apollo Kotlin

```
com.apollographql.apollo3.exception.ApolloNetworkException: Network error while executing ExtensionEndpointMappingsBulkUpdate
	at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$$inlined$map$1$2.emit(Emitters.kt:246)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:87)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:66)
	at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$3.invokeSuspend(WebSocketNetworkTransport.kt:271)
	at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$3.invoke(WebSocketNetworkTransport.kt)
	at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$3.invoke(WebSocketNetworkTransport.kt)
	at com.apollographql.apollo3.internal.FlowsKt$transformWhile$1$invokeSuspend$$inlined$collectWhile$1.emit(flows.kt:53)
	at com.apollographql.apollo3.internal.FlowsKt$transformWhile$1$invokeSuspend$$inlined$collectWhile$2.emit(flows.kt:38)
	at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$$inlined$filter$1$2.emit(Emitters.kt:223)
	at kotlinx.coroutines.flow.SubscribedFlowCollector.emit(Share.kt)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:383)
	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(SharedFlow.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.util.Map (java.util.ArrayList and java.util.Map are in module java.base of loader 'bootstrap')
	at com.apollographql.apollo3.network.ws.GraphQLWsProtocol.handleServerMessage(GraphQLWsProtocol.kt:120)
	at com.apollographql.apollo3.network.ws.WsProtocol.run$suspendImpl(WsProtocol.kt:144)
	at com.apollographql.apollo3.network.ws.WsProtocol$run$1.invokeSuspend(WsProtocol.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps to reproduce the behavior

Issue any invalid query the server wouldn't recognize over a `WebSocketNetworkTransport` using the `GraphQLWsProtocol`.

**Comment by martinbonnin** [comment]
Good catch 👍 . Not sure why this hasn't been an issue so far. I guess errors at this level are not very frequent. 

Interestingly, these errors are passed down to the call site as `Any?` and just removing the cast should make everything work. Do you want to give it a shot? If not, no worries, I'll make a patch, just let me know!

**Comment by martinbonnin** [comment]
Fix in #4540. Turns out this has not been an issue so far because the error you had should actually have been caught during codegen. Trying to use  a nullable input in a non-nullable position should have triggered a compile-time error. 

If you can share your schema and query, I'd be very curious to see if we're missing a validation rule there. Or maybe your client schema is a bit out of sync with your server schema. That's also another possibility.

In all cases, you're 100% right and the errors shouldn't be cast to a Map. This part should be fixed now and be part of the next release

**Comment by vincentjames501** [comment]
@martinbonnin , yeah originally it was because we had an under active development/fast evolving GQL API that got out of sync but it's also because we're trying to use this library in Clojure which we're basically just abandoning all type safety/code gen features this library gives so this is bound to happen to us. Thanks for the quick fix!

**Comment by martinbonnin** [comment]
This is now avilable in `3.7.2`
