### ISSUE TITLE
Runtime Exception: java.io.EOFException: source exhausted prematurely

### ISSUE THREAD

**Issue by chao2zhang** [apollographql/apollo-kotlin#4570]
### Summary

We have run into production exceptions in different queries but with similar stacktraces `java.io.EOFException: source exhausted prematurely`. This exception is happening at the rate of 1k/day for our applications.

### Version

2.5.14

### Steps to reproduce the behavior

- The query itself is probably 500 lines when fully expanded.
- The response size is at the scale of 100KB+.

- We are seeing a different exception for the same query for our iOS counterpart.
- We are thinking if this exception is just due to the fact that 
   - Either the response is too long and our vanilla graphql server cannot handle
   - The client application times out when parsing the response from server
   - In either case, the exception message was not clear and could be a lower-level issue.

### Logs

```
java.io.EOFException: source exhausted prematurely
    at okio.InflaterSource.read(InflaterSource.kt:184)
    at okio.GzipSource.read(GzipSource.kt:319)
    at okio.RealBufferedSource.indexOfElement(RealBufferedSource.kt:35)
    at com.apollographql.apollo.api.internal.json.BufferedSourceJsonReader.nextQuotedValue(BufferedSourceJsonReader.kt:4)
    at com.apollographql.apollo.api.internal.json.BufferedSourceJsonReader.nextString(BufferedSourceJsonReader.kt:118)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.nextString(ResponseJsonStreamReader.kt:24)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.nextScalar(ResponseJsonStreamReader.kt:162)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.toMap(ResponseJsonStreamReader.kt:120)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader$readObject$1.read(ResponseJsonStreamReader.kt:7)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.nextObject(ResponseJsonStreamReader.kt:26)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.readObject(ResponseJsonStreamReader.kt:7)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.toMap(ResponseJsonStreamReader.kt:84)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader$readObject$1.read(ResponseJsonStreamReader.kt:7)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.nextObject(ResponseJsonStreamReader.kt:26)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.readObject(ResponseJsonStreamReader.kt:7)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.toMap(ResponseJsonStreamReader.kt:84)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader$readObject$1.read(ResponseJsonStreamReader.kt:7)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.nextObject(ResponseJsonStreamReader.kt:26)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.readObject(ResponseJsonStreamReader.kt:7)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.toMap(ResponseJsonStreamReader.kt:84)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader$readObject$1.read(ResponseJsonStreamReader.kt:7)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.nextObject(ResponseJsonStreamReader.kt:26)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.readObject(ResponseJsonStreamReader.kt:7)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader$readList$1.read(ResponseJsonStreamReader.kt:59)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.nextList(ResponseJsonStreamReader.kt:39)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.toMap(ResponseJsonStreamReader.kt:112)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader$readObject$1.read(ResponseJsonStreamReader.kt:7)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.nextObject(ResponseJsonStreamReader.kt:26)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.readObject(ResponseJsonStreamReader.kt:7)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.toMap(ResponseJsonStreamReader.kt:84)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader$readObject$1.read(ResponseJsonStreamReader.kt:7)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.nextObject(ResponseJsonStreamReader.kt:26)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.readObject(ResponseJsonStreamReader.kt:7)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader$readList$1.read(ResponseJsonStreamReader.kt:59)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.nextList(ResponseJsonStreamReader.kt:39)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.toMap(ResponseJsonStreamReader.kt:112)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader$readObject$1.read(ResponseJsonStreamReader.kt:7)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.nextObject(ResponseJsonStreamReader.kt:26)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.readObject(ResponseJsonStreamReader.kt:7)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.toMap(ResponseJsonStreamReader.kt:84)
    at com.apollographql.apollo.response.OperationResponseParser$1.read(OperationResponseParser.java:1)
    at com.apollographql.apollo.api.internal.json.ResponseJsonStreamReader.nextObject(ResponseJsonStreamReader.kt:26)
    at com.apollographql.apollo.response.OperationResponseParser.parse(OperationResponseParser.java:55)
    at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:40)
    at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:22)
    at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$executeHttpCall$1.onResponse(ApolloServerInterceptor.kt:44)
    at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:58)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)
com.apollographql.apollo.exception.ApolloParseException: Failed to parse http response
    at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:117)
    at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:22)
    at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$executeHttpCall$1.onResponse(ApolloServerInterceptor.kt:44)
    at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:58)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)
java.lang.RuntimeException: SearchResultsPlacementsQuery: Failed to parse http response
    at com.instacart.client.apollo.ICApolloErrorLogger.<init>(ICApolloErrorLogger.kt:1)
    at com.instacart.client.apollo.ICApolloDelegate.applyResponseHandling(ICApolloDelegate.kt:3)
    at com.instacart.client.apollo.ICApolloDelegate.query(ICApolloDelegate.kt:65)
    at com.instacart.client.apollo.ICApolloApiImpl.query(ICApolloApiImpl.kt:13)
    at com.instacart.client.search.ICSearchPlacementsRepo$fetchResults$1.invoke(ICSearchPlacementsRepo.kt:46)
    at com.instacart.client.search.ICSearchPlacementsRepo$fetchResults$1.invoke(ICSearchPlacementsRepo.kt:1)
    at com.instacart.client.lce.utils.ICLceUtils$retryEvent$1.invoke(ICLceUtils.kt:2)
    at com.instacart.client.lce.utils.ICLceUtils$retryEvent$1.invoke(ICLceUtils.kt:1)
    at com.instacart.client.lce.utils.ICLceUtils$$ExternalSyntheticLambda1.apply(R8$$SyntheticClass:26)
    at io.reactivex.rxjava3.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.onNext(ObservableSwitchMap.java:23)
    at io.reactivex.rxjava3.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver$DelayErrorInnerObserver.onNext(ObservableConcatMap.java:3)
    at com.jakewharton.rxrelay3.PublishRelay$PublishDisposable.onNext(PublishRelay.java:9)
    at com.jakewharton.rxrelay3.PublishRelay.accept(PublishRelay.java:17)
    at com.jakewharton.rxrelay3.SerializedRelay.accept(SerializedRelay.java:51)
    at com.instacart.client.lce.utils.ICLceUtils$retryEvent$1$1$1.invoke(ICLceUtils.kt:2)
    at com.instacart.client.lce.utils.ICLceUtils$retryEvent$1$1$1.invoke(ICLceUtils.kt:1)
    at com.instacart.client.ui.lce.ICLoadingErrorScreen$toOnClickListener$1.onClick(ICLoadingErrorScreen.kt:16)
    at android.view.View.performClick(View.java:7792)
    at android.widget.TextView.performClick(TextView.java:16112)
    at android.view.View.performClickInternal(View.java:7769)
    at android.view.View.access$3800(View.java:910)
    at android.view.View$PerformClick.run(View.java:30218)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8663)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### Anything else?

Posting this issue here for posterity (We have tried searching elsewhere and didn't find valuable clues), and this repository seems the best to start the conversation

**Comment by chao2zhang** [comment]
@Jawnnypoo @bohan-v @huangc10

**Comment by martinbonnin** [comment]
Thanks for opening this @chao2zhang. Searching for the OkHttp issue links to two OkHttp issues (https://github.com/square/okhttp/issues/4277, https://github.com/square/okhttp/issues/2193) that points to two possible explanations:

* trailer bytes at the end of the compressed stream are missing.
* content-length returned is the one of the original response, not the content-length of the compressed response.

Did you want Apollo Kotlin to handle things differently here?

**Comment by martinbonnin** [comment]
Closing this one as it's unclear what can be done from Apollo's side. Feel free to leave a comment if you want me to reopen.

**Comment by Jawnnypoo** [comment]
Thanks Martin, we are investigating further on our end - we suspect it may be a timeout issue or something server related.
