### ISSUE TITLE
toFlow() and .watch() result in IllegalArgumentException: Flow has more than one element

### ISSUE THREAD

**Issue by darvelo** [apollographql/apollo-kotlin#4617]
### Version

3.7.3

### Summary

When using cache and network, both:

- `apollo.query(makeQuery()).fetchPolicy(FetchPolicy.CacheAndNetwork).toFlow()`
- `apollo.query(makeQuery()).fetchPolicy(FetchPolicy.CacheAndNetwork).watch()`

result in `java.lang.IllegalArgumentException: Flow has more than one element`.

If I use `FetchPolicy.NetworkOnly` no exception is thrown and the data is collected as expected. Am I using the `FetchPolicy` feature correctly? I assumed the flow would emit twice, once for the cache and one more time for the network. Likewise I assumed that `.watch()` will continuously emit whenever the cache updates, such as after a mutation in another part of the app that updates any of the data related to the original query.

I'm also noticing that after deleting the app and rerunning it, the sqlite database in the Device File Explorer is populated with data from a very old version of the schema, when the schema and data types were completely different. Could this be related? EDIT: For this cleaning and rebuilding the project fixed it. The flow exception still remains.

**Comment by martinbonnin** [comment]
Thanks for reaching out. That sounds unexpected 🤔 . Can you copy paste the full stacktrace? Looks like there's a `single()` operator somewhere.

**Comment by darvelo** [comment]
@martinbonnin Sure, does something like this help?
<img width="1349" alt="Screenshot 2023-01-11 at 10 53 02 PM" src="https://user-images.githubusercontent.com/523169/211852915-400ce73f-d0b5-444f-9249-5f59e7a613a6.png">

**Comment by martinbonnin** [comment]
Thanks! It would be nice to have the lines too (as in `exception.printStackTrace()`.

Looking around the code that's in there, I can find one `single()` [there](https://github.com/apollographql/apollo-kotlin/blob/05f2a3295517fb7a64c2259c38b453a37f3c4d19/libraries/apollo-normalized-cache/src/commonMain/kotlin/com/apollographql/apollo3/cache/normalized/FetchPolicyInterceptors.kt#L177) but I wouldn't expect this to emit multiple times...

How did you setup your interceptor chain/`ApolloClient.Builder`? Did you add anything else besides cache?

**Comment by darvelo** [comment]
Ok! Thanks for your support. Here's what the stack trace printed:

```
HttpClient(_cause=java.lang.IllegalArgumentException: Flow has more than one element)
	at com.davidarvelo.app.core.interactors.BaseQueryInteractor$mapped$1.invokeSuspend(BaseQueryInteractor.kt:49)
	at com.davidarvelo.app.core.interactors.BaseQueryInteractor$mapped$1.invoke(Unknown Source:9)
	at com.davidarvelo.app.core.interactors.BaseQueryInteractor$mapped$1.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:114)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.IllegalArgumentException: Flow has more than one element
	at kotlinx.coroutines.flow.FlowKt__ReduceKt$single$2.emit(Reduce.kt:58)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:87)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:66)
	at com.apollographql.apollo3.cache.normalized.FetchPolicyInterceptors$CacheAndNetworkInterceptor$1$intercept$1$invokeSuspend$$inlined$map$1$2.emit(Emitters.kt:223)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$2.emit(Errors.kt:158)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:62)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	... 9 more
```

This is the contents of my `ApolloClient.Builder`:

```kotlin
private var appSettingsStorage: SettingsStorage? = null

object DataClient {

    private const val AUTHORIZATION_HEADER = "Authorization"

    private val memoryFirstThenSqlCacheFactory = MemoryCacheFactory(10 * 1024 * 1024)
    // I used to use this but it's buggy for now.
    // Seems SQLite is returning duplicate records and
    // Apollo cancels the flow because it expects a single record.
    // TODO: Maybe in a later version of Apollo (as of this writing, 3.7.3) I can re-enable this.
//    .chain(SqlNormalizedCacheFactory("habbit.db"))

    val apollo = ApolloClient.Builder()
        .serverUrl("http://localhost:4000/graphql")
        .addHttpInterceptor(AuthorizationInterceptor())
        // Note that mutations will always be sent as POST requests, regardless of these settings, as to avoid hitting caches.
        .autoPersistedQueries(
            // For the initial hashed query that does not send the actual Graphql document
            httpMethodForHashedQueries = HttpMethod.Get,
            // For the follow-up query that sends the full document if the initial hashed query was not found
            httpMethodForDocumentQueries = HttpMethod.Get
        )
        .normalizedCache(normalizedCacheFactory = memoryFirstThenSqlCacheFactory)
        .build()

    fun configure(settingsStorage: SettingsStorage) {
        appSettingsStorage = settingsStorage
    }

    class AuthorizationInterceptor : HttpInterceptor {
        override suspend fun intercept(request: HttpRequest, chain: HttpInterceptorChain): HttpResponse {
            val requestBuilder = request.newBuilder().let {
                val authToken = appSettingsStorage?.authToken
                if (authToken != null) {
                    it.addHeader(AUTHORIZATION_HEADER, "Bearer $authToken")
                } else {
                    it
                }
            }
            return chain.proceed(requestBuilder.build())
        }
    }
}
```

**Comment by martinbonnin** [comment]
Thanks for sending that! Coroutines do not help with investigating the stack trace unfortunately... Maybe try without autopersisted queries? Does that change anything? 
I'll work on a small reproducer project, see if we can manage to reproduce something

**Comment by martinbonnin** [comment]
I can reproduce and this seems to be linked to auto persisted queries indeed. I'll keep digging

**Comment by martinbonnin** [comment]
Turns out [this is the culprit `single()`](https://github.com/apollographql/apollo-kotlin/blob/05f2a3295517fb7a64c2259c38b453a37f3c4d19/libraries/apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo3/interceptor/AutoPersistedQueryInterceptor.kt#L38)

I'll investigate how to make the configuration more robust. In the meantime, you can workaround this issue by configuring the auto persisted queries after the cache:

```kotlin
    val apollo = ApolloClient.Builder()
        .serverUrl("http://localhost:4000/graphql")
        .addHttpInterceptor(AuthorizationInterceptor())
        // Configure cache first
        .normalizedCache(normalizedCacheFactory = memoryFirstThenSqlCacheFactory)
        // And APQ last
        // Note that mutations will always be sent as POST requests, regardless of these settings, as to avoid hitting caches.
        .autoPersistedQueries(
            // For the initial hashed query that does not send the actual Graphql document
            httpMethodForHashedQueries = HttpMethod.Get,
            // For the follow-up query that sends the full document if the initial hashed query was not found
            httpMethodForDocumentQueries = HttpMethod.Get
        )
        .build()

```

**Comment by darvelo** [comment]
That was so fast! I added the workaround and it works as expected. Thank you so much!
