### ISSUE TITLE
It doesn't send required websocket request to backend server

### ISSUE THREAD

**Issue by zhaoyi0113** [apollographql/apollo-kotlin#4636]
### Version

3.7.3

### Summary

I am using Apollo client ilbrary to send graphql subscription request to backend which is a websocket apigateway hosted in AWS. From the app side, I got this error: `Caused by: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 10000 ms`. The full error log is attached at the bottom

From server side, I can see it sends a `CONNECT` request followed by a `MESSAGE` request. The `type` of the `MESSAGE` request is `connection_init`. After that it stops sending next request which should be `type` of `start` that includes the subscription payload. 

The same server works fine with Apollo nodejs client.
I wonder why it doesn't send all the requests to backend.

### Steps to reproduce the behavior

I build the apollo client by:

```
apolloClient = ApolloClient.Builder()
            .serverUrl("https://xxx.execute-api.ap-southeast-2.amazonaws.com/dev/graphql")
            .webSocketServerUrl("wss://xxx.execute-api.ap-southeast-2.amazonaws.com/dev")
            .build()

GlobalScope.launch {
            // Execute your query. This will suspend until the response is received.
            Log.i("gpl", "send subscription")
            apolloClient.subscription(EventSubscription()).toFlow().collect {
                Log.i("gpl", "receive subscription" + it)
                subscriptionText.append(it.data?.event?.msg)
            }
        }

```

### Logs

```
2023-01-18 17:28:18.765 15242-15265/com.example.rocketreserver I/gpl: send subscription
2023-01-18 17:28:18.826 15242-15260/com.example.rocketreserver D/HostConnection: createUnique: call
2023-01-18 17:28:18.829 15242-15260/com.example.rocketreserver D/HostConnection: HostConnection::get() New Host Connection established 0xb400007a1d5765d0, tid 15260
2023-01-18 17:28:18.844 15242-15260/com.example.rocketreserver D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma ANDROID_EMU_hwc_multi_configs GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
2023-01-18 17:28:18.853 15242-15242/com.example.rocketreserver W/RecyclerView: No adapter attached; skipping layout
2023-01-18 17:28:18.861 15242-15260/com.example.rocketreserver W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
2023-01-18 17:28:18.862 15242-15260/com.example.rocketreserver W/OpenGLRenderer: Failed to initialize 101010-2 format, error = EGL_SUCCESS
2023-01-18 17:28:18.862 15242-15260/com.example.rocketreserver D/EGL_emulation: eglCreateContext: 0xb400007a1d5789d0: maj 3 min 0 rcv 3
2023-01-18 17:28:18.863 15242-15260/com.example.rocketreserver D/EGL_emulation: eglMakeCurrent: 0xb400007a1d5789d0: ver 3 0 (tinfo 0x7c37b61080) (first time)
2023-01-18 17:28:18.905 15242-15260/com.example.rocketreserver I/Gralloc4: mapper 4.x is not supported
2023-01-18 17:28:18.906 15242-15260/com.example.rocketreserver D/HostConnection: createUnique: call
2023-01-18 17:28:18.906 15242-15260/com.example.rocketreserver D/HostConnection: HostConnection::get() New Host Connection established 0xb400007a1d576ed0, tid 15260
2023-01-18 17:28:18.907 15242-15260/com.example.rocketreserver D/goldfish-address-space: allocate: Ask for block of size 0x100
2023-01-18 17:28:18.907 15242-15260/com.example.rocketreserver D/goldfish-address-space: allocate: ioctl allocate returned offset 0x1efff8000 size 0x8000
2023-01-18 17:28:18.909 15242-15260/com.example.rocketreserver W/Gralloc4: allocator 4.x is not supported
2023-01-18 17:28:18.914 15242-15260/com.example.rocketreserver D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma ANDROID_EMU_hwc_multi_configs GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
2023-01-18 17:28:20.175 15242-15251/com.example.rocketreserver W/System: A resource failed to call close. 
2023-01-18 17:28:29.181 15242-15266/com.example.rocketreserver E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
    Process: com.example.rocketreserver, PID: 15242
    com.apollographql.apollo3.exception.ApolloNetworkException: Network error while executing event
        at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$$inlined$map$1$2.emit(Emitters.kt:246)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:87)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:66)
        at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$3.invokeSuspend(WebSocketNetworkTransport.kt:271)
        at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$3.invoke(Unknown Source:13)
        at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$3.invoke(Unknown Source:6)
        at com.apollographql.apollo3.internal.FlowsKt$transformWhile$1$invokeSuspend$$inlined$collectWhile$1.emit(flows.kt:53)
        at com.apollographql.apollo3.internal.FlowsKt$transformWhile$1$invokeSuspend$$inlined$collectWhile$2.emit(flows.kt:38)
        at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$$inlined$filter$1$2.emit(Emitters.kt:223)
        at kotlinx.coroutines.flow.SubscribedFlowCollector.emit(Unknown Source:2)
        at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:383)
        at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f401bd7, Dispatchers.Default]
    Caused by: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 10000 ms
        at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:184)
        at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:154)
        at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:508)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
        at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
        at java.lang.Thread.run(Thread.java:920)
2023-01-18 17:28:29.276 15242-15260/com.example.rocketreserver D/EGL_emulation: app_time_stats: avg=931.19ms min=1.76ms max=9902.87ms count=11
2023-01-18 17:28:29.385 15242-15266/? I/Process: Sending signal. PID: 15242 SIG: 9


```

**Comment by BoD** [comment]
Hi!

This timeout [happens](https://github.com/apollographql/apollo-kotlin/blob/05f2a3295517fb7a64c2259c38b453a37f3c4d19/libraries/apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo3/network/ws/SubscriptionWsProtocol.kt#L38) when waiting for the server's ack (or error) following the `connection_init`. Can you tell if this message is ever sent back?

Also, that there are 3 different WebSocket protocols that can be configured with Apollo Kotlin, depending on the server: 
- [SubscriptionWsProtocol](https://github.com/apollographql/apollo-kotlin/blob/05f2a3295517fb7a64c2259c38b453a37f3c4d19/libraries/apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo3/network/ws/SubscriptionWsProtocol.kt#L16) (the default)
- [GraphQLWsProtocol](https://github.com/apollographql/apollo-kotlin/blob/3f7e81b59ea2711a2eeb90087a1a3ba1b240082c/libraries/apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo3/network/ws/GraphQLWsProtocol.kt#L20)
- [AppSyncWsProtocol](https://github.com/apollographql/apollo-kotlin/blob/05f2a3295517fb7a64c2259c38b453a37f3c4d19/libraries/apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo3/network/ws/AppSyncWsProtocol.kt#L19) (for AWS AppSync)

that can be configured by calling `subscriptionNetworkTransport` on the ApolloClient (see an example for AppSync [here](https://github.com/apollographql/apollo-kotlin/blob/99590381c4dfbeed2b72665da6df6b2a9a941ac9/tests/websockets/src/commonTest/kotlin/AppSyncTest.kt#L59)).

I don't guess your issue is due to the wrong protocol though, because this part of the code is the same for all 3, but it's still worth mentioning.

The frame type (text or binary - default is text) can also be configured on the protocol, maybe it could be worth trying binary?

**Comment by zhaoyi0113** [comment]
Hi,

Thanks for your reply.

I can confirm the the backend response `connection_init` but it doesn't receive the next request. The same backend works well for Apollo Nodejs client that makes me think the issue is in Kotlin client side.

The example you linked is using `https` protocol but my code is using `wss://xxx`. Will that be much different?

Based on the log I shared, do you see whether Kotlin receives the `connection_init` response but failed to parse or it doesn't even receive any response from the server? Is there any detailed log I can investigate?

**Comment by BoD** [comment]
> The example you linked is using https protocol but my code is using wss://xxx. Will that be much different?

No this is actually equivalent and shouldn't matter.

>Based on the log I shared, do you see whether Kotlin receives the connection_init response but failed to parse or it doesn't even receive any response from the server? Is there any detailed log I can investigate?

From what I can tell from the log and exception is that it looks as if the server never replies to the `connection_init` message, and a timeout happens while waiting for it.

Would you be able to use [Charles Proxy](https://www.charlesproxy.com/) or a similar tool to see what is actually sent/received (this would also enable you to compare with the nodeJS version that works)?

You may also try `GraphQLWsProtocol` as from what I can tell this is the default on Apollo Client JS - maybe that's what your server expects?

**Comment by zhaoyi0113** [comment]
Sure I think I can try GraphQLWsProtocol first. Do you have instruction on how to configure this protocol class?

**Comment by BoD** [comment]
For sure, you can do it this way:

```kotlin
val apolloClient = ApolloClient.Builder()
            .serverUrl("https://xxx.execute-api.ap-southeast-2.amazonaws.com/dev/graphql")
            .webSocketServerUrl("wss://xxx.execute-api.ap-southeast-2.amazonaws.com/dev")
            .wsProtocol(GraphQLWsProtocol.Factory()) // <- this line
            .build()
```

If you want to try the binary frame type, that would be 
```kotlin
            .wsProtocol(GraphQLWsProtocol.Factory(frameType = WsFrameType.Binary))
```

There are also other options you can pass (for instance some servers expect some authentication parameters in `connectionPayload`) , see [here](https://github.com/apollographql/apollo-kotlin/blob/3f7e81b59ea2711a2eeb90087a1a3ba1b240082c/libraries/apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo3/network/ws/GraphQLWsProtocol.kt#L190).

**Comment by zhaoyi0113** [comment]
unfortunately this `.wsProtocol(GraphQLWsProtocol.Factory())` doesn't solve the issue. I get the same error.

change the frame type gives me a new error

```
 Caused by: com.apollographql.apollo3.exception.ApolloWebSocketClosedException: WebSocket Closed code='1003' reason='Binary is not supported'
        at com.apollographql.apollo3.network.ws.DefaultWebSocketEngine$open$webSocket$1.onClosing(OkHttpWebSocketEngine.kt:64)
        at okhttp3.internal.ws.RealWebSocket.onReadClose(RealWebSocket.kt:378)
        at okhttp3.internal.ws.WebSocketReader.readControlFrame(WebSocketReader.kt:220)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:104)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```

probably the server doesn't support binary frame type.

**Comment by BoD** [comment]
Thanks - this at least closes these possibilities.

At this point I think it would make sense to try with Charles Proxy or similar to investigate. If your server is public I can also try to have a look on my side?

**Comment by zhaoyi0113** [comment]
Great if you can try from your side, this is the code I am using:

```
ApolloClient.Builder()
            .serverUrl("https://ckz5xbx3ee.execute-api.ap-southeast-2.amazonaws.com/dev/graphql")
            .webSocketServerUrl("wss://jkpmcizu0i.execute-api.ap-southeast-2.amazonaws.com/dev")
            .wsProtocol(GraphQLWsProtocol.Factory())
            .build()

GlobalScope.launch {
            // Execute your query. This will suspend until the response is received.
            Log.i("gpl", "send subscription")
            apolloClient.subscription(EventSubscription()).toFlow().collect {
                Log.i("gpl", "receive subscription" + it)
                subscriptionText.append(it.data?.event?.msg)
            }
        }
```

**Comment by zhaoyi0113** [comment]
I have compared the request the server receive between nodejs and kotlin, 

nodejs:

```
{AccountID:"", ResourceID:"", Stage:"dev", RequestID:"fAqFaGBfywMFoDg=", Identity:events.APIGatewayRequestIdentity{CognitoIdentityPoolID:"", AccountID:"", CognitoIdentityID:"", Caller:"", APIKey:"", APIKeyID:"", AccessKey:"", SourceIP:"165.225.226.218", CognitoAuthenticationType:"", CognitoAuthenticationProvider:"", UserArn:"", UserAgent:"okhttp/4.9.3", User:""}, ResourcePath:"", Authorizer:interface {}(nil), HTTPMethod:"", APIID:"jkpmcizu0i", ConnectedAt:1674165588941, ConnectionID:"fAqFTcS6ywMCJqg=", DomainName:"jkpmcizu0i.execute-api.ap-southeast-2.amazonaws.com", Error:"", EventType:"MESSAGE", ExtendedRequestID:"fAqFaGBfywMFoDg=", IntegrationLatency:"", MessageDirection:"IN", MessageID:"fAqFacS-SwMCJqg=", RequestTime:"19/Jan/2023:21:59:49 +0000", RequestTimeEpoch:1674165589606, RouteKey:"$default", Status:""}
```


kotlin:

```
{AccountID:"", ResourceID:"", Stage:"dev", RequestID:"fArZzGGtywMF0Dg=", Identity:events.APIGatewayRequestIdentity{CognitoIdentityPoolID:"", AccountID:"", CognitoIdentityID:"", Caller:"", APIKey:"", APIKeyID:"", AccessKey:"", SourceIP:"165.225.226.218", CognitoAuthenticationType:"", CognitoAuthenticationProvider:"", UserArn:"", UserAgent:"", User:""}, ResourcePath:"", Authorizer:interface {}(nil), HTTPMethod:"", APIID:"jkpmcizu0i", ConnectedAt:1674166129061, ConnectionID:"fArZsdziSwMCHng=", DomainName:"jkpmcizu0i.execute-api.ap-southeast-2.amazonaws.com", Error:"", EventType:"MESSAGE", ExtendedRequestID:"fArZzGGtywMF0Dg=", IntegrationLatency:"", MessageDirection:"IN", MessageID:"fArZzdzpSwMCHng=", RequestTime:"19/Jan/2023:22:08:49 +0000", RequestTimeEpoch:1674166129792, RouteKey:"$default", Status:""}
```

The only different I can see is that kotlin doesn't have any value for the field `UserAgent`. Is there a way for me to add this field?

**Comment by BoD** [comment]
For the sake of posterity, it was an issue with the server not sending the `connection_init` message.
