### ISSUE TITLE
java.lang.NoSuchMethodError:  'void kotlin.jvm.internal. on calling Apollo Kotlin client

### ISSUE THREAD

**Issue by sherry-ummen-zalando** [apollographql/apollo-kotlin#4748]
### Question

I have a Java spring boot project where I am mixing kotlin. Though I am stuck with this runtime exception. Which I do not understand why it happens and how to solve this. It happening on the call to apollo kotlin client. I am assuming there is some mismatch with the version. But cannot really figure.

```
Caused by: java.lang.NoSuchMethodError: 'void kotlin.jvm.internal.FunctionReferenceImpl.<init>(int, java.lang.Class, java.lang.String, java.lang.String, int)'
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.<init>(SafeCollector.kt) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.<clinit>(SafeCollector.kt) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.flow.internal.SafeCollectorKt.<clinit>(SafeCollector.kt:15) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:87) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:66) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invokeSuspend(HttpNetworkTransport.kt:83) ~[apollo-runtime-jvm-3.7.4.jar:3.7.4]
	at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invoke(HttpNetworkTransport.kt) ~[apollo-runtime-jvm-3.7.4.jar:3.7.4]
	at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invoke(HttpNetworkTransport.kt) ~[apollo-runtime-jvm-3.7.4.jar:3.7.4]
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
```
Happens for the following code
```kotlin
 val response = runBlocking {
        apolloClient.mutation(
          UpdateCuratedCollectionMutation(
            input = curatedCollectionInput,
            version = collection.updatedAt.toEpochSecond()
          )
        ).execute()
    }
    
```

My dependencies are following
```
springBootVersion = '2.7.4'
id "org.jetbrains.kotlin.jvm" version "1.8.10"
id "com.apollographql.apollo3" version "3.7.4"
id 'org.jetbrains.kotlin.plugin.lombok' version '1.8.10'
id 'io.freefair.lombok' version '5.3.0'
implementation 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.10'
implementation "com.apollographql.apollo3:apollo-runtime:3.7.4"
```
Adding the dependency graph as well
[dependency.txt](https://github.com/apollographql/apollo-kotlin/files/10934569/dependency.txt)

**Comment by BoD** [comment]
Hi!

We've had similar issues with SpringBoot before (#4300, #4048) but I'm not sure they are the same as this one. What I can see in your dependency.txt looks good so I'm a bit puzzled.

The object `FunctionReferenceImpl` is in the [Kotlin stdlib](https://github.com/JetBrains/kotlin/blob/master/libraries/stdlib/jvm/runtime/kotlin/jvm/internal/FunctionReferenceImpl.java). It looks like the constructor receiving `int, java.lang.Class, java.lang.String, java.lang.String, int` exists since 1.4, and the one in your classpath is 1.8.

This also looks a bit like https://youtrack.jetbrains.com/issue/KT-39389, albeit it is about older versions, and the last comment is more than a year old, also I'm not clear on what the workaround is.

Would it be possible for you to share a simple project that shows the issue?

**Comment by sherry-ummen-zalando** [comment]
Thank you @BoD . I have created a project which is very close to my current project structure and the dependencies and problem is reproducible https://github.com/sherry-ummen-zalando/apollo-kotlin-issue

**Comment by sherry-ummen-zalando** [comment]
I got it working by upgrading the springboot and java version. https://github.com/sherry-ummen-zalando/apollo-kotlin-issue/tree/working_project

But looking at the dependencies its still not clear what is fixing the problem.

Also in my official project its super challenging to move to latest springboot :(

**Comment by BoD** [comment]
Hi! Thanks a lot for the repro project, that helps a lot!

Thanks for the update about making it work with a more recent SpringBoot.

I could also make the issue disappear on the repro project by removing a single dependency: `com.lightstep.tracer:lightstep-tracer-jre-bundle:0.30.5`. 

Not familiar with it and not sure yet why it's causing problems but wanted to share quickly.

> But looking at the dependencies its still not clear what is fixing the problem.

Same here 😅

**Comment by sherry-ummen-zalando** [comment]
huh awesome .. pff weird side affects

**Comment by BoD** [comment]
Thanks for the follow-up. 

Just to investigate a bit further I tried on a barebones project with Kotlin only, _without_ SpringBoot, but _with_ lightstep-tracer, to see if I could reproduce, and nope.

**Comment by sherry-ummen-zalando** [comment]
so you are not able to reproduce with barebone project ?

**Comment by BoD** [comment]
> so you are not able to reproduce with barebone project ?

Correct ✅

**Comment by sherry-ummen-zalando** [comment]
so springboot being notorious here?

**Comment by BoD** [comment]
> so springboot being notorious here?

It's certainly a combination of things :) Since a few other classpath issues in the past involved SpringBoot I'd tend to think there's something going on, but at this moment I don't understand what the exact culprit is.

**Comment by BoD** [comment]
It looks like we have an explanation (courtesy of @martinbonnin ! 🙏 ). `com.lightstep.tracer:lightstep-tracer-jre-bundle` is a "fat jar" that contains an old version of the kotlin stdlib - and so that's the one that used.

If you need it, you can instead depend on `com.lightstep.tracer:lightstep-tracer-jre` (without "bundle"), which will depend on it "the maven way".

**Comment by sherry-ummen-zalando** [comment]
awesome. thank you @BoD and @martinbonnin its fixed. I am closing this ticket. thank you for the excellent support :)
