### ISSUE TITLE
Hardcoded directive (@skip) when used with normalized cache results in RunTimeException.

### ISSUE THREAD

**Issue by ArjanSM** [apollographql/apollo-kotlin#4772]
### Version

v3.6.2

### Summary

I have a very simple query which uses a hardcoded value on the directive `@skip(if:true)` applied on a scalar field. 
While the project builds successfully, the operation, when executed throws a runtime exception. 
However, the exception is only thrown when the `normalizedCache` is enabled on the `ApolloClient`.

#### Probable Cause:-
The selection field shouldn't included in the request but somehow is. I've not read that part of the code.
Exception is thrown in the [Normalizer.kt](https://github.com/apollographql/apollo-kotlin/blob/main/libraries/apollo-normalized-cache-api/src/commonMain/kotlin/com/apollographql/apollo3/cache/normalized/api/internal/Normalizer.kt#L58)

### Steps to reproduce the behavior

Try executing the following query with the `normalizedCache` enabled.
```
query getCountry($code:ID!) {
  country(code:$code) {
    code @skip(if:true)
    name
  }
}
```
A runtime exception is thrown on executing this operation.
Here's the initialization of my ApolloClient

```
val  apolloClient = ApolloClient.Builder()
                .okHttpClient(OkHttpClient.Builder()
                    .addInterceptor(FirstInterceptor())
                    .addInterceptor(SecondInterceptor())
                    .addInterceptor(ChuckerInterceptor.Builder(this@MyApplication).build())
                    .build())
                .serverUrl("https://countries.trevorblades.com/graphql")
                .normalizedCache(MemoryCacheFactory())
                .build()
```

### Logs

The runtime exception.
```
java.lang.RuntimeException: Cannot find a CompiledField for entry: {code: null}, __typename = null, key = country({"code":"CA"})
        at com.apollographql.apollo3.cache.normalized.api.internal.Normalizer.buildRecord(Normalizer.kt:58)
        at com.apollographql.apollo3.cache.normalized.api.internal.Normalizer.replaceObjects(Normalizer.kt:145)
        at com.apollographql.apollo3.cache.normalized.api.internal.Normalizer.buildRecord(Normalizer.kt:81)
        at com.apollographql.apollo3.cache.normalized.api.internal.Normalizer.normalize(Normalizer.kt:29)
        at com.apollographql.apollo3.cache.normalized.api.OperationCacheExtensionsKt.normalize(OperationCacheExtensions.kt:31)
        at com.apollographql.apollo3.cache.normalized.api.OperationCacheExtensionsKt.normalize(OperationCacheExtensions.kt:18)
        at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore$writeOperationWithRecords$2.invoke(DefaultApolloStore.kt:182)
        at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore$writeOperationWithRecords$2.invoke(DefaultApolloStore.kt:181)
        at com.apollographql.apollo3.cache.normalized.internal.Lock.write(Lock.kt:18)
        at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore.writeOperationWithRecords(DefaultApolloStore.kt:181)
        at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore.writeOperation(DefaultApolloStore.kt:139)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$maybeWriteToCache$2.invokeSuspend(ApolloCacheInterceptor.kt:79)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$maybeWriteToCache$2.invoke(Unknown Source:8)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$maybeWriteToCache$2.invoke(Unknown Source:2)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor.maybeAsync(ApolloCacheInterceptor.kt:53)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor.maybeWriteToCache(ApolloCacheInterceptor.kt:73)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor.maybeWriteToCache$default(ApolloCacheInterceptor.kt:60)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$readFromNetwork$2.invokeSuspend(ApolloCacheInterceptor.kt:260)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$readFromNetwork$2.invoke(Unknown Source:8)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$readFromNetwork$2.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:223)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:87)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:66)
        at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invokeSuspend(HttpNetworkTransport.kt:82)
        at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invoke(Unknown Source:8)
        at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:195)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collect$suspendImpl(ChannelFlow.kt:167)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collect(Unknown Source:0)
        at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1.collect(SafeCollector.common.kt:113)
E/AndroidRuntime:     at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$readFromNetwork$$inlined$map$1.collect(SafeCollector.common.kt:113)
        at kotlinx.coroutines.flow.FlowKt__CollectKt.emitAll(Collect.kt:109)
        at kotlinx.coroutines.flow.FlowKt.emitAll(Unknown Source:1)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$interceptQuery$1.invokeSuspend(ApolloCacheInterceptor.kt:196)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$interceptQuery$1.invoke(Unknown Source:8)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$interceptQuery$1.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:195)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collect$suspendImpl(ChannelFlow.kt:167)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collect(Unknown Source:0)
        at kotlinx.coroutines.flow.FlowKt__ErrorsKt.catchImpl(Errors.kt:156)
        at kotlinx.coroutines.flow.FlowKt.catchImpl(Unknown Source:1)
        at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:113)
        at com.apollographql.apollo3.cache.normalized.FetchPolicyInterceptors$CacheFirstInterceptor$1$intercept$1$invokeSuspend$$inlined$map$1.collect(SafeCollector.common.kt:113)
        at kotlinx.coroutines.flow.FlowKt__CollectKt.emitAll(Collect.kt:109)
        at kotlinx.coroutines.flow.FlowKt.emitAll(Unknown Source:1)
        at com.apollographql.apollo3.cache.normalized.FetchPolicyInterceptors$CacheFirstInterceptor$1$intercept$1.invokeSuspend(FetchPolicyInterceptors.kt:88)
        at com.apollographql.apollo3.cache.normalized.FetchPolicyInterceptors$CacheFirstInterceptor$1$intercept$1.invoke(Unknown Source:8)
        at com.apollographql.apollo3.cache.normalized.FetchPolicyInterceptors$CacheFirstInterceptor$1$intercept$1.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at kotlinx.coroutines.flow.FlowKt__ReduceKt.single(Reduce.kt:57)
        at kotlinx.coroutines.flow.FlowKt.single(Unknown Source:1)
        at com.apollographql.apollo3.ApolloCall.execute(ApolloCall.kt:102)
        at com.example.gqltutorial.GraphQLRepoImpl$getData$2.invokeSuspend(GraphQLRepoImpl.kt:25)
        at com.example.gqltutorial.GraphQLRepoImpl$getData$2.invoke(Unknown Source:8)
        at com.example.gqltutorial.GraphQLRepoImpl$getData$2.invoke(Unknown Source:4)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at com.example.gqltutorial.GraphQLRepoImpl.getData(GraphQLRepoImpl.kt:24)
        at com.example.gqltutorial.DataSource$getData$2.invokeSuspend(DataSource.kt:20)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@43b720f, Dispatchers.Main]
```

**Comment by martinbonnin** [comment]
Many thanks for opening this an the reproducer! I'll push a fix for this. In the meantime, this shouldn't happen if you use a variable instead of `false`:

```graphql
query getCountry($code:ID!, skip: Boolean! = true) {
  country(code:$code) {
    code @skip(if:skip)
    name
  }
}
```
