### ISSUE TITLE
IllegalStateException: Check failed. when using @include with a default value inside a fragment

### ISSUE THREAD

**Issue by kyum1n** [apollographql/apollo-kotlin#4818]
### Version

3.7.5

### Summary

Executing a query with @include crashes with an ISE if the `@include` boolean uses its default when normalized cache is enabled.

### Steps to reproduce the behavior

Based on the Rocket Reserver sample project but with normalized cache enabled, the following query will fail when `$foo` is absent.
```graphql
query Foo(
    $foo: Boolean! = false
) {
    ... Bar
}

fragment Bar on Query {
    launches @include(if: $foo) {
        cursor
    }
}
```
```kotlin
apolloClient.query(FooQuery(Optional.absent())).execute()
```

Works fine in 3.7.4 or if there is no fragment involved, i.e.:
```graphql
query Foo(
    $foo: Boolean! = false
) {
    launches @include(if: $foo) {
        cursor
    }
}
```

Moving the `@include` outside of the fragment leads to a different crash, but that sounds like #4784:
```graphql
query Foo(
    $foo: Boolean! = false
) {
    ... Bar @include(if: $foo)
}

fragment Bar on Query {
    launches {
        cursor
    }
}
```

### Logs

include inside fragment:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.rocketreserver, PID: 14545
    java.lang.IllegalStateException: Check failed.
        at com.apollographql.apollo3.cache.normalized.api.internal.Normalizer.replaceObjects(Normalizer.kt:121)
        at com.apollographql.apollo3.cache.normalized.api.internal.Normalizer.buildRecord(Normalizer.kt:81)
        at com.apollographql.apollo3.cache.normalized.api.internal.Normalizer.normalize(Normalizer.kt:29)
        at com.apollographql.apollo3.cache.normalized.api.OperationCacheExtensionsKt.normalize(OperationCacheExtensions.kt:31)
        at com.apollographql.apollo3.cache.normalized.api.OperationCacheExtensionsKt.normalize(OperationCacheExtensions.kt:18)
        at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore$writeOperationWithRecords$2.invoke(DefaultApolloStore.kt:182)
        at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore$writeOperationWithRecords$2.invoke(DefaultApolloStore.kt:181)
        at com.apollographql.apollo3.cache.normalized.internal.Lock.write(Lock.kt:18)
        at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore.writeOperationWithRecords(DefaultApolloStore.kt:181)
        at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore.writeOperation(DefaultApolloStore.kt:139)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$maybeWriteToCache$2.invokeSuspend(ApolloCacheInterceptor.kt:79)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$maybeWriteToCache$2.invoke(Unknown Source:8)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$maybeWriteToCache$2.invoke(Unknown Source:2)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor.maybeAsync(ApolloCacheInterceptor.kt:53)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor.maybeWriteToCache(ApolloCacheInterceptor.kt:73)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor.maybeWriteToCache$default(ApolloCacheInterceptor.kt:60)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$readFromNetwork$2.invokeSuspend(ApolloCacheInterceptor.kt:260)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$readFromNetwork$2.invoke(Unknown Source:8)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$readFromNetwork$2.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:223)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:87)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:66)
        at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invokeSuspend(HttpNetworkTransport.kt:83)
        at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invoke(Unknown Source:8)
        at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:195)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collect$suspendImpl(ChannelFlow.kt:167)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collect(Unknown Source:0)
        at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1.collect(SafeCollector.common.kt:113)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$readFromNetwork$$inlined$map$1.collect(SafeCollector.common.kt:113)
        at kotlinx.coroutines.flow.FlowKt__CollectKt.emitAll(Collect.kt:109)
        at kotlinx.coroutines.flow.FlowKt.emitAll(Unknown Source:1)
E/AndroidRuntime:     at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$interceptQuery$1.invokeSuspend(ApolloCacheInterceptor.kt:196)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$interceptQuery$1.invoke(Unknown Source:8)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$interceptQuery$1.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:195)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(Unknown Source:0)
        at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@a4e379b, androidx.compose.runtime.BroadcastFrameClock@5211738, StandaloneCoroutine{Cancelling}@17a2311, AndroidUiDispatcher@7d64c76]
```
include outside fragment
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.rocketreserver, PID: 16120
    com.apollographql.apollo3.exception.ApolloCompositeException: multiple exceptions happened
        at com.apollographql.apollo3.cache.normalized.FetchPolicyInterceptors$CacheFirstInterceptor$1$intercept$1.invokeSuspend(FetchPolicyInterceptors.kt:100)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
    	Suppressed: com.apollographql.apollo3.exception.CacheMissException: Object 'QUERY_ROOT' has no field named '__typename'
        at com.apollographql.apollo3.cache.normalized.api.DefaultCacheResolver.resolveField(CacheResolver.kt:97)
        at com.apollographql.apollo3.cache.normalized.api.FieldPolicyCacheResolver.resolveField(CacheResolver.kt:188)
        at com.apollographql.apollo3.cache.normalized.api.internal.CacheBatchReader.toMap(CacheBatchReader.kt:115)
        at com.apollographql.apollo3.cache.normalized.api.OperationCacheExtensionsKt.readInternal(OperationCacheExtensions.kt:76)
        at com.apollographql.apollo3.cache.normalized.api.OperationCacheExtensionsKt.readDataFromCache(OperationCacheExtensions.kt:39)
        at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore$readOperation$2.invoke(DefaultApolloStore.kt:99)
        at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore$readOperation$2.invoke(DefaultApolloStore.kt:98)
        at com.apollographql.apollo3.cache.normalized.internal.Lock.read(Lock.kt:12)
        at com.apollographql.apollo3.cache.normalized.internal.DefaultApolloStore.readOperation(DefaultApolloStore.kt:98)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor.readFromCache(ApolloCacheInterceptor.kt:209)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor.access$readFromCache(ApolloCacheInterceptor.kt:39)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$interceptQuery$1.invokeSuspend(ApolloCacheInterceptor.kt:194)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$interceptQuery$1.invoke(Unknown Source:8)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$interceptQuery$1.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:195)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(Unknown Source:0)
        at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime:     at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: com.apollographql.apollo3.exception.ApolloParseException: Failed to parse GraphQL http network response
        at com.apollographql.apollo3.network.http.HttpNetworkTransport$Companion.wrapThrowableIfNeeded(HttpNetworkTransport.kt:241)
        at com.apollographql.apollo3.network.http.HttpNetworkTransport$Companion.access$wrapThrowableIfNeeded(HttpNetworkTransport.kt:235)
        at com.apollographql.apollo3.network.http.HttpNetworkTransport.singleResponse(HttpNetworkTransport.kt:102)
        at com.apollographql.apollo3.network.http.HttpNetworkTransport.access$singleResponse(HttpNetworkTransport.kt:30)
        at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invokeSuspend(HttpNetworkTransport.kt:84)
        at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invoke(Unknown Source:8)
        at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:195)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collect$suspendImpl(ChannelFlow.kt:167)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collect(Unknown Source:0)
        at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1.collect(SafeCollector.common.kt:113)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$readFromNetwork$$inlined$map$1.collect(SafeCollector.common.kt:113)
        at kotlinx.coroutines.flow.FlowKt__CollectKt.emitAll(Collect.kt:109)
        at kotlinx.coroutines.flow.FlowKt.emitAll(Unknown Source:1)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$interceptQuery$1.invokeSuspend(ApolloCacheInterceptor.kt:196)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$interceptQuery$1.invoke(Unknown Source:8)
        at com.apollographql.apollo3.cache.normalized.internal.ApolloCacheInterceptor$interceptQuery$1.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:195)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(Unknown Source:0)
        at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
     Caused by: java.lang.NullPointerException
        at com.example.rocketreserver.fragment.BarImpl_ResponseAdapter$Bar.fromJson(BarImpl_ResponseAdapter.kt:34)
E/AndroidRuntime:     at com.example.rocketreserver.adapter.FooQuery_ResponseAdapter$Data.fromJson(FooQuery_ResponseAdapter.kt:39)
        at com.example.rocketreserver.adapter.FooQuery_ResponseAdapter$Data.fromJson(FooQuery_ResponseAdapter.kt:22)
        at com.apollographql.apollo3.api.ObjectAdapter.fromJson(Adapters.kt:292)
        at com.apollographql.apollo3.api.NullableAdapter.fromJson(Adapters.kt:57)
        at com.apollographql.apollo3.api.internal.ResponseParser.parse(ResponseParser.kt:33)
        at com.apollographql.apollo3.api.Operations.parseJsonResponse(Operations.kt:63)
        at com.apollographql.apollo3.network.http.HttpNetworkTransport.singleResponse(HttpNetworkTransport.kt:97)
        		... 30 more
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@aceb277, androidx.compose.runtime.BroadcastFrameClock@36c6ee4, StandaloneCoroutine{Cancelling}@74cdf4d, AndroidUiDispatcher@a52ba02]
    Caused by: [CIRCULAR REFERENCE: com.apollographql.apollo3.exception.ApolloParseException: Failed to parse GraphQL http network response]
```

**Comment by kyum1n** [comment]
just tried with 3.7.6-SNAPSHOT:
It fixes the 2nd case where the `@include` is next to the fragment.
But I still get the ISE when the `@include` is inside the fragment.

**Comment by martinbonnin** [comment]
The issue is that the code cannot lookup the default value from the variable alone in 

```kotlin
fragment Bar on Query {
    # No need to get a default value here
    launches @include(if: $foo) {
        cursor
    }
}
```

Still looking into this. In the meantime, the workaround is to remove the default value and pass explicit `true` or `false` in your operations.

**Comment by martinbonnin** [comment]
The new snapshot is building [here](https://github.com/apollographql/apollo-kotlin/actions/runs/4576878729). Should be available in a few minutes.

**Comment by kyum1n** [comment]
Seems like the snapshot build never made it, but I just checked against the 3.8.0 release and it seems to be working now. 
Closing this, thank you.

**Comment by martinbonnin** [comment]
Thanks for the update!
