### ISSUE TITLE
[3.7.4~] App crashes when using ApolloInterceptor with autoPersistedQueries()

### ISSUE THREAD

**Issue by omtians9425** [apollographql/apollo-kotlin#4888]
Below stack trace and debugging by the tutorial app are inappropriate, so let me fix (Please wait) 🙇 

### Version

3.7.4~ (Confirmed it also occurs in 3.8.0)

### Summary

In official tutorial app, the following code makes app crash. [Ref](https://github.com/apollographql/apollo-kotlin-tutorial/pull/45/files)

```kt
val apolloClient = ApolloClient.Builder()
    .serverUrl("https://apollo-fullstack-tutorial.herokuapp.com/graphql")
    .webSocketServerUrl("wss://apollo-fullstack-tutorial.herokuapp.com/graphql")
    .okHttpClient(
        OkHttpClient.Builder()
            .addInterceptor(AuthorizationInterceptor())
            .build()
    )
    // Add ApolloInterceptor (here it just proceeds the request for simplicity)
    .addInterceptor(object : ApolloInterceptor {
        override fun <D : Operation.Data> intercept(request: ApolloRequest<D>, chain: ApolloInterceptorChain): Flow<ApolloResponse<D>> {
            return chain.proceed(request)
        }
    })
    // Enable APQ
    .autoPersistedQueries()
    .webSocketReopenWhen { throwable, attempt ->
        Log.d("Apollo", "WebSocket got disconnected, reopening after a delay", throwable)
        delay(attempt * 1000)
        true
    }

    .build()
```

This tutorial app doesn't seem to support APQ but it also occurs in my business app which supports APQ and worked properly before 3.7.4.

### Steps to reproduce the behavior

https://github.com/apollographql/apollo-kotlin-tutorial/pull/45

### Logs

Full stacktrace:
```
com.example.rocketreserver           E  FATAL EXCEPTION: main
      Process: com.example.rocketreserver, PID: 4825
      com.apollographql.apollo3.exception.SubscriptionOperationException: Operation error TripsBooked
       at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$$inlined$map$1$2.emit(Emitters.kt:245)
       at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
       at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
       at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:87)
       at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:66)
       at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$3.invokeSuspend(WebSocketNetworkTransport.kt:282)
       at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$3.invoke(Unknown Source:13)
       at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$3.invoke(Unknown Source:6)
       at com.apollographql.apollo3.internal.FlowsKt$transformWhile$1$invokeSuspend$$inlined$collectWhile$1.emit(flows.kt:53)
       at com.apollographql.apollo3.internal.FlowsKt$transformWhile$1$invokeSuspend$$inlined$collectWhile$2.emit(flows.kt:38)
       at com.apollographql.apollo3.network.ws.WebSocketNetworkTransport$execute$$inlined$filter$1$2.emit(Emitters.kt:223)
       at kotlinx.coroutines.flow.SubscribedFlowCollector.emit(Unknown Source:2)
       at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:383)
       at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
       Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@10fc8d4, androidx.compose.runtime.BroadcastFrameClock@ae14a7d, StandaloneCoroutine{Cancelling}@4cfd72, AndroidUiDispatcher@e2cd5c3]
```

**Comment by omtians9425** [comment]
It turned out that the above stack trace and debugging by the tutorial app are nothing to do with real problem in my business app, so let me investigate more and recreate Issue 🙇
