### ISSUE TITLE
[3.7.4~] `autoPersistedQueries(hashedQueries = HttpMethod.Get)` no longer fallback to HttpMethod.POST

### ISSUE THREAD

**Issue by omtians9425** [apollographql/apollo-kotlin#4906]
### Version

3.4.0~ (Confirmed it also occurs in 3.8.0)

### Summary

Based on [your advice](https://github.com/apollographql/apollo-kotlin/issues/4032#issuecomment-1101273154) given earlier,  we use the following custom interceptor with `autoPersistedQueries`

This interceptor will fall back the requests to HttpMethod.POST if the query parameter (URL) is too long.

```kt
val apolloClient: ApolloClient = ApolloClient.Builder()
      .autoPersistedQueries(httpMethodForHashedQueries = HttpMethod.Get) // 👈 APQ
      .addInterceptor(object : ApolloInterceptor { // 👈 custom interceptor
          // Since the server doesn't returns response for GET requests with a URL length (http request line, to be precise) of 5kb or more.
          // This interceptor converts the http method of the request to POST if the length is 4kb or more.

          // http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers
          // The default value is 8kb, but we confirmed that connection close occurs around 5kb in the environment
          private val postFallbackURLLengthThreshold = 4000

          private val delegate = DefaultHttpRequestComposer(serverUrl)

          override fun <D : Operation.Data> intercept(
              request: ApolloRequest<D>,
              chain: ApolloInterceptorChain
          ): Flow<ApolloResponse<D>> {
              val httpRequest = delegate.compose(request)
              return if (httpRequest.method == HttpMethod.Get && postFallbackURLLengthThreshold < httpRequest.url.toByteArray().size) {
                  chain.proceed(request.newBuilder().httpMethod(HttpMethod.Post).build())  //  👈 fallback to POST
              } else {
                  chain.proceed(request)
              }
          }
      })
      .okHttpClient(okHttpClient)
      .addInterceptor(...)
      .addInterceptor(...)
      .serverUrl(serverUrl)
      .build()
```

However, due to [this change](https://github.com/apollographql/apollo-kotlin/pull/4628) from 3.7.4, APQ interceptor will run as the last interceptor. So even though the request fell back to POST finally it ended up being a GET, resulting in the "URL too long" error.

Is there any workaround to keep the previous behavior?
We want to avoid using `.autoPersistedQueries(httpMethodForHashedQueries = HttpMethod.Post)` because we want to use HTTP cache 

And, from my research, reverting this PR on tag v.3.7.4 fixes this issue: https://github.com/apollographql/apollo-kotlin/pull/4628

### Steps to reproduce the behavior

Run the above code with very long query parameters with v3.7.4

### Logs

```
E  com.apollographql.apollo3.exception.ApolloNetworkException: Failed to execute GraphQL http network request
		at com.apollographql.apollo3.network.http.DefaultHttpEngine.execute(OkHttpEngine.kt:82)
		at com.apollographql.apollo3.network.http.HttpNetworkTransport$EngineInterceptor.intercept(HttpNetworkTransport.kt:150)
		at com.apollographql.apollo3.network.http.DefaultHttpInterceptorChain.proceed(HttpInterceptor.kt:22)
		at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invokeSuspend(HttpNetworkTransport.kt:58)
		at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invoke(Unknown Source:8)
		at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invoke(Unknown Source:4)
		at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
		at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
		at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:195)
		at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157)
		at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(Unknown Source:0)
		at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
		at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
		at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
		at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
		at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:148)
		at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
		at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
		at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at sample.app.HogeInterceptor.intercept(HogeInterceptor.kt:10)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at sample.app.FugaInterceptor.intercept(FugaInterceptor.kt:10)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
		at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
		at com.apollographql.apollo3.network.http.DefaultHttpEngine.execute(OkHttpEngine.kt:74)
		at com.apollographql.apollo3.network.http.HttpNetworkTransport$EngineInterceptor.intercept(HttpNetworkTransport.kt:150) 
		at com.apollographql.apollo3.network.http.DefaultHttpInterceptorChain.proceed(HttpInterceptor.kt:22) 
		at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invokeSuspend(HttpNetworkTransport.kt:58) 
		at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invoke(Unknown Source:8) 
		at com.apollographql.apollo3.network.http.HttpNetworkTransport$execute$1.invoke(Unknown Source:4) 
		at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61) 
		at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230) 
		at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:195) 
		at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157) 
		at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(Unknown Source:0) 
		at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60) 
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
		at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) 
		at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) 
		at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) 
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) 
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) 
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) 
Suppressed: okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
... 39 more
```

**Comment by BoD** [comment]
Hi! Have you tried using a custom `HttpRequestComposer` like [here](https://github.com/apollographql/apollo-kotlin/issues/4032#issuecomment-1098988405) instead of an Interceptor?

**Comment by omtians9425** [comment]
@BoD Thank you!!
We want to inject a custom OkHttpClient into ApolloClient, so `HttpRequestComposer` is unavailable due to [here](https://github.com/apollographql/apollo-kotlin/blob/main/libraries/apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo3/ApolloClient.kt#L502-L504)

**Comment by omtians9425** [comment]
@BoD Thanks you, `httpEngine()` worked!!
