### ISSUE TITLE
IllegalStateException when writing coordinates to JSON

### ISSUE THREAD

**Issue by Orbyt** [apollographql/apollo-kotlin#5010]
### Version

3.7.4

### Summary

`IllegalStateException` occurs when executing query after migration to Apollo 3.

See log section for stacktrace.

The piece of input referenced (`{"location":{"latitude":31.9496748,"longitude":-108.8067046}}`) is definately valid JSON. The error gives no indication as to why that input cannot be written to JSON. The input code for the query has not really changed, with the exception of changes related to the use of `Optional`s as required by Apollo 3. The stack trace seems to reference generated `*_InputAdapter` classes in the project.

What might be the issue?

### Steps to reproduce the behavior

N/A

### Logs

```
java.lang.IllegalStateException: Cannot write {"location":{"latitude":31.9496748,"longitude":-108.8067046}} to Json
 	at com.apollographql.apollo3.api.json.-JsonWriters.writeAny(JsonWriters.kt:40)
 	at com.apollographql.apollo3.api.Adapters$AnyAdapter$1.toJson(Adapters.kt:203)
 	at com.apollographql.apollo3.api.Adapters$AnyAdapter$1.toJson(Adapters.kt:211)
 	at com.apollographql.apollo3.api.NullableAdapter.toJson(Adapters.kt:65)
 	at com.apollographql.apollo3.api.PresentAdapter.toJson(Adapters.kt:92)
 	at com.example.example.type.adapter.ProductRecommendationQuestionInput_InputAdapter.toJson(ProductRecommendationQuestionInput_InputAdapter.kt:37)
 	at com.example.example.type.adapter.ProductRecommendationQuestionInput_InputAdapter.toJson(ProductRecommendationQuestionInput_InputAdapter.kt:21)
 	at com.apollographql.apollo3.api.ObjectAdapter.toJson(Adapters.kt:313)
 	at com.apollographql.apollo3.api.NullableAdapter.toJson(Adapters.kt:65)
 	at com.apollographql.apollo3.api.ListAdapter.toJson(Adapters.kt:39)
 	at com.apollographql.apollo3.api.ListAdapter.toJson(Adapters.kt:25)
 	at com.apollographql.apollo3.api.NullableAdapter.toJson(Adapters.kt:65)
 	at com.example.example.adapter.ProductRecommendationQuery_VariablesAdapter.toJson(ProductRecommendationQuery_VariablesAdapter.kt:30)
 	at com.example.example.ProductRecommendationQuery.serializeVariables(ProductRecommendationQuery.kt:40)
 	at com.apollographql.apollo3.api.http.DefaultHttpRequestComposer$Companion.composePostParams(DefaultHttpRequestComposer.kt:116)
 	at com.apollographql.apollo3.api.http.DefaultHttpRequestComposer$Companion.access$composePostParams(DefaultHttpRequestComposer.kt:68)
 	at com.apollographql.apollo3.api.http.DefaultHttpRequestComposer$Companion.buildPostBody(DefaultHttpRequestComposer.kt:215)
 	at com.apollographql.apollo3.api.http.DefaultHttpRequestComposer.compose(DefaultHttpRequestComposer.kt:62)
 	at com.apollographql.apollo3.network.http.HttpNetworkTransport.execute(HttpNetworkTransport.kt:43)
 	at com.apollographql.apollo3.interceptor.NetworkInterceptor.intercept(NetworkInterceptor.kt:22)
 	at com.apollographql.apollo3.interceptor.DefaultInterceptorChain.proceed(ApolloInterceptor.kt:23)
 	at com.apollographql.apollo3.cache.http.HttpCache$httpCache$2.intercept(HttpCacheExtensions.kt:106)
 	at com.apollographql.apollo3.interceptor.DefaultInterceptorChain.proceed(ApolloInterceptor.kt:23)
 	at com.apollographql.apollo3.ApolloClient.executeAsFlow(ApolloClient.kt:178)
 	at com.apollographql.apollo3.ApolloCall.toFlow(ApolloCall.kt:97)
 	at com.apollographql.apollo3.ApolloCall.execute(ApolloCall.kt:106)
 	at com.example.example.data.remote.RemoteRepoImpl.getProductRecommendation(RemoteRepoImpl.kt:1333)
```

**Comment by martinbonnin** [comment]
Hi 👋 
Thanks for sending this!

Do you know what is the runtime type of  `{"location":{"latitude":31.9496748,"longitude":-108.8067046}}`. It looks like it's a custom scalar mapped to `Any` (default behaviour). In that case, apollo3 supports `Map`, `List`, `String`, `Boolean`, `Int`, `Double`, `JsonNumber` and `Long`. Anything else will throw the error above (even if `.toString()` is valid json)

**Comment by martinbonnin** [comment]
Gotcha. That's interesting I wonder how come this worked in version 2. In all cases, you should be able to convert to a `Map` with something like:

```kotlin
fun Any.convert(): Any {
  return when (this) {
    is JSONObject -> this.keys().toList().map {
      it to this.get(it).convert()
    }.toMap()
    is JSONArray -> this.toList().map { it.convert() }
    is Long, is Int, is String, is Boolean, null -> this
    else -> error("Cannot convert $this of class ${this.javaClass} to JSON")
  }
}
```

and then call 

```kotlin
jsonObject.convert()
```

**Comment by martinbonnin** [comment]
Looking at the [2.x code](https://github.com/apollographql/apollo-kotlin/blob/a31a58cd1ce2ab1a81c88ebdbb53f270b6d0353d/apollo-api/src/commonMain/kotlin/com/apollographql/apollo/api/CustomTypeValue.kt#L106), it was converting everything to a String. So your `JSONObject` was actually sent as a "String" to your server. If you want to keep the same behaviour, call `.toString()` at the call site:

```kotlin
val query = MyQuery(jsonObject.toString())
```

or [define your own adapter](https://www.apollographql.com/docs/kotlin/essentials/custom-scalars/):

```kotlin
object adapter: Adapter<JSONObject> {
  override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters): JSONObject {
    return JSONObject(reader.nextString())
  }

  override fun toJson(writer: JsonWriter, customScalarAdapters: CustomScalarAdapters, value: JSONObject) {
    writer.value(value.toString())
  }
}
```

**Comment by martinbonnin** [comment]
> the input type as defined by the query is a List<ProductRecommendationQuestionInput?>?

Indeed, I just edited the comment above. I think something like so would work:

```kotlin
val query = ProductRecommendationQuery(
  listOf(
    ProductRecommendationQuestionInput(
      params = Optional.Present(jsonObject.toString())
    )
  )
)
```

**Comment by martinbonnin** [comment]
Thanks for sending this. Turns our you had some specific handling to convert your `JSONObject` to a `Map` (`jsonObjectToMap(value)`). The 3.x equivalent would be something like so:

```kotlin
class AnyHashAdapter : Adapter<Any> {
  override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters): Any {
    return when(val value = AnyAdapter.fromJson(reader, customScalarAdapters)) {
      is Map<*,*> -> JSONObject(value)
      else -> value.toString()
    }
  }

  override fun toJson(writer: JsonWriter, customScalarAdapters: CustomScalarAdapters, value: Any) {
    when (value) {
      is JSONObject -> writer.writeAny(jsonObjectToMap(value))
      else -> writer.value(value.toString())
    }
  }
}
```

**Comment by martinbonnin** [comment]
> The query, query inputs and relevant adapter were already posted. Is there a particular piece of code that would provide more details? I am unsure as to what else is relevant.

Gotcha. Sorry I was confused getting all the pieces together. More comments below

> why the Apollo SDK isn't simply able to handle a JSONObject when attempting to write JSON

`JSONObject` is coming from an external dependency of your project like typically [org.json](https://stleary.github.io/JSON-java/org/json/JSONObject.html). Apollo Kotlin knows nothing about `org.json` so it can't deal with it. Apollo Koltin cannot support all JSON libraries out there like `org.json` but also `Gson`, `Jackson`, moshi, etc.. It only knows about Kotlin StdLib. This is why you had `AnyHashAdapter` in the 2.x codebase. `AnyHashAdapter` converts from `org.json.JSONObject` (that Apollo Kotlin doesn't know about) to `kotlin.collections.Map` (that Apollo Kotlin knows about because it's in the Kotlin standard library)

> why the input object seems to only get to adapters if converted to a String.

Apologies for steering this discussion to Strings, this was a red herring. I missed that you previously had a `CustomTypeAdapter`. This is the part that needs to be ported to Apollo Kotlin 3

> The adapter that I posted was surely created to handle Apollo 2 edge cases, so if it's not needed or been deprecated please let me know.

It's still needed. The adapter converts (adapts) from `JSONObject` in your project to `Map` (in Apollo Kotlin). It was named `CustomTypeAdapter` in Apollo 2 and it's now named just `Adapter`. I believe something like below should help?

```kotlin
class AnyHashAdapter : Adapter<Any> {
  override fun toJson(writer: JsonWriter, customScalarAdapters: CustomScalarAdapters, value: Any) {
    when (value) {
      // The jsonObejctToMap here is the important part and will convert from JSONObject to Map
      is JSONObject -> writer.writeAny(jsonObjectToMap(value))
      else -> writer.value(value.toString())
    }
  }  
  
  override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters): Any {
    return when(val value = reader.readAny()) {
      is Map<*,*> -> JSONObject(value)
      else -> value.toString()
    }
  }
}
```

> I certainly appreciate your help with this matter. Thank you!

Same, thanks for posting all the details! I hope the above makes a bit more sense? Let me know otherwise!

**Comment by martinbonnin** [comment]
That's interesting. Maybe the different input fields are of different types? Can you share your schema? If they are of different types, you'll need to register the adapter for each custom GraphQL scalar that you want to handle (See https://www.apollographql.com/docs/kotlin/essentials/custom-scalars/).

**Comment by martinbonnin** [comment]
Sorry I meant the GraphQL types in your schema. Each GraphQL type is mapped to a Kotlin type depending your Gradle configuration (see https://www.apollographql.com/docs/kotlin/essentials/custom-scalars/). Then depending the adapters you register, they will be called to "adapt" these types. So in order to troubleshoot all of this, you'll need to look at your schema, Gradle configuration and registered adapters. Sorry I know that's a lot of things to look at but there's no real way around this. If you can upload a reproducer somewhere that might be easier.

**Comment by martinbonnin** [comment]
Hey @Orbyt did you manage to make it work? Did you see anything in your schema?

**Comment by martinbonnin** [comment]
```
java.lang.ClassCastException: org.json.JSONObject cannot be cast to java.util.Map
	at com.example.example.data.remote.adapters.HashAdapter.toJson(HashAdapter.kt:14)
```

Sounds like this is progress. Can you share your implementation of `HashAdapter`?

**Comment by martinbonnin** [comment]
Hi @Orbyt did you end up finding a solution to this issue? Anything else we can help with here?

**Comment by martinbonnin** [comment]
I'm going to assume you found a solution. Feel free to comment and we will reopen.

**Comment by milgner** [comment]
It seems like this is still a problem. While trying to work with an API that uses `UUID` a lot, I used `addCustomScalarAdapter` to add my adapter implementation for `java.util.UUID` - only to discover that the `AnyAdapter` implementation [completely ignores the `customScalarAdapters` argument](https://github.com/apollographql/apollo-kotlin/blob/5a9edd48d9524fe18080a2d0d3161e56a2a24927/libraries/apollo-api/src/commonMain/kotlin/com/apollographql/apollo/api/Adapters.kt#L202) that's passed in.

Is there any reason for that? It seems to me like `customScalarAdapters` should be used if possible. I'm open to creating a PR, but I don't want to put any work into this.

**Comment by martinbonnin** [comment]
@milgner can you open a separate issue for your use case? We can dive into the specifics there.
