### ISSUE TITLE
Building with Apollo into a project with uuid 0.7.0+ fails with cryptic error

### ISSUE THREAD

**Issue by baconz** [apollographql/apollo-kotlin#5046]
### Description

This probably belongs in youtrack as a compiler bug, but thought I would post here in case somebody else stumbles across this and is as confused as I was. I tried to upgrade https://github.com/benasher44/uuid to 0.7.0 in my project, and suddenly I got the cryptic stacktrace pasted below. I made a sample project and was able to repro by including Apollo and compiling a JS target. It looks like there is a transitive dependency issue, and, in fact, it looks like Apollo is intentionally pinned to `uuid:0.6.0` because of metadata issues (https://github.com/apollographql/apollo-kotlin/blob/main/gradle/libraries.toml#L155). I'm sticking to 0.6.0 for now to mirror Apollo. It would be nice if the compiler threw a clearer error!

```
e: Could not find "uuid" in [/Users/xxxx/Library/Application Support/kotlin/daemon]
e: java.lang.IllegalStateException: FATAL ERROR: Could not find "uuid" in [/Users/xxxx/Library/Application Support/kotlin/daemon]
        at org.jetbrains.kotlin.ir.backend.js.KlibKt$resolverLogger$1.fatal(klib.kt:111)
        at org.jetbrains.kotlin.library.KotlinLibrarySearchPathResolver.resolve(SearchPathResolver.kt:171)
        at org.jetbrains.kotlin.library.SearchPathResolver.resolve$default(SearchPathResolver.kt:20)
        at org.jetbrains.kotlin.library.SearchPathResolverKt.resolve(SearchPathResolver.kt:29)
        at org.jetbrains.kotlin.library.metadata.resolver.impl.KotlinLibraryResolverImpl$resolveDependencies$2$2.invoke(KotlinLibraryResolverImpl.kt:122)
        at org.jetbrains.kotlin.library.metadata.resolver.impl.KotlinLibraryResolverImpl$resolveDependencies$2$2.invoke(KotlinLibraryResolverImpl.kt:122)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
        at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:817)
        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:808)
        at org.jetbrains.kotlin.library.metadata.resolver.impl.KotlinLibraryResolverImpl.resolveDependencies(KotlinLibraryResolverImpl.kt:135)
        at org.jetbrains.kotlin.library.metadata.resolver.impl.KotlinLibraryResolverImpl.resolveWithDependencies(KotlinLibraryResolverImpl.kt:44)
        at org.jetbrains.kotlin.ir.backend.js.JsLibraryResolverKt.jsResolveLibraries(JsLibraryResolver.kt:51)
        at org.jetbrains.kotlin.ir.backend.js.ModulesStructure.<init>(klib.kt:476)
        at org.jetbrains.kotlin.ir.backend.js.PrepareAnalyzedSourceModuleKt.prepareAnalyzedSourceModule(prepareAnalyzedSourceModule.kt:26)
        at org.jetbrains.kotlin.ir.backend.js.PrepareAnalyzedSourceModuleKt.prepareAnalyzedSourceModule$default(prepareAnalyzedSourceModule.kt:16)
        at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.processSourceModule(K2JsIrCompiler.kt:435)
        at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:295)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:181)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:72)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:100)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:46)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
        at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:213)
        at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:84)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:486)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:409)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:290)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:112)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile$default(IncrementalCompilerRunner.kt:94)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execJsIncrementalCompiler(CompileServiceImpl.kt:567)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execJsIncrementalCompiler(CompileServiceImpl.kt:101)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1678)
        at jdk.internal.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
        ```

**Comment by martinbonnin** [comment]
Thanks!

If you scroll up these logs, I _think_ you should find something like "`uuid:$something` not considered because mismatch" (wording completely made up by me but I remember the compiler "skips" some artifacts if the metadata versions do not match. 

That'd be an argument for bumping our `languageVersion`. Right now, [we're still with languageVersion=1.5](https://github.com/apollographql/apollo-kotlin/blob/a877fb6452e07c51147903df0ff954d6e272e8bc/build-logic/src/main/kotlin/CompilerOptions.kt#L27). This means you can use Apollo Kotlin on the JVM back to Kotlin 1.4. This was ~3 years ago now so it might make sense to upgrade. 

I'm curious the root cause of this error though. Kotlin in general is very backward compatible so as long as you're using the latest compiler version on your end it _should_ be able to read artifact produced by most of the previous versions. Do you have the reproducer somewhere public by any chance?

**Comment by baconz** [comment]
I think I might not have been passing the right flags to get that error? I looked with `--debug` and couldn't find anything.

I put up the reproducer here if you'd like to check it out: https://github.com/baconz/testuuid

**Comment by martinbonnin** [comment]
> I think I might not have been passing the right flags to get that error?

Nevermind, I can't have it either, looks like it's a different problem.

> I put up the reproducer here if you'd like to check it out: https://github.com/baconz/testuuid

Thanks! I can reproduce but that's as far as my knowledge goes.

Trying to bump the `uuid` version in Apollo, I get this diff in the klibs:

```diff
$ diff compiledWith0_6_0/default/manifest compiledWith0_7_0/default/manifest
4c4
< depends=com.apollographql.apollo3\:apollo-annotations com.squareup.okio\:okio uuid kotlin
---
> depends=com.apollographql.apollo3\:apollo-annotations com.squareup.okio\:okio com.benasher44\:uuid kotlin
```

Looks like this is this [Youtrack](https://youtrack.jetbrains.com/issue/KT-58568/Daemon-compilation-failed), I'll leave a comment there.

**Comment by martinbonnin** [comment]
Thinking more about this, looks like [K/N backward compatibility is still experimental](https://youtrack.jetbrains.com/issue/KT-42293/Native-provide-binary-compatibility-between-incremental-releases) so this kind of things are somewhat expected. I think the correct fix is to provide `apiVersion`/`languageVersion` to JVM builds to maximize compatibility there. And for native, always use the latest version.

I filed https://github.com/benasher44/uuid/pull/147 on `uuid` for better compatibility in the future. 

Unfortunately, we're stuck for this specific case because of https://youtrack.jetbrains.com/issue/KT-61423:

* Either we keep `uuid:0.6.0` and newer K/N consumers will fail because of the above issue
* Or we update to `uuid:0.7.0` and the 1.6 JVM consumers will fail because of "incompatible metadata, 1.8 found, expected 1.6"
* Or we update to `uuid:0.8.0` and the 1.6 JVM consumers will fail because of "incompatible metadata, 1.9 found, expect 1.6"
* Or we update to `uuid:0.9.0` (when available) and the 1.6 JVM consumers will fail because of KT-61423

Given the absence of a one-size-fits-all solution, moving forward seems a better solution. Unless strong objections, I'll drop support for Kotlin 1.6 and update to `uuid:0.7.0` for the time being (and `uuid:0.9.0` when available)

**Comment by erokhins** [comment]
@martinbonnin I saw a couple of reports from you in our Kotlin tracker (Thank you for that)!
And I'm curious. Why it is important for you to keep compatibility with clients that are using the old multiplatform Kotlin plugin? 
I understand why it is important to keep compatibility with old Kotlin JVM clients, but I don't expect a lot of old KMP clients.

**Comment by erokhins** [comment]
`.jar` is indeed the same, but we have 2 different grade plugin -- one for the Multiplatforms users, and other -- for JVM users. I.e. bugs like https://youtrack.jetbrains.com/issue/KT-61423 shouldn't affect JVM users on Kotlin 1.6. But for errors like "incompatible metadata version" is indeed the same for KMP and JVM.

**Comment by martinbonnin** [comment]
Right 👍 I edited [my comment above](https://github.com/apollographql/apollo-kotlin/issues/5046#issuecomment-1689699122). 

So looks like updating to `uuid:0.9.0` (when available) is the perfect way forward. And until then using `uuid:0.7.0` mitigates the issue at the price of bumping the JVM requirements to 1.7.
