### ISSUE TITLE
ApolloInitializer$Companion context has not been initialized

### ISSUE THREAD

**Issue by yuvaraj119** [apollographql/apollo-kotlin#5277]
### Version

3.8.0, 3.8.2

### Summary

Caused by: kotlin.UninitializedPropertyAccessException: lateinit property context has not been initialized
                                                                                        	at com.apollographql.apollo3.cache.normalized.sql.ApolloInitializer$Companion.getContext$apollo_normalized_cache_sqlite_debug(ApolloInitializer.kt:17)
                                                                                        	at com.apollographql.apollo3.cache.normalized.sql.internal.FactoryImplementationsKt.createDriver(factoryImplementations.kt:15)
                                                                                        	at com.apollographql.apollo3.cache.normalized.sql.SqlNormalizedCacheFactory.<init>(SqlNormalizedCacheFactory.kt:38)

### Logs

```
(Your logs here)
```

**Comment by martinbonnin** [comment]
Looks like you're on Android and using the [androidx.startup](https://developer.android.com/topic/libraries/app-startup) library? I'd recommend double checking your merged manifest, making sure the ApolloInitializer is correctly setup.

If using androidx.startup is too cumbersome, you always have the option to create the normalized cache manually:

```kotlin
val cacheFactory = SqlNormalizedCacheFactory(context)
```

**Comment by yuvaraj119** [comment]
I can see meta-data in manifest
```
<provider
        name="androidx.startup"
<meta-data 
       android:name="com,apollographql.apollo3.cache.normalized.sql.ApolloInitializer"
       android:value="androidx.startup"/>
<meta-data 
       android:name="androidx.work.workmanagerinitializer"
       android:value="androidx.startup"/>
</provider>
```
Still i'm getting error

**Comment by yuvaraj119** [comment]
One of my app works perfectly where the other has this issue not sure what i'm missing for timebeing end up manually initialization and it worked.

`AppInitializer.getInstance(applicationContext)
            .initializeComponent(ApolloInitializer::class.java)`
