### ISSUE TITLE
NoSuchElementException when calling execute()

### ISSUE THREAD

**Issue by jrowan3** [apollographql/apollo-kotlin#5356]
### Question

Hi all, i am making a query

`apolloClient.query(MyQuery()).execute()`

and it is thowing a NoSuchElementException
I am looking at my proxy and see that the call is made and the response is there, but i am getting NoSuchElementException when making the execute() call

Thank you for your time

**Comment by BoD** [comment]
Hi! Could you attach the full stacktrace of the exception? Also, which version of the library are you using? Thanks.

**Comment by jrowan3** [comment]
@BoD here is the stacktrace, i took out the companies parts of it

it starts with execute() and goes down like this

```
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

apollographqlDependencies = [
            runtime       : "com.apollographql.apollo3:apollo-runtime:${apolloReleaseVersion}",
            api           : "com.apollographql.apollo3:apollo-api:${apolloReleaseVersion}",
            httpCache     : "com.apollographql.apollo3:apollo-http-cache:${apolloReleaseVersion}",
            rxSupport     : "com.apollographql.apollo3:apollo-rx3-support:${apolloReleaseVersion}",
            testingSupport    : "com.apollographql.apollo3:apollo-testing-support:${apolloReleaseVersion}"
    ]
    
    apolloReleaseVersion = 3.8.2

**Comment by BoD** [comment]
Thanks! This stacktrace doesn't help too much, maybe we'll have more luck with:

```kotlin
try {
  apolloClient.query(MyQuery()).execute()
} catch (e: Exception) {
  e.printStackTrace()
}
```

**Comment by jrowan3** [comment]
@BoD this is the full stacktrace

java.util.NoSuchElementException: Flow is empty
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__ReduceKt.single(Reduce.kt:62)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt.single(Unknown Source:1)
                                                                                                    	at com.apollographql.apollo3.ApolloCall.execute(ApolloCall.kt:129)
                                                                                                    	at com.something(FManager.kt:412)
                                                                                                    	at com.something(Networking.kt:439)
                                                                                                    	at com.something.MyViewModel$myviewmodelcall$1.invokeSuspend(MyViewModel.kt:64)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

**Comment by BoD** [comment]
Interesting - would you be able to share your project (or a simplified version of it) by any chance?

**Comment by jrowan3** [comment]
@BoD I cannot share my project, it is for the company i work for

**Comment by jrowan3** [comment]
@BoD I cannot send you anything, do you have any idea or clue as to what might be happening in this case? Have you seen this before at all?

**Comment by BoD** [comment]
Alas no this is unexpected, and without any clue of what your code is doing, it's hard to guess what could be wrong. 

Here is what I would do: start a very simple project from scratch, make sure that works, and then add code from your real project to it. This should help find which part is creating the issue.

**Comment by martinbonnin** [comment]
Might be worth checking cache configuration/any interceptor configured?

**Comment by martinbonnin** [comment]
@jrowan3 anything else we can help with here?

**Comment by martinbonnin** [comment]
Closing for now, please leave a comment if you want us to reopen
