### ISSUE TITLE
[Android] Proceesing 2 queries apollo graphql that have same type into 1 array

### ISSUE THREAD

**Issue by muslimmuda15** [apollographql/apollo-kotlin#5359]
### Question

Hi all. 
I have 2 queries that have same type

![image](https://github.com/apollographql/apollo-kotlin/assets/26782958/3f6d544a-318c-420d-9f0e-f258e11bd124)

I tried to insert findOrderByOid into [FindOrderByRestaurantId] like this:

```
var orderListData: ArrayList<FindOrderByRestaurantIdQuery.FindOrderByRestaurantId?> = ArrayList()
    fun getOrderList(){
        scope.launch {
            apolloBuilder.apolloBuild().query(
                FindOrderByRestaurantIdQuery(
                    id = "1"
                )
            ).execute().apply {
                orderListData = data?.findOrderByRestaurantId?.toCollection(ArrayList()) ?: ArrayList()
            }
        }
    }
    
    fun getOrderDetail(){
        scope.launch {
            apolloBuilder.apolloBuild().query(
                FindOrderByOidQuery(
                    oid = "15"
                )
            ).execute().apply {
                data?.findOrderByOid?.let {
                    orderListData.add(it)
                }
            }
        }
    }
```
but getting error:
```
Type mismatch.
Required: FindOrderByRestaurantIdQuery.FindOrderByRestaurantId?
Found: FindOrderByOidQuery.FindOrderByOid
```
I cannot making new data class then parsing one by one because OrderResult has almost hundred variables

How to get the response as `OrderResult`?

Here my gradle:
```
plugins {
    id 'com.android.application' version '8.1.2' apply false
    id 'org.jetbrains.kotlin.android' version "1.9.0" apply false
    id 'com.apollographql.apollo3' version '3.8.2' apply false
    id 'org.jetbrains.kotlin.jvm' version '1.9.10' apply false
    ...
}
```
```
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.apollographql.apollo3'
    ...
}

android {
    ...
    compileSdk 34
    defaultConfig {
        ...
        minSdk 21
        targetSdk 34
        ...
    }
    compileOptions {
        sourceCompatibility 17
        targetCompatibility 17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

apollo {
    service("myapp") {
        packageName.set("com.myapp.app")
//        codegenModels.set("responseBased")
        introspection {
            endpointUrl.set("https://endpoint.com/data/")
            schemaFile.set(file("src/main/graphql/sg/com/myapp/app/schema.graphqls"))
        }
        customTypeMapping = [
                "Date"    : "kotlin.String",
                "DateTime": "kotlin.String",
                "Time"    : "kotlin.String",
                "BigInt"  : "kotlin.Long",
                "Double"  : "kotlin.Double"
        ]
    }
}

dependencies {
    ...
    implementation 'com.apollographql.apollo3:apollo-runtime:3.8.2'
    implementation 'com.apollographql.apollo3:apollo-api:3.8.2'
    ...
}
```
If something is missing, let me know
thanks

**Comment by BoD** [comment]
Hi!

Apollo Kotlin will generate a specific model for each query you declare in your graphql files. The reason is, even if in the schema they have the same type, on your side you may select different fields on these queries.

However you can still achieve some model reuse by using fragments, for example:

```graphql
fragment allOrderFields on OrderResult {
  allServed
  billUrl
  # etc.
}

query FindOrderByOidQuery($oid: ID!) {
  findOrderByOid {
    ...allOrderFields
  }
}

query FindOrderByRestaurantIdQuery($id: ID!) {
  findOrderByRestaurantIdQuery {
    ...allOrderFields
  }
}
``` 

Hope this helps!

**Comment by muslimmuda15** [comment]
It seem great work, but how to making `AllOrderField` can inheritance?
like this:
```
data class CustomAllOrderField(
    var customId: Int,
    var order: AllOrderField
): AllOrderField by order
```

**Comment by BoD** [comment]
For `by order` to work, `AllOrderField` would need to be an interface. You could do the delegation manually, e.g.

```
class CustomAllOrderField(
    val customId: Int,
    private val order: AllOrderField
) {
    val allServed = order.allServed
    val billUrl = order.billUrl
    // etc.
}
```

Otherwise you can just access the fields through `order`: `myCustomAllOrderField.order.allServed` etc.

**Comment by muslimmuda15** [comment]
I got error 
```
java.lang.IllegalArgumentException: Parcel: unknown type for value AllOrderField(params)
                                                                                                        at android.os.Parcel.getValueType(Parcel.java:2421)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2320)
                                                                                                    	at android.os.Parcel.writeList(Parcel.java:1394)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2472)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2328)
                                                                                                    	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1277)
                                                                                                    	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
                                                                                                    	at android.os.Bundle.writeToParcel(Bundle.java:1362)
                                                                                                    	at android.os.Parcel.writeBundle(Parcel.java:1346)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2445)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2335)
                                                                                                    	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1277)
                                                                                                    	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
                                                                                                    	at android.os.Bundle.writeToParcel(Bundle.java:1362)
                                                                                                    	at android.os.Parcel.writeBundle(Parcel.java:1346)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2445)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2335)
                                                                                                    	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1277)
                                                                                                    	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
                                                                                                    	at android.os.Bundle.writeToParcel(Bundle.java:1362)
                                                                                                    	at android.os.Parcel.writeBundle(Parcel.java:1346)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2445)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2335)
                                                                                                    	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1277)
                                                                                                    	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
                                                                                                    	at android.os.Bundle.writeToParcel(Bundle.java:1362)
                                                                                                    	at android.os.Parcel.writeBundle(Parcel.java:1346)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2445)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2335)
                                                                                                    	at android.os.BaseBundle.dumpStats(BaseBundle.java:1874)
                                                                                                    	at android.os.BaseBundle.dumpStats(BaseBundle.java:1911)
                                                                                                    	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:150)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
2023-11-16 14:05:47.718 27349-27349 AndroidRuntime          sg.com.appety.waiterapp.debug        E  	at android.app.ActivityThread.main(ActivityThread.java:8762)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```
I cannot see where error my code.
What should I do?

**Comment by BoD** [comment]
It's hard to know without more details. It looks like it is about your class being `Serializable` (or `Parcelable`?) but one of the field is of a type which is not?

**Comment by muslimmuda15** [comment]
hmmm, I think the problem is I put the query as `Serializable`
```
DoneOrdeFragment().apply {
       arguments = Bundle().apply {
            putSerializable(ORDER_LIST, orderList as Serializable)
       }
}
```
Can I send the `ArrayList<AllOrderField>` into another activity.

**Comment by BoD** [comment]
Indeed this shouldn’t work because you’re only allowed to pass classes that implement Serializable which is not the case of the data classes generated by Apollo.

It’s [recommended](https://developer.android.com/guide/navigation/navigation-pass-data#:~:text=Each%20destination%20should%20be%20responsible%20for%20loading%20UI%20data%20based%20on%20the%20minimum%20necessary%20information%2C%20such%20as%20item%20IDs) to only pass simple data to the destinations, and have them load the full data accordingly, so overall I would recommend to only pass the IDs of your objects around, and then the destination can fetch them. If you are using the Apollo (or a third-party) cache this shouldn't not go to the network and be fast.

Another way to do this would be to serialize to/from Json Strings and pass that to your Fragment/Activities. See [parsing a response body](https://www.apollographql.com/docs/kotlin/advanced/no-runtime/#parsing-an-http-response-body) for some details how to do this. But these strings may be lengthy and overall passing IDs is probably a better solution.

**Comment by BoD** [comment]
Closing for now, don't hesitate to open another issue if needed.
