### ISSUE TITLE
Removing OperationName

### ISSUE THREAD

**Issue by hamidreza-sani** [apollographql/apollo-kotlin#5496]
### Question

Is it possible to not pass OperationName to the backend? I would like to just pass variables and query

**Comment by martinbonnin** [comment]
You can customize the HTTP request using the `HttpRequestComposer` API:

```kotlin
  object myHttpRequestComposer : HttpRequestComposer { 
    override fun <D : Operation.Data> compose(apolloRequest: ApolloRequest<D>): HttpRequest {
      val postData = buildJsonString {
        writeObject {
          name("query")
          value(apolloRequest.operation.document())
          name("variables")
          apolloRequest.operation.serializeVariables(this, apolloRequest.executionContext[CustomScalarAdapters]!!, false)
        }
      }.encodeUtf8()


      return HttpRequest.Builder(HttpMethod.Post, "https://example.com/graphqls")
          .body(object : HttpBody {
            override val contentType: String
              get() = "application/Json"
            override val contentLength: Long
              get() = postData.size.toLong()

            override fun writeTo(bufferedSink: BufferedSink) {
              bufferedSink.write(postData)
            }
          })
          .build()
    }
  }
```

And then use it when building your ApolloClient:

```kotlin
    val apolloClient = ApolloClient.Builder()
        .networkTransport(
            HttpNetworkTransport.Builder()
                .httpRequestComposer(myHttpRequestComposer)
                .build()
        )
        .build()
```

**Comment by hamidreza-sani** [comment]
Thanks for the quick replying. Could I use this along with okHttpClient? 

```

@Provides
    @Singleton
    @Named("apollo")
    fun okhttpClientForApollo(): OkHttpClient {
        val logging = HttpLoggingInterceptor()
            .apply { level = HttpLoggingInterceptor.Level.BODY }
        return OkHttpClient().newBuilder()
            .connectTimeout(BFF_OK_HTTP_CONNECT_TIMEOUT_IN_SECONDS, TimeUnit.SECONDS)
            .readTimeout(BFF_OK_HTTP_READ_TIMEOUT_IN_SECONDS, TimeUnit.SECONDS)
            .writeTimeout(BFF_OK_HTTP_WRITE_TIMEOUT_IN_SECONDS, TimeUnit.SECONDS)
            .addInterceptor(GraphqlAuthInterceptor())
            .addInterceptor(logging)
            .build()
    }


@Provides
    @Singleton
    fun provideApollo(
        @Named("apollo") client: OkHttpClient
    ): ApolloClient {
        return ApolloClient.Builder()
            .okHttpClient(client)
            .build()
    }
```

**Comment by martinbonnin** [comment]
Sure, just set the `OkHttpClient` on the `HttpNetworkTransport`:

```kotlin
    val client = ApolloClient.Builder()
        .networkTransport(
            HttpNetworkTransport.Builder()
                .okHttpClient(yourOkHttpClient)
                .httpRequestComposer(myHttpRequestComposer)
                .build()
        )
        .build()

```

This is what `ApolloClient.Builder.okHttpClient()` is doing under the hood

**Comment by hamidreza-sani** [comment]
Getting a `Nesting problem` error now. Previously it was working as expected.
```
Error getting live orders Nesting problem. : java.lang.IllegalStateException: Nesting problem.
	at com.apollographql.apollo3.api.json.BufferedSinkJsonWriter.name(BufferedSinkJsonWriter.kt:119)
	at com.doordash.smartshelf.adapter.GetLiveOrdersQuery_VariablesAdapter.toJson(GetLiveOrdersQuery_VariablesAdapter.kt:32)
	at com.doordash.smartshelf.GetLiveOrdersQuery.serializeVariables(GetLiveOrdersQuery.kt:40)
	at com.doordash.smartshelf.network.ApiModule$apolloHttpRequestComposer.compose(ApiModule.kt:404)
	at com.apollographql.apollo3.network.http.HttpNetworkTransport.execute(HttpNetworkTransport.kt:50)
	at com.apollographql.apollo3.interceptor.NetworkInterceptor.intercept(NetworkInterceptor.kt:22)
	at com.apollographql.apollo3.interceptor.DefaultInterceptorChain.proceed(ApolloInterceptor.kt:23)
	at com.apollographql.apollo3.ApolloClient.executeAsFlow$apollo_runtime(ApolloClient.kt:187)
	at com.apollographql.apollo3.ApolloCall.toFlow(ApolloCall.kt:120)
	at com.apollographql.apollo3.ApolloCall.execute(ApolloCall.kt:129)
```

 I'm using Apollo3 (3.8.2) and noticed that `apolloRequest.operation.serializeVariables()` doesn't have a 3rd parameter so I wonder if there's a version missmatch

**Comment by martinbonnin** [comment]
My bad, I forgot to wrap the variables in `writeObject`:

```kotlin
          writeObject {
            apolloRequest.operation.serializeVariables(this, apolloRequest.executionContext[CustomScalarAdapters]!!, false)
          }
```

 I have edited [the code above](https://github.com/apollographql/apollo-kotlin/issues/5496#issuecomment-1865021945) to account for that

**Comment by hamidreza-sani** [comment]
worked perfectly. Thank you very much!!!
