### ISSUE TITLE
Apollo 2.5.14 crashes the app when connection timeout happens

### ISSUE THREAD

**Issue by Cryosleeper** [apollographql/apollo-kotlin#5544]
### Question

Hello,

When connection timeout happens due to back-end issues, we're seeing crashes coming from users:

```
Fatal Exception: com.apollographql.apollo.exception.ApolloNetworkException: Failed to execute http call for operation 'our operation name'

       at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$executeHttpCall$1.onFailure(ApolloServerInterceptor.kt:107)

       at com.google.firebase.perf.network.InstrumentOkHttpEnqueueCallback.onFailure(InstrumentOkHttpEnqueueCallback.java:63)

       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)

       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)

       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

       at java.lang.Thread.run(Thread.java:920)
```

We're using Rx3Apollo to convert the call into Observable, but this exception comes from a non-Rx stack trace. Looks like _ApolloServerInterceptor_ throws it outside, and we can't even add a handler directly. Apollo version is 2.5.14.

My questions are:
- what options do we have to handle it without a major version update?
- is there an option to setup automatic retry, with or without the version update? OkHttp3 should try it on its own, but does Apollo Kotlin has functionality similar to [Apollo Retry Link](https://www.apollographql.com/docs/react/api/link/apollo-link-retry/)?

**Comment by martinbonnin** [comment]
Hi 👋 

Tried reproducing with the following without success:

```java
public class MainTest {
    @Test
    public void testStuff() throws InterruptedException {
        OkHttpClient okHttpClient = new OkHttpClient.Builder()
                .readTimeout(Duration.of(2, ChronoUnit.SECONDS))
                .build();


        ApolloClient apolloClient = ApolloClient.builder()
                .okHttpClient(okHttpClient)
                .serverUrl("http://localhost:12987")
                .build();

        Rx3Apollo.from(apolloClient.query(new GetFooQuery())).subscribe(
                next -> {
                    System.out.println("Got data:" + next.getData().toString());
                },
                error -> {
                    System.out.println("Got error:" + error.getMessage());
                    error.printStackTrace();
                }
        );

        Thread.sleep(10000);
    }
}
```

(you can simulate a read timeout by starting [netcat](https://en.wikipedia.org/wiki/Netcat) in a shell: `nc -l 12987`)

Could it be that something in your RxJava chain intercept the error and rethrows it or something like so? If you could provide a reproducer, that'd help tremendously.

> is there an option to setup automatic retry, with or without the version update? OkHttp3 should try it on its own, but does Apollo Kotlin has functionality similar to [Apollo Retry Link](https://www.apollographql.com/docs/react/api/link/apollo-link-retry/)?

You can using `ApolloInterceptor`. My v2 skills are a bit rusty but something like this should do it:

```java
class RetryInterceptor implements ApolloInterceptor {

        @Override
        public void interceptAsync(@NotNull InterceptorRequest request, @NotNull ApolloInterceptorChain chain, @NotNull Executor dispatcher, @NotNull CallBack callBack) {
            chain.proceedAsync(request, dispatcher, new CallBack() {
                int retry = 0;

                @Override
                public void onResponse(@NotNull InterceptorResponse response) {
                    callBack.onResponse(response);
                }

                @Override
                public void onFetch(FetchSourceType sourceType) {

                }

                @Override
                public void onFailure(@NotNull ApolloException e) {
                    if (retry < 3) {
                        retry += 1;
                        System.out.println("retrying" + retry);
                        chain.proceedAsync(request, dispatcher, this);
                    } else {
                        callBack.onFailure(e);
                    }

                }

                @Override
                public void onCompleted() {

                }
            });
        }

        @Override
        public void dispose() {

        }
    }
```

**Comment by martinbonnin** [comment]
@Cryosleeper anything else we can help with here?

**Comment by Cryosleeper** [comment]
@martinbonnin should be all, thank you!
