### ISSUE TITLE
httpBatching() related crash

### ISSUE THREAD

**Issue by ber4444** [apollographql/apollo-kotlin#5665]
### Version

4.0.0-beta.4

### Summary

Crash due to https://github.com/apollographql/apollo-kotlin/blob/9bbdd325334873855382958dd2d05adebe5097dd/libraries/apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo3/network/http/BatchingHttpInterceptor.kt#L128 throwing an `IllegalStateException` which is not being handled anywhere

### Steps to reproduce the behavior

have a flaky network which would cause empty response bodies

### Logs

```
FATAL EXCEPTION: pool-25-thread-1
                                                                                                    Process: com.xxx.debug, PID: 29351
                                                                                                    java.lang.IllegalStateException: empty body while batching queries
                                                                                                    	at com.apollographql.apollo3.network.http.BatchingHttpInterceptor.executePendingRequests(BatchingHttpInterceptor.kt:128)
                                                                                                    	at com.apollographql.apollo3.network.http.BatchingHttpInterceptor.access$executePendingRequests(BatchingHttpInterceptor.kt:63)
                                                                                                    	at com.apollographql.apollo3.network.http.BatchingHttpInterceptor$intercept$3.invokeSuspend(BatchingHttpInterceptor.kt:108)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2e1274f, java.util.concurrent.Executors$FinalizableDelegatedExecutorService@9f1fedc]

```

**Comment by BoD** [comment]
Hi! Thanks for reporting this. Bodies should definitely not be null here, although here they're request (not response) bodies, which makes me think something other than network flakiness may be the root cause. Would you have a way to reproduce this by any chance?

**Comment by ber4444** [comment]
Yeah, I realized it happens every time when using
```
ApolloClient.Builder()
                ...
                .httpBatching()
```
whereas adding `.canBeBatched(true)` to the query invocation works fine.

**Comment by ber4444** [comment]
we have this as well in the builder, if that matters:
```
.autoPersistedQueries(
                    // For the initial hashed query that does not send the actual Graphql document
                    httpMethodForHashedQueries = HttpMethod.Get,

                    // For the follow-up query that sends the full document if the initial hashed query was not found
                    httpMethodForDocumentQueries = HttpMethod.Get
                )
```

**Comment by BoD** [comment]
Ah that explains it, thanks.

Indeed, with auto persisted queries configured with GET, requests won't have a body which causes this crash when trying to batch them.

I'm curious to know if your server will support batching and APQ at the same time - you could try with `Post` instead to confirm.

If you want to use both features in different parts of your code, you can configure them with `enableByDefault = false` and then enable them on individual calls with `.enableAutoPersistedQueries(true)` or `canBeBatched(true)`.

**Comment by BoD** [comment]
@ber4444 Is there anything else we can do on this?

**Comment by BoD** [comment]
Closing for now, don't hesitate to reopen a ticket if you need assistance.
