### ISSUE TITLE
How to throw error apollographql based from OkHttp

### ISSUE THREAD

**Issue by muslimmuda15** [apollographql/apollo-kotlin#5741]
### Question

I just create apollo builder like this:
```kotlin
fun apolloBuild(token: String): ApolloClient {
        errorData = ErrorData()
        Log.d("OkHttp", "JWT TOKEN : " + "JWT" + " " + token)
        val interceptor = HttpLoggingInterceptor()
        interceptor.setLevel(HttpLoggingInterceptor.Level.BODY)

        val okHttpClient = OkHttpClient.Builder()
                .addInterceptor(interceptor)
                .addNetworkInterceptor(StethoInterceptor())
                .addNetworkInterceptor(object: Interceptor {
                    override fun intercept(chain: Interceptor.Chain): Response {
                        return chain.proceed(chain.request()
                                .newBuilder()
                                .header ("Authorization", "JWT $token")
                                .build())
                    }
                })
                .connectTimeout(60, TimeUnit.SECONDS)
                .readTimeout(60, TimeUnit.SECONDS)
                .writeTimeout(60, TimeUnit.SECONDS)
                .build()

        return ApolloClient.Builder()
                .serverUrl(BuildConfig.SERVER_URL)
                .okHttpClient(okHttpClient)
                .build()
    }
```

and I create apollo request like this 
```kotlin
CoroutineScope(Dispatchers.IO).launch {
            try {
                apolloBuilder.apolloBuild(jwt).mutation(
                    LockOrderV2Mutation(
                        restoId = id,
                        lock = false
                    )
                ).execute().apply {
                    data?.let {
                          setData(it)
                     }
                }
            } catch (e: ApolloException) {
                val error = e.message
            }
        }
```

But, I got from variable `error` message like this `Http request failed with status code '400'`
But the error from OkHttp Logging Interceptor like this:
```json
{
  "errors": [
    {
      "message": "Variable \"$oid\" of type \"Boolean!\" used in position expecting type \"String!\".",
      "code": "GRAPHQL_VALIDATION_FAILED",
      "locations": [
        {
          "line": 1,
          "column": 48
        },
        {
          "line": 1,
          "column": 133
        }
      ],
      "extensions": {
        "code": "GRAPHQL_VALIDATION_FAILED",
        "exception": {
          "stacktrace": [
            "GraphQLError: Variable \"$oid\" of type \"Boolean!\" used in position expecting type \"String!\".",
            "    at Object.leave (/opt/apps/node_modules/graphql/validation/rules/VariablesInAllowedPositionRule.js:64:17)",
            "    at Object.leave (/opt/apps/node_modules/graphql/language/visitor.js:324:32)",
            "    at Object.leave (/opt/apps/node_modules/graphql/utilities/TypeInfo.js:411:21)",
            "    at visit (/opt/apps/node_modules/graphql/language/visitor.js:197:21)",
            "    at validate (/opt/apps/node_modules/graphql/validation/validate.js:91:24)",
            "    at validate (/opt/apps/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)",
            "    at processGraphQLRequest (/opt/apps/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
            "    at async processHTTPRequest (/opt/apps/node_modules/apollo-server-core/dist/runHttpQuery.js:221:30)"
          ]
        }
      }
    }
  ]
}
```
How to get the error from OkHttp error response, so the error what I want like this `"Variable \"$oid\" of type \"Boolean!\" used in position expecting type \"String!\"."`?

**Comment by martinbonnin** [comment]
Hi 👋 

Thanks for sending this! There are several things happening here.

### Validation error

Your server fails to validate your query:

```
Variable \"$oid\" of type \"Boolean!\" used in position expecting type \"String!\"
```

On the other hand Apollo Kotlin compiled it correctly. 

This might indicate a problem in our client-side validation code. If you can share your schema and mutation, I can look into this.


### HTTP code 400

Your server returns a '400' HTTP code:

```
Http request failed with status code '400'
```

When seeing a non-2xx status code, Apollo Kotlin doesn't try to parse the errors (because the response could be of any shape). For this reason, the GraphQL over HTTP spec recommends to use `200` for validation error (spechttps://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md?plain=1#L602).

I'd recommend your backend team to change the error code to 200 and then you'll be able to get the message with

```kotlin
val response = apolloClient.query(HeroNameQuery()).execute()
println(response.errors.first().message

```

### `httpExposeErrorBody`

If changing the HTTP status code is not an option, you can get the raw HTTP response body using `httpExposeErrorBody`:

```kotlin
    val apolloClient = ApolloClient.Builder()
        .serverUrl(mockServer.url())
        .httpExposeErrorBody(true)
        .build()
```

And then use `ApolloHttpException.bodu`

```kotlin
    try {
      val response = apolloClient.query(HeroNameQuery()).execute()
    } catch (e: ApolloHttpException) {
      println("Error: ${e.body?.use { it.readUtf8() }}")
    } catch(e: ApolloException) {
      // ....
    }
```

Just remember to always catch `ApolloHttpException` and close the body as failing to do so will create a resource leak.


Hope this helps, let me know how that goes!

**Comment by muslimmuda15** [comment]
Thats great.
But how to split into variable likely
```kotlin
var message = e.body.message
var code = e.body.code
var stacktrace = e.body.stacktrace
```

**Comment by martinbonnin** [comment]
There is `com.apollographql.apollo3.api.Error` but `code` and `stacktrace` are not GraphQL standard fields so you'll have to define your own structure if you want to read those. I recommend using `kotlinx-serialization` or `moshi` for this.

**Comment by muslimmuda15** [comment]
Thanks you.
