### ISSUE TITLE
Build fails with Android 15

### ISSUE THREAD

**Issue by SebPawp** [apollographql/apollo-kotlin#5785]
### Version

3.8.3

### Summary

I updated app to target Android 15 and the build fails.
`> Task :check{MyApp}ApolloDuplicates`

### Steps to reproduce the behavior

Set these values to your Project's main app module:
```
android {
    compileSdkPreview "VanillaIceCream"
    ...
    defaultConfig {
        targetSdkPreview "VanillaIceCream"
    }
}
```

### Logs

```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Multiple build operations failed.
    There was a failure while populating the build operation queue: Could not isolate parameters com.android.build.gradle.internal.utils.D8BackportedMethodsGenerator$Parameters_Decorated@3f8c31dd of artifact transform D8BackportedMethodsGenerator
    There was a failure while populating the build operation queue: Could not isolate parameters com.android.build.gradle.internal.utils.D8BackportedMethodsGenerator$Parameters_Decorated@41269944 of artifact transform D8BackportedMethodsGenerator
There was a failure while populating the build operation queue: Could not isolate parameters com.android.build.gradle.internal.utils.D8BackportedMethodsGenerator$Parameters_Decorated@3f8c31dd of artifact transform D8BackportedMethodsGenerator
Could not isolate parameters com.android.build.gradle.internal.utils.D8BackportedMethodsGenerator$Parameters_Decorated@3f8c31dd of artifact transform D8BackportedMethodsGenerator
Could not isolate value com.android.build.gradle.internal.utils.D8BackportedMethodsGenerator$Parameters_Decorated@3f8c31dd of type D8BackportedMethodsGenerator.Parameters
Cannot query the value of this property because it has no value available.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
com.intellij.openapi.externalSystem.model.ExternalSystemException: Multiple build operations failed.
    There was a failure while populating the build operation queue: Could not isolate parameters com.android.build.gradle.internal.utils.D8BackportedMethodsGenerator$Parameters_Decorated@3f8c31dd of artifact transform D8BackportedMethodsGenerator
    There was a failure while populating the build operation queue: Could not isolate parameters com.android.build.gradle.internal.utils.D8BackportedMethodsGenerator$Parameters_Decorated@41269944 of artifact transform D8BackportedMethodsGenerator
There was a failure while populating the build operation queue: Could not isolate parameters com.android.build.gradle.internal.utils.D8BackportedMethodsGenerator$Parameters_Decorated@3f8c31dd of artifact transform D8BackportedMethodsGenerator
Could not isolate parameters com.android.build.gradle.internal.utils.D8BackportedMethodsGenerator$Parameters_Decorated@3f8c31dd of artifact transform D8BackportedMethodsGenerator
Could not isolate value com.android.build.gradle.internal.utils.D8BackportedMethodsGenerator$Parameters_Decorated@3f8c31dd of type D8BackportedMethodsGenerator.Parameters
Cannot query the value of this property because it has no value available.
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.addBuildModels(ProjectImportAction.java:439)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:139)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:43)
	...
Cause 1: org.gradle.internal.operations.BuildOperationQueueFailure: There was a failure while populating the build operation queue: Could not isolate parameters com.android.build.gradle.internal.utils.D8BackportedMethodsGenerator$Parameters_Decorated@3f8c31dd of artifact transform D8BackportedMethodsGenerator
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.executeInParallel(DefaultBuildOperationExecutor.java:138)
	...
Caused by: org.gradle.api.artifacts.transform.VariantTransformConfigurationException: Could not isolate parameters com.android.build.gradle.internal.utils.D8BackportedMethodsGenerator$Parameters_Decorated@3f8c31dd of artifact transform D8BackportedMethodsGenerator
	at org.gradle.api.internal.artifacts.transform.DefaultTransformer$IsolateTransformerParameters.doIsolateParameters(DefaultTransformer.java:667)
	...
Caused by: org.gradle.internal.snapshot.impl.IsolationException: Could not isolate value com.android.build.gradle.internal.utils.D8BackportedMethodsGenerator$Parameters_Decorated@3f8c31dd of type D8BackportedMethodsGenerator.Parameters
	at org.gradle.internal.snapshot.impl.DefaultIsolatableFactory.isolate(DefaultIsolatableFactory.java:51)
	...
Caused by: org.gradle.api.internal.provider.MissingValueException: Cannot query the value of this property because it has no value available.
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateOwnPresentValue(AbstractMinimalProvider.java:75)
	...
Cause 2: org.gradle.internal.operations.BuildOperationQueueFailure: There was a failure while populating the build operation queue: Could not isolate parameters com.android.build.gradle.internal.utils.D8BackportedMethodsGenerator$Parameters_Decorated@41269944 of artifact transform D8BackportedMethodsGenerator
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.executeInParallel(DefaultBuildOperationExecutor.java:138)
	...
Caused by: org.gradle.api.artifacts.transform.VariantTransformConfigurationException: Could not isolate parameters com.android.build.gradle.internal.utils.D8BackportedMethodsGenerator$Parameters_Decorated@41269944 of artifact transform D8BackportedMethodsGenerator
	at org.gradle.api.internal.artifacts.transform.DefaultTransformer$IsolateTransformerParameters.doIsolateParameters(DefaultTransformer.java:667)
	...
Caused by: org.gradle.internal.snapshot.impl.IsolationException: Could not isolate value com.android.build.gradle.internal.utils.D8BackportedMethodsGenerator$Parameters_Decorated@41269944 of type D8BackportedMethodsGenerator.Parameters
	at org.gradle.internal.snapshot.impl.DefaultIsolatableFactory.isolate(DefaultIsolatableFactory.java:51)
	...
Caused by: org.gradle.api.internal.provider.MissingValueException: Cannot query the value of this property because it has no value available.
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateOwnPresentValue(AbstractMinimalProvider.java:75)	
	...


==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Failed to stop service 'com.android.build.gradle.internal.errors.SyncIssueReporterImpl$GlobalSyncIssueService_8e32bece-f20c-415d-ab35-12e68e90a276'.
> Failed to find Platform SDK with path: platforms;android-35

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.api.services.internal.ServiceLifecycleException: Failed to stop service 'com.android.build.gradle.internal.errors.SyncIssueReporterImpl$GlobalSyncIssueService_8e32bece-f20c-415d-ab35-12e68e90a276'.
	at org.gradle.api.services.internal.RegisteredBuildServiceProvider.lambda$maybeStop$1(RegisteredBuildServiceProvider.java:169)
	...
Caused by: com.android.builder.errors.EvalIssueException: Failed to find Platform SDK with path: platforms;android-35
	at com.android.build.gradle.internal.errors.SyncIssueReporterImpl.reportRemainingIssues(SyncIssueReporterImpl.kt:72)
	at com.android.build.gradle.internal.errors.SyncIssueReporterImpl.access$reportRemainingIssues(SyncIssueReporterImpl.kt:39)
	at 
        ...

==============================================================================

BUILD FAILED in 738ms
```

**Comment by BoD** [comment]
Thanks for reporting this!

After a quick test on our Tutorial app [here](https://github.com/BoD/apollo-kotlin-tutorial/tree/vanilla-ice-cream), I can't seem to reproduce the issue. Is there a way you could share a small project where you have the issue? Thanks!

**Comment by SebPawp** [comment]
Hi @BoD, thanks for the quick response.

It looks like it's related to `coreLibraryDesugaringEnabled`. [Doc here](https://developer.android.com/studio/write/java8-support).

When set to true the Apollo task fails.

```
compileOptions {
        // Flag to enable support for the new language APIs
        coreLibraryDesugaringEnabled false
    }
```

**Comment by BoD** [comment]
It looks like I still can build/run without an issue [with this](https://github.com/BoD/apollo-kotlin-tutorial/blob/vanilla-ice-cream/compose/final/app/build.gradle.kts#L28).

**Comment by SebPawp** [comment]
Do you mind trying to set this line to true: https://github.com/BoD/apollo-kotlin-tutorial/blob/vanilla-ice-cream/compose/final/app/build.gradle.kts#L36C9-L36C47

Hopefully it will fail for you as well...

**Comment by BoD** [comment]
Woops sorry I meant to set it to true! But [with true](https://github.com/BoD/apollo-kotlin-tutorial/commit/3db068ada0b954947ebf4126d693db97ff8fee5e#diff-53e942cb2f3b02db0708f8869dd4f16aa4045dca16b799da96f7ec983bde1f73R36) I still don't have the issue.

Actually I just noticed this line in your stacktrace: `Failed to find Platform SDK with path: platforms;android-35` - do you have it installed in SDK manager?
