### ISSUE TITLE
Try the experimental WebSocketNetworkTransport

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#5862]
### Description

Historically, WebSockets have been one of the most complex and error-prone parts of Apollo Kotlin.

Starting with `4.0.0-beta.6`, `apollo-runtime` has an experimental `ApolloWebSocketNetworkTransport` aiming at simplifying the WebSocket setup. 

If you have had issues with WebSockets, try it out. More documentation and migration guide is available at https://www.apollographql.com/docs/kotlin/v4/advanced/experimental-websockets

**Comment by dmitrytavpeko** [comment]
Great job, thanks! I don't observe `kotlinx.coroutines.channels.ClosedReceiveChannelException: Channel was closed` errors anymore that prevented from reinstating my subscriptions!
While migrating to the new implementation, I encountered these issues:

1. API doesn't allow to set an OkHttpClient. In the old implementation we have `.webSocketEngine(DefaultWebSocketEngine(mySharedOkHttpClient))`
2. The [documentation](https://www.apollographql.com/docs/kotlin/v4/advanced/experimental-websockets/) says that it's possible to customize the retry logic by using `addRetryOnErrorInterceptor`. However, such an API doesn't exist. I used to customize the backoff in the following way:
```
                        .reopenWhen { throwable, attempt ->
                            val delayBeforeNextAttemptMs =
                                2.0.pow(attempt.toInt()).coerceAtMost(30.0).toLong() * 1_000L
                            delay(delayBeforeNextAttemptMs)
                            true
                        }
```
Will these issue be addressed in the future?

**Comment by martinbonnin** [comment]
@dmitrytavpeko `WebSocketEngine(WebSocket.Factory)` is now available in the [SNAPSHOTs](https://www.apollographql.com/docs/kotlin/#snapshots) if you want to try it out

**Comment by dmitrytavpeko** [comment]
@martinbonnin Thank you for the quick response!

**Comment by martinbonnin** [comment]
@jvanderwee Can you share your existing code here? I'll add the matching snippet to the doc

**Comment by jvanderwee** [comment]
```
class WebSocketReconnectException: Exception("The WebSocket needs to be reopened")
```

```
val apolloClient = ApolloClient.Builder()
    .serverUrl("http://localhost:8080/graphql")
    .subscriptionNetworkTransport(
        WebSocketNetworkTransport.Builder()
            .serverUrl("http://localhost:8080/subscriptions")
            .protocol(
                GraphQLWsProtocol.Factory(
                    connectionPayload = {
                        mapOf("Authorization" to token)
                    },
                ),
            )
            .reopenWhen { throwable, attempt ->
                if (throwable is WebSocketReconnectException) {
                    true
                } else {
                    // Another WebSocket error happened, decide what to do with it
                    // Here we're trying to reconnect at most 3 times
                    attempt < 3
                }
            }
            .build()
    )
    .build()
```

```
apolloClient.subscriptionNetworkTransport.closeConnection(WebSocketReconnectException())
```

**Comment by martinbonnin** [comment]
Hi @jvanderwee thanks for sending this! 

Looks like you're calling `closeConnection()` to force a reconnect. `closeConnection()` is still around so you can do something similar with:

```kotlin
class WebSocketReconnectException: Exception("The WebSocket needs to be reopened")
class RetryException: Exception("The WebSocket needs to be retried")
```

```kotlin
class MyInterceptor: ApolloInterceptor {
  override fun <D : Operation.Data> intercept(request: ApolloRequest<D>, chain: ApolloInterceptorChain): Flow<ApolloResponse<D>> {
    return chain.proceed(request)
        .onEach {
          if (request.retryOnError == true && it.exception != null && it.exception is ApolloNetworkException) {
            throw RetryException()
          }
        }
        .retryWhen { cause, attempt ->
          when (cause) {
            is RetryException -> {
              attempt < 3
            }
            is WebSocketReconnectException -> {
              true
            }
            else -> false
          }
        }.catch { 
          if (it !is RetryException) {
            throw it
          }
        }
  }
}
```

```kotlin
val apolloClient = ApolloClient.Builder()
    .serverUrl("http://localhost:8080/graphql")
    .subscriptionNetworkTransport(
        WebSocketNetworkTransport.Builder()
            .serverUrl("http://localhost:8080/subscriptions")
            .protocol(
                GraphQLWsProtocol(
                    connectionParams = {
                        mapOf("Authorization" to token)
                    },
                ),
            )
            .retryOnError { it.operation is Subscription }
            .retryOnErrorInterceptor(MyInterceptor())
            .build()
    )
    .build()
```


```kotlin
apolloClient.subscriptionNetworkTransport.closeConnection(WebSocketReconnectException())
```

While the above should be working, it's pretty verbose and I'd love to take this opportunity to do things a bit better. 

Can you share what triggers the call to `closeConnection()`? Is that a sepcific GraphQL message? A WebSocket close frame? Or something else completely out of band?

**Comment by jvanderwee** [comment]
When we change the import for closeConnection
```diff
-import com.apollographql.apollo.network.ws.closeConnection
+import com.apollographql.apollo.network.websocket.closeConnection
```
the exception is expected to be of type `ApolloException`, so we're forced to use something like `DefaultApolloException`:
```
apolloClient.subscriptionNetworkTransport.closeConnection(DefaultApolloException("WebSocket needs to be closed"))
```
but then this means we need `is DefaultApolloException` in the `retryWhen` which doesn't seem quite right:
```
.retryWhen { cause, attempt ->
    when (cause) {
        is DefaultApolloException -> {
            true
        }
        ...
    }
}
```
could we add a specific subclass of `ApolloException` to be used for closing the connection?

if we don't update the import an `IllegalArgumentException` is thrown because `websocket.WebSocketNetworkTransport` is not an instance of `ws.WebSocketNetworkTransport`

we close the connection whenever we need to update the authorisation header in the payload

**Comment by martinbonnin** [comment]
Thanks for the follow up!

> could we add a specific subclass of ApolloException to be used for closing the connection?

We can make a `closeConnection()` that reports a `WebSocketManuallyClosedException`. I'd still keep the `closeConnection(ApolloException)` in case someone needs to tunnel data.

> we close the connection whenever we need to update the authorisation header in the payload

That's the question. When do you need to update the authorization header? Ideally I would expect the server to notify its listeners directly in the websocket with some message (`"token expired"`) or even a WebSocket close frame. 

This seems like the best way and would allow to handle websocket authentication in a single interceptor, just like for HTTP. That'd be a lot more symmetrical. But maybe your server doesn't signal that? In which case I'm curious how you can tell that you need to refresh the token (timeout, something else?)

**Comment by jvanderwee** [comment]
> We can make a closeConnection() that reports a WebSocketManuallyClosedException
👌 thanks!

>  I would expect the server to notify its listeners directly in the websocket
very good point! we've been closing the connection as a side-effect of our HTTP authorisation interceptor, but it makes way more sense for this to be handle my the websocket itself. I'll look into this! we will still need to update the authorisation header when the user logs in though

**Comment by martinbonnin** [comment]
> we've been closing the connection as a side-effect of our HTTP authorisation interceptor

Interesting! What happens if you're on a screen that listens to a subscription without ever doing a query/subscription? The subscription has no way to know when to renew its token in that case?

**Comment by jvanderwee** [comment]
correct! very much an oversight on our part 🙃

**Comment by martinbonnin** [comment]
@jvanderwee Thanks for the follow up! 

* `closeConnection()` is added in https://github.com/apollographql/apollo-kotlin/pull/6105.
* Documentation changes are in https://github.com/apollographql/apollo-kotlin/pull/6106. 

I did **not** mention `closeConnection()` explicitely in there because I'd like to avoid promoting it too much. While it's technically the only way to get your setup working for now, I'd like to encourage the backend to send something when the token needs to be updated instead. 

This probably will require new APIs to update the token from an `ApolloInterceptor`, just like for the `Authorization` header for HTTP.

Right now I'm thinking something like this:

```kotlin
class AuthorizationInterceptor : ApolloInterceptor {
  override fun <D : Operation.Data> intercept(request: ApolloRequest<D>, chain: ApolloInterceptorChain): Flow<ApolloResponse<D>> {
    return flow {
      val token = getOrRefreshToken()
      emit(
          request.newBuilder()
              // for HTTP transport
              .addHttpHeader("Authorization", "Bearer $token")
              // for WebSocket transport
              //.webSocketConnectionPayload(mapOf("token" to token))
              .build()
      )
    }.flatMapConcat {
      chain.proceed(it)
    }.onEach { 
      if (it.errors.contains("Token expired")) {
        throw TokenExpired
      }
    }.retryWhen { cause, attempt -> 
      cause is TokenExpired
    }
  }
}
```

I haven't tested it yet but assuming the server can return the 401 information is a regular GraphQL response, that would allow handling authentication consistently between HTTP and WebSocket. Any thoughts? Could that work for you?

**Comment by jvanderwee** [comment]
That would work for us! Thanks @martinbonnin

**Comment by jvanderwee** [comment]
👋 we're seeing the following crash occur on Android in 4.0.1 after migrating to experimental web sockets. unsure when this happens at the moment, will update if we narrow it down


```
          Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void w6.u.close(int, java.lang.String)' on a null object reference
       at com.apollographql.apollo.network.websocket.internal.SubscribableWebSocket.shutdown(SubscribableWebSocket.kt:119)
       at com.apollographql.apollo.network.websocket.internal.SubscribableWebSocket.onError(SubscribableWebSocket.kt:220)
       at com.apollographql.apollo.network.websocket.JvmWebSocket.onFailure(WebSocketEngine.jvm.kt:67)
       at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.kt:592)
       at okhttp3.internal.ws.RealWebSocket$connect$1.onFailure(RealWebSocket.kt:202)
```

**Comment by martinbonnin** [comment]
@jvanderwee thanks for the feedback. This can happen if the `onError` callback is called while opening the WebSocket. I expected `OkHttp` to dispatch the callback but looks like this is not the case. I made a fix [here](https://github.com/apollographql/apollo-kotlin/pull/6197).

For the record, would you have the rest of the stacktrace so we can see what triggers this error?

**Comment by jvanderwee** [comment]
Thanks!

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void w6.u.close(int, java.lang.String)' on a null object reference
       at com.apollographql.apollo.network.websocket.internal.SubscribableWebSocket.shutdown(SubscribableWebSocket.kt:119)
       at com.apollographql.apollo.network.websocket.internal.SubscribableWebSocket.onError(SubscribableWebSocket.kt:220)
       at com.apollographql.apollo.network.websocket.JvmWebSocket.onFailure(WebSocketEngine.jvm.kt:67)
       at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.kt:592)
       at okhttp3.internal.ws.RealWebSocket$connect$1.onFailure(RealWebSocket.kt:202)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by jvanderwee** [comment]
Thanks @martinbonnin! When do you plan on publishing the 4.0.2 release?

**Comment by jvanderwee** [comment]
Thanks @martinbonnin 🙏 just trying out the snapshot, unable to pull in `apollo-testing-support` due to this:
```
Could not find apollo-kotlin:apollo-mockserver:unspecified.
     Searched in the following locations:
       - https://s01.oss.sonatype.org/content/repositories/snapshots/apollo-kotlin/apollo-mockserver/unspecified/apollo-mockserver-unspecified.pom
       - https://dl.google.com/dl/android/maven2/apollo-kotlin/apollo-mockserver/unspecified/apollo-mockserver-unspecified.pom
       - https://repo.maven.apache.org/maven2/apollo-kotlin/apollo-mockserver/unspecified/apollo-mockserver-unspecified.pom
     Required by:
         project :shared > com.apollographql.apollo:apollo-testing-support:4.0.2-SNAPSHOT:20241023.101530-26 > com.apollographql.apollo:apollo-testing-support-jvm:4.0.2-SNAPSHOT:20241023.101530-26
```

**Comment by martinbonnin** [comment]
Ah this is interesting! Probably due to the moving of mockserver. Thanks for reporting it, I'll take a look!

**Comment by martinbonnin** [comment]
@jvanderwee the new SNAPSHOT is [currently building](https://github.com/apollographql/apollo-kotlin/actions/runs/11497685396/job/32001895145). In the meantime, you can workaround with

```kotlin
configurations.configureEach {
    exclude(group= "apollo-kotlin", module = "apollo-mockserver")
}
```

**Comment by ronjunevaldoz** [comment]
`WebSocketEngine` is not yet implemented in WASMJS right? @martinbonnin

**Comment by martinbonnin** [comment]
@ronjunevaldoz this is correct. There are [no WebSockets for WasmJs yet](https://github.com/apollographql/apollo-kotlin/blob/7668a302eb5c62ca1d3e423ccfefa1142acee1f4/libraries/apollo-runtime/src/wasmJsMain/kotlin/com/apollographql/apollo/network/websocket/WebSocketEngine.wasmJs.kt#L4).

**Comment by sebj** [comment]
Is there a way to configure a dynamic (changeable) `serverUrl`? I'm working on our subscriptions for the first time, with no previous Apollo web socket implementation, but I can't help but notice that the old Apollo web sockets supported a `suspend` lambda for the `serverUrl`, which would be useful for our app which can currently switch between backend environments on the fly.

**Comment by martinbonnin** [comment]
@sebj changing the `serverUrl` on the fly is not possible indeed.

> our app which can currently switch between backend environments on the fly

Can you re-create the `ApolloClient` instead? Typically, different environments will have different data and require different caches. I'm hesitant to encourage changing the endpoing on the fly as it could have nasty consequences. Or maybe your environments share the same data?


PS: @ronjunevaldoz [websockets are now supported for wasm](https://github.com/apollographql/apollo-kotlin/pull/6637)

**Comment by kieranm** [comment]
@martinbonnin If we need to obtain a fresh access token and attach it to the URL (which may involve refreshing the token), what's the best way to do that if passing a function here is no longer supported?

We use AWS API Gateway websockets which require the requests to be authorised at connection time.

On the Apollo Web client, functions for the URL argument are supported - so wondering what the rationale is for dropping this.

Thanks a lot!

**Comment by martinbonnin** [comment]
> A query parameter is a pragmatic way to do this because headers can't be provided for websocket connection requests

Right. This use case indeed requires a new url. Thanks for providing details about the browser APIs, that explains a lot. 

> wondering what the rationale is for the different approach.

Mainly trying to document the use case and make sure this is still needed. Will add it to the TODO list.

**Comment by martinbonnin** [comment]
@damianpetla right, I contemplated that at some point but that idea never really went through. Mind creating a pull request to add a `isExceptionRecoverable` parameter to [`RetryOnErrorInterceptor`](https://github.com/apollographql/apollo-kotlin/blob/19fc22badd281acee897678c32cdad0987571206/libraries/apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo/interceptor/RetryOnErrorInterceptor.kt#L49)?

Things are a bit hectic right now with GraphQLConf just around the corner but I'm planning to sit down with that code in a couple of weeks and get it through the finish line (includes this and being able to change the url on the fly and we should be good to go).
