### ISSUE TITLE
Error parsing integer on Android 5 devices in release builds

### ISSUE THREAD

**Issue by eduardb** [apollographql/apollo-kotlin#5932]
### Version

3.8.4

### Summary

On release builds only, running on Android 5 ARMv7 devices, such as the Galaxy Note 3, some corruption seems to happen when parsing integers, raising the exception in the logs below.

The body being parsed, as logged by OkHttp, is this: 
```{"errors":[{"message":"Enter your secret code.","locations":[{"line":1,"column":134}],"path":["signup"],"code":"needs-pin"}],"data":{"signup":null}}```

Interestingly enough, the bug doesn't happen when running the app in debug mode.

### Steps to reproduce the behavior

Reproducer project: https://github.com/eduardb/ApolloAndroidLollipopParsingBugRepro
In particular, look at this code: https://github.com/eduardb/ApolloAndroidLollipopParsingBugRepro/blob/main/app/src/main/java/com/apollo/androidlollipopparsingbugrepro/MainActivity.kt#L41-L51

### Logs

```
com.apollographql.apollo3.exception.JsonDataException: Expected an int but was 4294967297 at path [errors, 0, locations, 0, line]
	at com.apollographql.apollo3.api.json.BufferedSourceJsonReader.nextInt(BufferedSourceJsonReader.kt:615)
	at com.apollographql.apollo3.api.internal.ResponseParser.readErrorLocation(ResponseParser.kt:137)
	at com.apollographql.apollo3.api.internal.ResponseParser.readErrorLocations(ResponseParser.kt:124)
	at com.apollographql.apollo3.api.internal.ResponseParser.readError(ResponseParser.kt:80)
	at com.apollographql.apollo3.api.internal.ResponseParser.readErrors(ResponseParser.kt:62)
	at com.apollographql.apollo3.api.internal.ResponseParser.parse(ResponseParser.kt:34)
	at com.apollographql.apollo3.api.Operations.parseJsonResponse(Operations.kt:63)
	at com.apollographql.apollo3.api.Operations.parseJsonResponse(Operations.kt:80)
	at com.apollographql.apollo3.api.Operations.parseJsonResponse$default(Operations.kt:76)
```

**Comment by eduardb** [comment]
Closing, as the bug doesn't reproduce anymore if Proguard/R8 is enabled with the `proguard-android-optimize.txt` rules, and figuring out what is going on in the non-optimized bytecode is a near-impossible task.
