### ISSUE TITLE
How to use Data Builders + Fake Resolver to set default values?

### ISSUE THREAD

**Issue by mformetal** [apollographql/apollo-kotlin#6160]
### Question

I'm currently migrating a bunch of Apollo2 -> Apollo3 code, and I saw the [data buidlers](https://www.apollographql.com/docs/kotlin/v3/testing/data-builders) feature to make creating apollo-types simpler for unit tests. 

We use the `customTypeMapping` for types such as:
```
customTypeMapping.putAll(
            mapOf(
                "CanonicalUrl" to "kotlin.String",
                ...
            )
        )
```

To make Apollo aware of this type when generating default values, I've used a shim implementation of `DefaultFakeResolver`:

```
private val resolver = object : DefaultFakeResolver(GraphqlPaymentsSchema.all + SportsbookPaymentsSchema.all) {
        override fun resolveLeaf(context: FakeResolverContext): Any {
            return when (context.mergedField.type.rawType().name) {
                "CanonicalUrl" -> ""
                else -> super.resolveLeaf(context)
            }
        }
    }
```

However, using this `resolver` results in a `NullPointerException` at the point of apollo's json-adapter call.

Without using this `resolver`, I get an error like: 
```
java.lang.IllegalStateException: Don't know how to instantiate leaf CanonicalUrl
	at com.apollographql.apollo3.api.DefaultFakeResolver.resolveLeaf(fakeResolver.kt:277)
```

Is the documentation missing a required step?

**Comment by BoD** [comment]
Hi! Could you paste the stacktrace of the NPE you're getting?

**Comment by mformetal** [comment]
> Hi! Could you paste the stacktrace of the NPE you're getting?

Of course, sorry to not post earlier:

```
java.lang.NullPointerException
	at bet.thescore.graphql.sportsbook.apollo3.fragment.BaseDeeplinkFragmentImpl_ResponseAdapter$BaseDeeplinkFragment.fromJson(BaseDeeplinkFragmentImpl_ResponseAdapter.kt:39)
	at bet.thescore.graphql.sportsbook.apollo3.fragment.DeeplinkFragmentImpl_ResponseAdapter$DeeplinkFragment$Fragments.fromJson(DeeplinkFragmentImpl_ResponseAdapter.kt:71)
	at bet.thescore.graphql.sportsbook.apollo3.fragment.DeeplinkFragmentImpl_ResponseAdapter$DeeplinkFragment.fromJson(DeeplinkFragmentImpl_ResponseAdapter.kt:40)
	at bet.thescore.graphql.sportsbook.apollo3.fragment.CasinoLobbyCategoryCarouselFragmentImpl_ResponseAdapter$DeepLinkOptional$Fragments.fromJson(CasinoLobbyCategoryCarouselFragmentImpl_ResponseAdapter.kt:133)
	at bet.thescore.graphql.sportsbook.apollo3.fragment.CasinoLobbyCategoryCarouselFragmentImpl_ResponseAdapter$DeepLinkOptional.fromJson(CasinoLobbyCategoryCarouselFragmentImpl_ResponseAdapter.kt:104)
	at bet.thescore.graphql.sportsbook.apollo3.fragment.CasinoLobbyCategoryCarouselFragmentImpl_ResponseAdapter$DeepLinkOptional.fromJson(CasinoLobbyCategoryCarouselFragmentImpl_ResponseAdapter.kt:87)
	at com.apollographql.apollo3.api.ObjectAdapter.fromJson(Adapters.kt:292)
	at com.apollographql.apollo3.api.NullableAdapter.fromJson(Adapters.kt:57)
	at bet.thescore.graphql.sportsbook.apollo3.fragment.CasinoLobbyCategoryCarouselFragmentImpl_ResponseAdapter$CasinoLobbyCategoryCarouselFragment.fromJson(CasinoLobbyCategoryCarouselFragmentImpl_ResponseAdapter.kt:43)
	at bet.thescore.graphql.sportsbook.apollo3.fragment.SearchResultShelfFragmentImpl_ResponseAdapter$SearchResultShelfChildren$Fragments.fromJson(SearchResultShelfFragmentImpl_ResponseAdapter.kt:133)
	at bet.thescore.graphql.sportsbook.apollo3.fragment.SearchResultShelfFragmentImpl_ResponseAdapter$SearchResultShelfChildren.fromJson(SearchResultShelfFragmentImpl_ResponseAdapter.kt:78)
	at bet.thescore.graphql.sportsbook.apollo3.fragment.SearchResultShelfFragmentImpl_ResponseAdapter$SearchResultShelfChildren.fromJson(SearchResultShelfFragmentImpl_ResponseAdapter.kt:61)
	at com.apollographql.apollo3.api.ObjectAdapter.fromJson(Adapters.kt:292)
	at com.apollographql.apollo3.api.ListAdapter.fromJson(Adapters.kt:30)
	at bet.thescore.graphql.sportsbook.apollo3.fragment.SearchResultShelfFragmentImpl_ResponseAdapter$SearchResultShelfFragment.fromJson(SearchResultShelfFragmentImpl_ResponseAdapter.kt:35)
	at bet.thescore.graphql.sportsbook.apollo3.fragment.SearchSectionFragmentImpl_ResponseAdapter$SectionChildren$Fragments.fromJson(SearchSectionFragmentImpl_ResponseAdapter.kt:120)
	at bet.thescore.graphql.sportsbook.apollo3.fragment.SearchSectionFragmentImpl_ResponseAdapter$SectionChildren.fromJson(SearchSectionFragmentImpl_ResponseAdapter.kt:86)
	at bet.thescore.graphql.sportsbook.apollo3.fragment.SearchSectionFragmentImpl_ResponseAdapter$SectionChildren.fromJson(SearchSectionFragmentImpl_ResponseAdapter.kt:69)
	at com.apollographql.apollo3.api.ObjectAdapter.fromJson(Adapters.kt:292)
	at com.apollographql.apollo3.api.ListAdapter.fromJson(Adapters.kt:30)
	at bet.thescore.graphql.sportsbook.apollo3.fragment.SearchSectionFragmentImpl_ResponseAdapter$SearchSectionFragment.fromJson(SearchSectionFragmentImpl_ResponseAdapter.kt:40)
	at bet.thescore.graphql.sportsbook.apollo3.queries.adapter.SearchQuery_ResponseAdapter$PageChildren$Fragments.fromJson(SearchQuery_ResponseAdapter.kt:122)
	at bet.thescore.graphql.sportsbook.apollo3.queries.adapter.SearchQuery_ResponseAdapter$PageChildren.fromJson(SearchQuery_ResponseAdapter.kt:95)
	at bet.thescore.graphql.sportsbook.apollo3.queries.adapter.SearchQuery_ResponseAdapter$PageChildren.fromJson(SearchQuery_ResponseAdapter.kt:80)
	at com.apollographql.apollo3.api.ObjectAdapter.fromJson(Adapters.kt:292)
	at com.apollographql.apollo3.api.ListAdapter.fromJson(Adapters.kt:30)
	at bet.thescore.graphql.sportsbook.apollo3.queries.adapter.SearchQuery_ResponseAdapter$Page.fromJson(SearchQuery_ResponseAdapter.kt:60)
	at bet.thescore.graphql.sportsbook.apollo3.queries.adapter.SearchQuery_ResponseAdapter$Page.fromJson(SearchQuery_ResponseAdapter.kt:51)
	at com.apollographql.apollo3.api.ObjectAdapter.fromJson(Adapters.kt:292)
	at com.apollographql.apollo3.api.NullableAdapter.fromJson(Adapters.kt:57)
	at bet.thescore.graphql.sportsbook.apollo3.queries.adapter.SearchQuery_ResponseAdapter$Data.fromJson(SearchQuery_ResponseAdapter.kt:31)
	at bet.thescore.graphql.sportsbook.apollo3.queries.adapter.SearchQuery_ResponseAdapter$Data.fromJson(SearchQuery_ResponseAdapter.kt:22)
	at com.apollographql.apollo3.api.ObjectAdapter.fromJson(Adapters.kt:292)
	at com.apollographql.apollo3.api.FakeResolverKt.buildData(fakeResolver.kt:334)
	at bet.thescore.graphql.sportsbook.apollo3.queries.SearchQuery$Companion.Data(SearchQuery.kt:623)
	at bet.thescore.android.ui.search.apollo3.sportsbook.SearchResultsTransformerTest.verify section with no children has 0 for badge count(SearchResultsTransformerTest.kt:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:119)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:94)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:89)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy2/jdk.proxy2.$Proxy5.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

**Comment by mformetal** [comment]
That custom adapter:

```
class StringTypeConverter : CustomTypeAdapter<String> {
    override fun encode(value: String) = CustomTypeValue.GraphQLString(value)

    override fun decode(value: CustomTypeValue<*>) = value.value.toString()
}
```

Line 39 of that generated class:
```
public object BaseDeeplinkFragmentImpl_ResponseAdapter {
  public object BaseDeeplinkFragment :
      Adapter<bet.thescore.graphql.sportsbook.apollo3.fragment.BaseDeeplinkFragment> {
    public val RESPONSE_NAMES: List<String> = listOf("__typename", "canonicalUrl")

    public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
        bet.thescore.graphql.sportsbook.apollo3.fragment.BaseDeeplinkFragment {
      var __typename: String? = null
      var _canonicalUrl: String? = null

      while(true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> __typename = StringAdapter.fromJson(reader, customScalarAdapters)
          1 -> _canonicalUrl = customScalarAdapters.responseAdapterFor<String>(CanonicalUrl.type).fromJson(reader,
              customScalarAdapters)
          else -> break
        }
      }

      return bet.thescore.graphql.sportsbook.apollo3.fragment.BaseDeeplinkFragment(
        __typename = __typename!!,
        canonicalUrl = _canonicalUrl!! **<-- line 39**
      )
    }

    public override fun toJson(
      writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters,
      `value`: bet.thescore.graphql.sportsbook.apollo3.fragment.BaseDeeplinkFragment,
    ): Unit {
      writer.name("__typename")
      StringAdapter.toJson(writer, customScalarAdapters, value.__typename)

      writer.name("canonicalUrl")
      customScalarAdapters.responseAdapterFor<String>(CanonicalUrl.type).toJson(writer,
          customScalarAdapters, value.canonicalUrl)
    }
  }
}
```

It uses the `!!` operator which doesn't seem safe?

**Comment by BoD** [comment]
Hmm I still don't understand why this doesn't work, but I can recommend that first you migrate to using a v3 adapter for your scalar(s) ([migration guide](https://www.apollographql.com/docs/kotlin/v3/migration/3.0#custom-scalar-adapters)) - doing so should help the investigation a bit.

**Comment by mformetal** [comment]
> Hmm I still don't understand why this doesn't work, but I can recommend that first you migrate to using a v3 adapter for your scalar(s) ([migration guide](https://www.apollographql.com/docs/kotlin/v3/migration/3.0#custom-scalar-adapters)) - doing so should help the investigation a bit.

Perhaps it's this project's way of handling dependencies. 

Instead of all our code being in one github repository, we have two: one that publishes apollo-generated code, and one that consumes it. 

Publish logic:
```
create<MavenPublication>("client-debug") {
        from(project.components["debug"])
        groupId = // group
        artifactId = // id
        version = // unfortunately a github sha
    }
```

If a project then consumes that artifact as such:
```
implementation(// artifact id)
```

Could that be the source of the issue?

**Comment by BoD** [comment]
I don't think the multi module setup should cause any issue. 

Something else to check: it looks like you have several schemas and use the same FakeResolver (`DefaultFakeResolver(GraphqlPaymentsSchema.all + SportsbookPaymentsSchema.all)`) for both - I don't think that's really supported, can you try using one per schema?

**Comment by mformetal** [comment]
> I don't think the multi module setup should cause any issue.
> 
> Something else to check: it looks like you have several schemas and use the same FakeResolver (`DefaultFakeResolver(GraphqlPaymentsSchema.all + SportsbookPaymentsSchema.all)`) for both - I don't think that's really supported, can you try using one per schema?

We have two modules with a `schema` defined: one in a module named `graphql`, and the other in a module named `payments`. If I just import and use one of them (i.e. `__Schema.all`), Apollo doesn't seem to set default values of data types defined in one schema but not the other.

Is there another way to merge the two?

**Comment by martinbonnin** [comment]
It's not really possible to merge 2 schemas. The types could clash, etc... You'll have to use a `FakeResolver` matching your operation.

A reproducer wuold help a ton understanding what's going on here.

**Comment by mformetal** [comment]
> It's not really possible to merge 2 schemas. The types could clash, etc... You'll have to use a `FakeResolver` matching your operation.
> 
> A reproducer wuold help a ton understanding what's going on here.

I can get a small reproducer to you in just a moment

**Comment by mformetal** [comment]
It actually looks like the issue was in merging the two different `__Schema` files - using one or the other works in the majority of cases, but having to map between the two for things that are "already" implemented is a bit cumbersome. Thanks for your help!
