### ISSUE TITLE
Idling Resource - Message indicating that the resource has transitioned from busy to idle was never sent

### ISSUE THREAD

**Issue by shendriksen** [apollographql/apollo-kotlin#849]
We have come across an issue with the ApolloIdlingResource that causes our Espresso tests to fail.

With the current ApolloIdlingResource our tests fail intermittently due to the below error:

```
java.lang.IllegalStateException: Resource apollo-client isIdleNow() is returning true, but a message indicating that the resource has transitioned from busy to idle was never sent.
at android.support.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleRaceCondition(IdlingResourceRegistry.java:481)
at android.support.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleMessage(IdlingResourceRegistry.java:403)
at android.os.Handler.dispatchMessage(Handler.java:101)
at android.support.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:160)
at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:472)
at android.support.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:381)
at android.support.test.espresso.ViewInteraction$2.call(ViewInteraction.java:261)
at android.support.test.espresso.ViewInteraction$2.call(ViewInteraction.java:258)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6541)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

Looking into the issue it appears that the `callback.onTransitionToIdle();` code is not run as the callback is null at the point the `apolloClient.idleCallback()` is made.

Moving the callback to the `isIdleNow()` method appears to resolve the issue for us.
isIdleNow method changes:

```
    @Override
    public boolean isIdleNow() {
        boolean idle = (apolloClient.activeCallsCount() == 0);

        ResourceCallback callback = ApolloIdlingResource.this.callback;
        if (idle && callback != null) {
            callback.onTransitionToIdle();
        }

        return idle;
    }
```

For our test setup we register the resource before and unregister after each test:

`IdlingRegistry.getInstance().register(apolloIdlingResource);`
`IdlingRegistry.getInstance().unregister(apolloIdlingResource);`

Where our `apolloIdlingResource` is:
`private ApolloIdlingResource apolloIdlingResource = ApolloIdlingResource.create("apollo-client", apolloClient);`

Is there a better solution to this issue?

**Comment by digitalbuddha** [comment]
@VisheshVadhera mind taking a look, not sure if something jumps out at you.

**Comment by VisheshVadhera** [comment]
@digitalbuddha @shendriksen Somehow completely missed the mention. Let me take a look and get back.

**Comment by tasomaniac** [comment]
Any update on this? Is this still reproducable? We have been using the idling resource support on our project and we never got such crash. Can you double check how you integrate?

**Comment by ahmedMubarak2024** [comment]
@tasomaniac  yes just got it over here espresso-core:3.2.0 "java.lang.IllegalStateException: Resource is user in cache isIdleNow() is returning true, but a message indicating that the resource has transitioned from busy to idle was never sent." what happened was i want to wait until some request get done so i put this on a sharedpref mock and using a map and it was checking for a value in it

**Comment by tasomaniac** [comment]
It would be great if you can share your setup. I guess it may depend on the setup. We have this IdlingResource integrated in our project for ~6months and had no issues so far.

**Comment by martinbonnin** [comment]
Hi 👋 Can you try with [Apollo Android 3](https://github.com/apollographql/apollo-android/releases/tag/v3.0.0-rc01)?

**Comment by martinbonnin** [comment]
Closing as obsolete. Please leave a message if anyone's bumping into this
